import { useEffect, useMemo, useRef, useState } from "react";
import "./ResearchCanvasPage.css";

type Card = { id:string; type:string; title:string; content:string; x:number; y:number; width:number; height:number; sourcePath?:string; sourceLabel?:string; pageNumber?:number|null };
type Connection = { id:string; fromId:string; toId:string; label:string; note?:string };
type Canvas = { id:string; title:string; description:string; cards:Card[]; connections:Connection[]; viewport:{x:number;y:number;zoom:number}; gridSize:number; snapToGrid:boolean; createdAt:string; updatedAt:string };
type Notebook = { id:string; title:string; evidence:Array<{id:string;type:string;title:string;excerpt:string;projectPath:string;projectName:string;documentName:string;pageNumber:number|null}> };

const uid = (prefix:string) => `${prefix}-${Date.now()}-${Math.random().toString(16).slice(2)}`;
const cardTypes = ["Research Note","OCR Passage","Page","Entity","Relationship","Timeline Event","Place","Citation","Comparison"];
const relationLabels = ["Supports","Contradicts","Refers To","Variant Of","Causes","Precedes","Located At","Mentions","Derived From"];

export default function ResearchCanvasPage(){
  const [workspacePath,setWorkspacePath]=useState("");
  const [canvases,setCanvases]=useState<Canvas[]>([]); const [selectedId,setSelectedId]=useState("");
  const [notebooks,setNotebooks]=useState<Notebook[]>([]); const [newTitle,setNewTitle]=useState("");
  const [message,setMessage]=useState(""); const [selectedCardIds,setSelectedCardIds]=useState<string[]>([]);
  const [connectFrom,setConnectFrom]=useState(""); const [relation,setRelation]=useState("Supports");
  const [cardDraft,setCardDraft]=useState({type:"Research Note",title:"",content:"",sourcePath:"",sourceLabel:""});
  const [history,setHistory]=useState<Canvas[]>([]); const [future,setFuture]=useState<Canvas[]>([]);
  const dragging=useRef<{id:string;dx:number;dy:number}|null>(null); const panning=useRef<{x:number;y:number;ox:number;oy:number}|null>(null);
  const saveTimer=useRef<number|null>(null);
  const selected=canvases.find(c=>c.id===selectedId)||null;

  async function load(path=workspacePath){ if(!path)return; const data=await window.ocrStudio.listResearchCanvases({workspacePath:path}); setCanvases(data.canvases||[]); setSelectedId(id=>(data.canvases||[]).some((c:Canvas)=>c.id===id)?id:(data.canvases?.[0]?.id||"")); }
  useEffect(()=>{(async()=>{const projects=await window.ocrStudio.listRecentProjects(); const path=projects.find((p:any)=>p.workspacePath)?.workspacePath||""; setWorkspacePath(path); if(path){await load(path); const wb=await window.ocrStudio.listResearchNotebooks({workspacePath:path}); setNotebooks(wb.notebooks||[]);}})().catch(e=>setMessage(e.message));},[]);

  function commit(next:Canvas,remember=true){ if(!selected)return; if(remember){setHistory(h=>[...h.slice(-29),selected]);setFuture([]);} setCanvases(items=>items.map(c=>c.id===next.id?next:c)); if(saveTimer.current)window.clearTimeout(saveTimer.current); saveTimer.current=window.setTimeout(async()=>{try{await window.ocrStudio.updateResearchCanvas({workspacePath,canvas:next});setMessage("Canvas autosaved.");}catch(e:any){setMessage(e.message);}},500); }
  async function createCanvas(){if(!workspacePath||!newTitle.trim())return;const created=await window.ocrStudio.createResearchCanvas({workspacePath,canvas:{title:newTitle,description:"",cards:[],connections:[]}});setCanvases(cs=>[created,...cs]);setSelectedId(created.id);setNewTitle("");}
  async function deleteCanvas(){if(!selected||!confirm(`Delete “${selected.title}”?`))return;await window.ocrStudio.deleteResearchCanvas({workspacePath,canvasId:selected.id});await load();}
  function addCard(input=cardDraft){if(!selected||!input.title.trim())return;const offset=selected.cards.length*28;const card:Card={id:uid("card"),type:input.type,title:input.title.trim(),content:input.content||"",x:100+offset,y:100+offset,width:280,height:170,sourcePath:input.sourcePath||"",sourceLabel:input.sourceLabel||""};commit({...selected,cards:[...selected.cards,card],updatedAt:new Date().toISOString()});setCardDraft({type:"Research Note",title:"",content:"",sourcePath:"",sourceLabel:""});}
  function addEvidence(ev:Notebook["evidence"][number]){addCard({type:ev.type,title:ev.title,content:ev.excerpt,sourcePath:ev.projectPath,sourceLabel:[ev.projectName,ev.documentName,ev.pageNumber?`Page ${ev.pageNumber}`:""].filter(Boolean).join(" · ")});}
  function updateCard(id:string,patch:Partial<Card>,remember=true){if(!selected)return;commit({...selected,cards:selected.cards.map(c=>c.id===id?{...c,...patch}:c)},remember);}
  function removeSelected(){if(!selected||!selectedCardIds.length)return;const ids=new Set(selectedCardIds);commit({...selected,cards:selected.cards.filter(c=>!ids.has(c.id)),connections:selected.connections.filter(e=>!ids.has(e.fromId)&&!ids.has(e.toId))});setSelectedCardIds([]);}
  function connect(cardId:string){if(!selected)return;if(!connectFrom){setConnectFrom(cardId);setMessage("Select the target card.");return;}if(connectFrom===cardId){setConnectFrom("");return;}const exists=selected.connections.some(e=>e.fromId===connectFrom&&e.toId===cardId&&e.label===relation);if(!exists)commit({...selected,connections:[...selected.connections,{id:uid("edge"),fromId:connectFrom,toId:cardId,label:relation}]});setConnectFrom("");}
  function undo(){if(!selected||!history.length)return;const prev=history[history.length-1];setFuture(f=>[selected,...f]);setHistory(h=>h.slice(0,-1));setCanvases(cs=>cs.map(c=>c.id===selected.id?prev:c));window.ocrStudio.updateResearchCanvas({workspacePath,canvas:prev});}
  function redo(){if(!selected||!future.length)return;const next=future[0];setHistory(h=>[...h,selected]);setFuture(f=>f.slice(1));setCanvases(cs=>cs.map(c=>c.id===selected.id?next:c));window.ocrStudio.updateResearchCanvas({workspacePath,canvas:next});}
  const cardMap=useMemo(()=>new Map((selected?.cards||[]).map(c=>[c.id,c])),[selected?.cards]);
  const analytics=useMemo(()=>{const cards=selected?.cards.length||0;const edges=selected?.connections.length||0;const connected=new Set((selected?.connections||[]).flatMap(e=>[e.fromId,e.toId])).size;return{cards,edges,orphans:Math.max(0,cards-connected),density:cards>1?(edges/(cards*(cards-1))).toFixed(2):"0.00"}},[selected]);
  function onMove(e:React.MouseEvent){if(!selected)return;if(dragging.current){const rect=(e.currentTarget as HTMLElement).getBoundingClientRect();const vx=(e.clientX-rect.left-selected.viewport.x)/selected.viewport.zoom;const vy=(e.clientY-rect.top-selected.viewport.y)/selected.viewport.zoom;const grid=selected.snapToGrid?selected.gridSize:1;updateCard(dragging.current.id,{x:Math.round((vx-dragging.current.dx)/grid)*grid,y:Math.round((vy-dragging.current.dy)/grid)*grid},false);}else if(panning.current){commit({...selected,viewport:{...selected.viewport,x:panning.current.ox+e.clientX-panning.current.x,y:panning.current.oy+e.clientY-panning.current.y}},false);}}
  function stopPointer(){if(dragging.current&&selected)window.ocrStudio.updateResearchCanvas({workspacePath,canvas:selected});dragging.current=null;panning.current=null;}
  function startDrag(e:React.MouseEvent,card:Card){e.stopPropagation();if(!selected)return;const rect=(e.currentTarget.parentElement?.parentElement as HTMLElement).getBoundingClientRect();dragging.current={id:card.id,dx:(e.clientX-rect.left-selected.viewport.x)/selected.viewport.zoom-card.x,dy:(e.clientY-rect.top-selected.viewport.y)/selected.viewport.zoom-card.y};}
  function exportCanvas(format:"json"|"svg"|"html"){if(!selected)return;window.ocrStudio.exportResearchCanvas({workspacePath,canvasId:selected.id,format}).then((r:any)=>{if(r.filePath)setMessage(`Exported to ${r.filePath}`)}).catch((e:any)=>setMessage(e.message));}

  return <div className="canvas-page"><header className="canvas-hero"><div><span>PHASE 8.0C</span><h2>Visual Research Canvas</h2><p>Arrange manuscript evidence, build arguments, and preserve direct links to source material.</p></div><div className="canvas-metrics"><b>{analytics.cards}</b><small>Cards</small><b>{analytics.edges}</b><small>Connections</small><b>{analytics.orphans}</b><small>Orphans</small><b>{analytics.density}</b><small>Density</small></div></header>
  {message&&<div className="canvas-message">{message}</div>}
  <div className="canvas-shell"><aside className="canvas-sidebar"><div className="create-canvas"><input placeholder="New canvas title" value={newTitle} onChange={e=>setNewTitle(e.target.value)} onKeyDown={e=>e.key==="Enter"&&createCanvas()}/><button onClick={createCanvas}>＋ Create</button></div><div className="canvas-list">{canvases.map(c=><button className={c.id===selectedId?"active":""} key={c.id} onClick={()=>{setSelectedId(c.id);setHistory([]);setFuture([])}}><strong>{c.title}</strong><small>{c.cards.length} cards · {c.connections.length} links</small></button>)}</div>
  {selected&&<><hr/><h3>Add card</h3><select value={cardDraft.type} onChange={e=>setCardDraft({...cardDraft,type:e.target.value})}>{cardTypes.map(t=><option key={t}>{t}</option>)}</select><input placeholder="Card title" value={cardDraft.title} onChange={e=>setCardDraft({...cardDraft,title:e.target.value})}/><textarea placeholder="Notes or quoted evidence" value={cardDraft.content} onChange={e=>setCardDraft({...cardDraft,content:e.target.value})}/><button onClick={()=>addCard()}>Add to canvas</button><h3>Notebook evidence</h3><div className="evidence-picker">{notebooks.flatMap(n=>n.evidence.map(ev=><button key={`${n.id}-${ev.id}`} onClick={()=>addEvidence(ev)}><b>{ev.title}</b><small>{n.title} · {ev.type}</small></button>))}</div></>}</aside>
  <main className="canvas-workspace">{selected?<><div className="canvas-toolbar"><input className="canvas-title" value={selected.title} onChange={e=>commit({...selected,title:e.target.value})}/><select value={relation} onChange={e=>setRelation(e.target.value)}>{relationLabels.map(x=><option key={x}>{x}</option>)}</select><button className={connectFrom?"active":""} onClick={()=>setConnectFrom("")}>{connectFrom?"Cancel link":"Link: click cards"}</button><button onClick={undo} disabled={!history.length}>Undo</button><button onClick={redo} disabled={!future.length}>Redo</button><button onClick={()=>commit({...selected,viewport:{x:0,y:0,zoom:1}})}>Reset view</button><label><input type="checkbox" checked={selected.snapToGrid} onChange={e=>commit({...selected,snapToGrid:e.target.checked})}/> Snap</label><button onClick={()=>exportCanvas("svg")}>SVG</button><button onClick={()=>exportCanvas("html")}>HTML</button><button onClick={()=>exportCanvas("json")}>JSON</button><button className="danger" onClick={removeSelected} disabled={!selectedCardIds.length}>Delete cards</button><button className="danger" onClick={deleteCanvas}>Delete canvas</button></div>
  <div className="stage" onMouseDown={e=>{if(e.target===e.currentTarget)panning.current={x:e.clientX,y:e.clientY,ox:selected.viewport.x,oy:selected.viewport.y}}} onMouseMove={onMove} onMouseUp={stopPointer} onMouseLeave={stopPointer} onWheel={e=>{e.preventDefault();const zoom=Math.min(2.2,Math.max(.35,selected.viewport.zoom+(e.deltaY<0?.1:-.1)));commit({...selected,viewport:{...selected.viewport,zoom}},false)}} style={{backgroundSize:`${selected.gridSize*selected.viewport.zoom}px ${selected.gridSize*selected.viewport.zoom}px`,backgroundPosition:`${selected.viewport.x}px ${selected.viewport.y}px`}}>
  <div className="world" style={{transform:`translate(${selected.viewport.x}px,${selected.viewport.y}px) scale(${selected.viewport.zoom})`}}><svg className="connections"><defs><marker id="arrow" markerWidth="10" markerHeight="10" refX="8" refY="3" orient="auto"><path d="M0,0 L0,6 L9,3 z"/></marker></defs>{selected.connections.map(edge=>{const a=cardMap.get(edge.fromId),b=cardMap.get(edge.toId);if(!a||!b)return null;const x1=a.x+a.width/2,y1=a.y+a.height/2,x2=b.x+b.width/2,y2=b.y+b.height/2;return <g key={edge.id}><line x1={x1} y1={y1} x2={x2} y2={y2}/><text x={(x1+x2)/2} y={(y1+y2)/2-8}>{edge.label}</text></g>})}</svg>{selected.cards.map(card=><article className={`canvas-card ${selectedCardIds.includes(card.id)?"selected":""} ${connectFrom===card.id?"link-source":""}`} key={card.id} style={{left:card.x,top:card.y,width:card.width,height:card.height}} onClick={e=>{e.stopPropagation();if(connectFrom){connect(card.id);return;}setSelectedCardIds(ids=>e.shiftKey?(ids.includes(card.id)?ids.filter(x=>x!==card.id):[...ids,card.id]):[card.id])}}><header onMouseDown={e=>startDrag(e,card)}><span>{card.type}</span><button onClick={e=>{e.stopPropagation();connect(card.id)}}>🔗</button></header><input value={card.title} onChange={e=>updateCard(card.id,{title:e.target.value})}/><textarea value={card.content} onChange={e=>updateCard(card.id,{content:e.target.value})}/>{card.sourceLabel&&<small>{card.sourceLabel}</small>}{card.sourcePath&&<button className="source-btn" onClick={e=>{e.stopPropagation();window.ocrStudio.openResearchCanvasSource(card.sourcePath!)}}>Open source</button>}<div className="resize" onMouseDown={e=>{e.stopPropagation();const sx=e.clientX,sy=e.clientY,w=card.width,h=card.height;const move=(ev:MouseEvent)=>updateCard(card.id,{width:Math.max(200,w+ev.clientX-sx),height:Math.max(130,h+ev.clientY-sy)},false);const up=()=>{window.removeEventListener("mousemove",move);window.removeEventListener("mouseup",up);};window.addEventListener("mousemove",move);window.addEventListener("mouseup",up)}}/></article>)}</div></div></>:<div className="canvas-empty"><h3>Create a research canvas</h3><p>Then add notes or evidence from your research notebooks.</p></div>}</main></div></div>
}
