import {useEffect,useMemo,useState} from "react";
import "./PublicScholarlyPortalPage.css";
type Project={projectPath:string;projectName:string};
const api=window.ocrStudio as any;
const blankSite={id:"",title:"",shortTitle:"",subtitle:"",description:"",publisher:"",license:"CC BY 4.0",access:"Public",status:"Draft",accentColor:"#a64b14",domain:""};
const blankPage={id:"",siteId:"",title:"About this edition",content:"",order:1,status:"Published"};
export default function PublicScholarlyPortalPage(){
 const[projects,setProjects]=useState<Project[]>([]),[projectPath,setProjectPath]=useState(""),[sites,setSites]=useState<any[]>([]),[pages,setPages]=useState<any[]>([]),[analytics,setAnalytics]=useState<any[]>([]),[metrics,setMetrics]=useState<any>({}),[site,setSite]=useState<any>(blankSite),[page,setPage]=useState<any>(blankPage),[tab,setTab]=useState("site"),[message,setMessage]=useState("");
 const load=async(p:string)=>{if(!p)return;const r=await api.getPublicPortalProject({projectPath:p});if(r.success){setSites(r.sites);setPages(r.pages);setAnalytics(r.analytics);setMetrics(r.metrics)}};
 useEffect(()=>{api.getPublicPortalWorkspace().then((r:any)=>{const ps=r.projects||[];setProjects(ps);const p=ps[0]?.projectPath||"";setProjectPath(p);load(p)})},[]);
 const readiness=useMemo(()=>{const missing=["title","publisher","license","access"].filter(k=>!String(site[k]||"").trim());return{ready:!missing.length,missing}},[site]);
 const saveSite=async()=>{const r=await api.savePublicPortalSite({projectPath,...site});setSite(r.site);setMessage("Portal configuration saved.");await load(projectPath)};
 const savePage=async()=>{if(!site.id)return setMessage("Save or select a portal first.");const r=await api.savePublicPortalPage({projectPath,...page,siteId:site.id});setPage(r.page);setMessage("Public page saved.");await load(projectPath)};
 const generate=async()=>{if(!site.id)return setMessage("Save the portal first.");if(!readiness.ready)return setMessage(`Complete: ${readiness.missing.join(", ")}`);setMessage("Generating responsive portal and search index…");const r=await api.generatePublicPortal({projectPath,site});if(r.success){setMessage(`Portal generated with ${r.recordCount} searchable records and ${r.pageCount} custom pages.`);await load(projectPath);await api.openPublicPortalFile(r.indexPath)}};
 return <div className="portal-page"><header><div><h2>Public Scholarly Web Portal</h2><p>Build a responsive reader, searchable public collection, and static research API from approved project content.</p></div><select value={projectPath} onChange={e=>{setProjectPath(e.target.value);load(e.target.value)}}>{projects.map(p=><option key={p.projectPath} value={p.projectPath}>{p.projectName}</option>)}</select></header>
 <section className="portal-metrics">{[["Sites",metrics.sites],["Published",metrics.published],["Custom pages",metrics.pages],["Portal exports",metrics.exports],["Public sites",metrics.publicSites]].map(([a,b])=><article key={String(a)}><b>{b||0}</b><span>{a}</span></article>)}</section>
 <nav>{["site","pages","publishing"].map(x=><button key={x} className={tab===x?"active":""} onClick={()=>setTab(x)}>{x}</button>)}</nav>{message&&<p className="portal-notice">{message}</p>}
 {tab==="site"&&<div className="portal-grid"><aside><h3>Portal sites</h3><button className="new" onClick={()=>setSite(blankSite)}>+ New portal</button>{sites.map(s=><button className="site-card" key={s.id} onClick={()=>{setSite(s);setPage({...blankPage,siteId:s.id})}}><b>{s.title||"Untitled portal"}</b><span>{s.status} · {s.access}</span></button>)}</aside><section className="portal-editor"><h3>{site.id?"Edit portal":"New public portal"}</h3><label>Portal title<input value={site.title} onChange={e=>setSite({...site,title:e.target.value})}/></label><label>Subtitle<input value={site.subtitle} onChange={e=>setSite({...site,subtitle:e.target.value})}/></label><label>Description<textarea value={site.description} onChange={e=>setSite({...site,description:e.target.value})}/></label><div className="two"><label>Publisher<input value={site.publisher} onChange={e=>setSite({...site,publisher:e.target.value})}/></label><label>Licence<input value={site.license} onChange={e=>setSite({...site,license:e.target.value})}/></label></div><div className="three"><label>Status<select value={site.status} onChange={e=>setSite({...site,status:e.target.value})}>{["Draft","Under Review","Published","Archived"].map(x=><option key={x}>{x}</option>)}</select></label><label>Access<select value={site.access} onChange={e=>setSite({...site,access:e.target.value})}>{["Public","Embargoed","Institution-only","Private"].map(x=><option key={x}>{x}</option>)}</select></label><label>Accent color<input type="color" value={site.accentColor} onChange={e=>setSite({...site,accentColor:e.target.value})}/></label></div><label>Public domain or base URL<input placeholder="https://edition.example.org" value={site.domain} onChange={e=>setSite({...site,domain:e.target.value})}/></label><div className={readiness.ready?"ready":"not-ready"}><b>{readiness.ready?"Ready to generate":"Configuration incomplete"}</b>{!readiness.ready&&<span>Missing: {readiness.missing.join(", ")}</span>}</div><div className="actions"><button onClick={saveSite}>Save portal</button>{site.id&&<button className="danger" onClick={async()=>{await api.deletePublicPortalSite({projectPath,id:site.id});setSite(blankSite);await load(projectPath)}}>Delete</button>}</div></section></div>}
 {tab==="pages"&&<div className="portal-grid"><aside><h3>Public pages</h3><button className="new" onClick={()=>setPage({...blankPage,siteId:site.id})}>+ New page</button>{pages.filter(p=>!site.id||p.siteId===site.id).map(p=><button className="site-card" key={p.id} onClick={()=>setPage(p)}><b>{p.title}</b><span>{p.status} · order {p.order}</span></button>)}</aside><section className="portal-editor"><h3>Page editor</h3><label>Title<input value={page.title} onChange={e=>setPage({...page,title:e.target.value})}/></label><label>Content<textarea className="large" value={page.content} onChange={e=>setPage({...page,content:e.target.value})}/></label><div className="two"><label>Order<input type="number" value={page.order} onChange={e=>setPage({...page,order:Number(e.target.value)})}/></label><label>Status<select value={page.status} onChange={e=>setPage({...page,status:e.target.value})}><option>Draft</option><option>Published</option></select></label></div><div className="actions"><button onClick={savePage}>Save page</button>{page.id&&<button className="danger" onClick={async()=>{await api.deletePublicPortalPage({projectPath,id:page.id});setPage({...blankPage,siteId:site.id});await load(projectPath)}}>Delete</button>}</div></section></div>}
 {tab==="publishing"&&<section className="publish-panel"><h3>Static portal publisher</h3><p>The generated folder works without a server and includes a responsive reader, full-text client search, structured JSON endpoints, publication metadata, and a web-app manifest.</p><div className="feature-grid">{["Responsive scholarly reader","Full-text and entity search","Static JSON research API","Custom public pages","Offline-friendly deployment","Institutional branding"].map(x=><article key={x}>✓ {x}</article>)}</div><button className="generate" onClick={generate}>Generate and open public portal</button><h4>Generation history</h4>{analytics.map(a=><article className="history" key={a.id}><b>{a.type}</b><span>{a.details} · {new Date(a.createdAt).toLocaleString()}</span>{a.outputPath&&<button onClick={()=>api.openPublicPortalFile(a.outputPath)}>Open folder</button>}</article>)}</section>}
 </div>;
}
