import {useEffect,useMemo,useState} from 'react';
import {getProjects} from '../../services/projectStorage';
import './StemmaWorkbenchPage.css';
const blank={parentId:'',childId:'',confidence:70,basis:'Textual agreement',evidence:'',notes:''};
export default function StemmaWorkbenchPage(){
 const [workspaces,setWorkspaces]=useState<string[]>([]),[workspacePath,setWorkspacePath]=useState(''),[data,setData]=useState<any>({witnesses:[],relationships:[],analysis:{pairs:[],inferredEdges:[],summary:{}}}),[message,setMessage]=useState('Select a workspace.'),[tab,setTab]=useState('overview'),[form,setForm]=useState<any>(blank),[filter,setFilter]=useState('');
 useEffect(()=>{void getProjects().then(ps=>{const w=[...new Set(ps.map(p=>p.workspacePath).filter(Boolean))] as string[];setWorkspaces(w);if(w[0])setWorkspacePath(w[0])})},[]);
 const load=async()=>{if(!workspacePath)return;const r=await window.ocrStudio.getStemmaAnalysis({workspacePath});setData(r);setMessage(r.message)};
 useEffect(()=>{void load()},[workspacePath]);
 const save=async()=>{const r=await window.ocrStudio.saveStemmaRelationship({workspacePath,relationship:form});setMessage(r.message);if(r.success){setForm(blank);await load()}};
 const exportIt=async(format:string)=>{const r=await window.ocrStudio.exportStemmaAnalysis({workspacePath,format});setMessage(r.message);if(r.success)await window.ocrStudio.openStemmaExport(r.filePath)};
 const witnesses=data.witnesses||[],pairs=(data.analysis?.pairs||[]).filter((p:any)=>!filter||`${p.a.siglum} ${p.b.siglum}`.toLowerCase().includes(filter.toLowerCase())),edges=[...(data.relationships||[]),...(data.analysis?.inferredEdges||[])];
 const matrix=useMemo(()=>{const m:any={};for(const p of data.analysis?.pairs||[]){m[`${p.a.id}|${p.b.id}`]=p.similarity;m[`${p.b.id}|${p.a.id}`]=p.similarity}return m},[data]);
 return <div className="st-page"><header className="st-hero"><div><span>Phase 10B · Milestone 4</span><h2>Variant Analysis & Stemma Workbench</h2><p>Measure witness affinity, inspect shared innovations, and model manuscript descent.</p></div><div><button onClick={()=>void load()}>Re-analyze</button><button onClick={()=>exportIt('svg')}>Export SVG</button></div></header>
 <section className="st-toolbar"><label>Workspace<select value={workspacePath} onChange={e=>setWorkspacePath(e.target.value)}>{workspaces.map(w=><option key={w}>{w}</option>)}</select></label><span>{message}</span></section>
 <nav className="st-tabs">{[['overview','Overview'],['matrix','Agreement matrix'],['tree','Stemma'],['relationships','Relationships']].map(([id,label])=><button key={id} className={tab===id?'active':''} onClick={()=>setTab(id)}>{label}</button>)}</nav>
 {tab==='overview'&&<><section className="st-stats"><article><b>{data.analysis?.witnessCount||0}</b><span>Witnesses</span></article><article><b>{data.analysis?.collationCount||0}</b><span>Collations</span></article><article><b>{data.analysis?.summary?.averageSimilarity||0}%</b><span>Average agreement</span></article><article><b>{data.analysis?.summary?.sharedInnovations||0}</b><span>Shared innovations</span></article></section><section className="st-panel"><div className="st-panel-head"><h3>Witness affinity</h3><input placeholder="Filter sigla" value={filter} onChange={e=>setFilter(e.target.value)}/></div>{pairs.length===0?<p>Save collations with at least two witnesses to calculate affinities.</p>:pairs.sort((a:any,b:any)=>b.similarity-a.similarity).map((p:any)=><article className="st-pair" key={`${p.a.id}-${p.b.id}`}><div><b>{p.a.siglum} ⇄ {p.b.siglum}</b><small>{p.compared} locations compared · {p.sharedInnovations} shared innovations</small></div><div className="st-meter"><i style={{width:`${p.similarity}%`}}/><span>{p.similarity}%</span></div></article>)}</section><div className="st-export"><button onClick={()=>exportIt('html')}>HTML report</button><button onClick={()=>exportIt('json')}>JSON dataset</button></div></>}
 {tab==='matrix'&&<section className="st-panel"><h3>Manuscript agreement matrix</h3><div className="st-matrix"><table><thead><tr><th>Witness</th>{witnesses.map((w:any)=><th key={w.id}>{w.siglum}</th>)}</tr></thead><tbody>{witnesses.map((a:any)=><tr key={a.id}><th>{a.siglum}</th>{witnesses.map((b:any)=><td key={b.id} className={(a.id===b.id?'self ':'' )+(Number(matrix[`${a.id}|${b.id}`]||0)>=80?'high':'')}>{a.id===b.id?'100%':`${matrix[`${a.id}|${b.id}`]??'—'}${matrix[`${a.id}|${b.id}`]!==undefined?'%':''}`}</td>)}</tr>)}</tbody></table></div></section>}
 {tab==='tree'&&<section className="st-panel"><h3>Proposed stemma</h3><p className="muted">Solid relationships are curated; dashed relationships are inferred from the highest textual agreement.</p><div className="st-tree">{witnesses.map((w:any,i:number)=><div className="st-node" key={w.id} style={{left:`${8+(i%4)*24}%`,top:`${30+Math.floor(i/4)*150}px`}}><b>{w.siglum}</b><small>{w.date||w.region||'Undated'}</small></div>)}<svg>{edges.map((e:any,i:number)=>{const ai=witnesses.findIndex((w:any)=>w.id===e.parentId),bi=witnesses.findIndex((w:any)=>w.id===e.childId);if(ai<0||bi<0)return null;const ax=12+(ai%4)*24,ay=62+Math.floor(ai/4)*150,bx=12+(bi%4)*24,by=62+Math.floor(bi/4)*150;return <g key={e.id||i}><line x1={`${ax}%`} y1={ay} x2={`${bx}%`} y2={by} className={e.inferred?'inferred':''}/><text x={`${(ax+bx)/2}%`} y={(ay+by)/2-5}>{e.confidence||e.similarity}%</text></g>})}</svg></div></section>}
 {tab==='relationships'&&<div className="st-grid"><section className="st-panel st-form"><h3>Add stemma relationship</h3><label>Ancestor / exemplar<select value={form.parentId} onChange={e=>setForm({...form,parentId:e.target.value})}><option value="">Select witness</option>{witnesses.map((w:any)=><option value={w.id} key={w.id}>{w.siglum} · {w.title}</option>)}</select></label><label>Descendant / copy<select value={form.childId} onChange={e=>setForm({...form,childId:e.target.value})}><option value="">Select witness</option>{witnesses.map((w:any)=><option value={w.id} key={w.id}>{w.siglum} · {w.title}</option>)}</select></label><label>Confidence<input type="range" min="1" max="100" value={form.confidence} onChange={e=>setForm({...form,confidence:Number(e.target.value)})}/><span>{form.confidence}%</span></label><label>Basis<input value={form.basis} onChange={e=>setForm({...form,basis:e.target.value})}/></label><label>Evidence<textarea value={form.evidence} onChange={e=>setForm({...form,evidence:e.target.value})}/></label><label>Notes<textarea value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})}/></label><button onClick={save}>Save relationship</button></section><section className="st-panel"><h3>Curated relationships</h3>{(data.relationships||[]).length===0?<p>No curated relationships yet.</p>:(data.relationships||[]).map((r:any)=><article className="st-rel" key={r.id}><div><b>{witnesses.find((w:any)=>w.id===r.parentId)?.siglum||'?'} → {witnesses.find((w:any)=>w.id===r.childId)?.siglum||'?'}</b><small>{r.confidence}% confidence · {r.basis}</small><p>{r.evidence||r.notes}</p></div><div><button onClick={()=>setForm(r)}>Edit</button><button className="danger" onClick={async()=>{await window.ocrStudio.deleteStemmaRelationship({workspacePath,id:r.id});await load()}}>Delete</button></div></article>)}</section></div>}
 </div>
}
