import { useEffect, useMemo, useState } from "react";
import "./CollaborationHubPage.css";

type Project={projectPath:string;projectName:string};
type Person={id:string;name:string;email:string;role:string;expertise:string;status:string;notes:string};
type Assignment={id:string;title:string;description:string;assigneeId:string;reviewerId:string;module:string;sourceReference:string;priority:string;status:string;dueDate:string;progress:number};
type Comment={id:string;assignmentId:string;authorId:string;body:string;type:string;resolved:boolean;createdAt:string};
const api=window.ocrStudio as any;
const blankPerson={id:"",name:"",email:"",role:"Editor",expertise:"",status:"Active",notes:""};
const blankAssignment={id:"",title:"",description:"",assigneeId:"",reviewerId:"",module:"General",sourceReference:"",priority:"Medium",status:"Backlog",dueDate:"",progress:0};
export default function CollaborationHubPage(){
 const [projects,setProjects]=useState<Project[]>([]),[projectPath,setProjectPath]=useState("");
 const [people,setPeople]=useState<Person[]>([]),[assignments,setAssignments]=useState<Assignment[]>([]),[comments,setComments]=useState<Comment[]>([]),[activity,setActivity]=useState<any[]>([]),[dashboard,setDashboard]=useState<any>({});
 const [tab,setTab]=useState("board"),[pf,setPf]=useState<any>(blankPerson),[af,setAf]=useState<any>(blankAssignment),[comment,setComment]=useState("");
 const load=async(p:string)=>{if(!p)return;const r=await api.getCollaborationProject({projectPath:p});if(r.success){setPeople(r.contributors);setAssignments(r.assignments);setComments(r.comments);setActivity(r.activity);setDashboard(r.dashboard);}};
 useEffect(()=>{api.getCollaborationWorkspace().then((r:any)=>{setProjects(r.projects||[]);const p=r.projects?.[0]?.projectPath||"";setProjectPath(p);if(p)load(p);});},[]);
 const names=useMemo(()=>Object.fromEntries(people.map(p=>[p.id,p.name])),[people]);
 const savePerson=async()=>{if(!projectPath||!pf.name.trim())return;await api.saveCollaborationContributor({projectPath,...pf});setPf(blankPerson);await load(projectPath)};
 const saveAssignment=async()=>{if(!projectPath||!af.title.trim())return;await api.saveCollaborationAssignment({projectPath,...af});setAf(blankAssignment);await load(projectPath)};
 const addComment=async()=>{if(!comment.trim()||!af.id)return;await api.addCollaborationComment({projectPath,assignmentId:af.id,authorId:pf.id,body:comment,type:"Comment"});setComment("");await load(projectPath)};
 const columns=["Backlog","In Progress","In Review","Completed"];
 return <div className="collab-page"><header><div><h2>Collaborative Scholarly Workspace</h2><p>Coordinate contributors, assignments, reviews, comments, and project activity.</p></div><div className="actions"><select value={projectPath} onChange={e=>{setProjectPath(e.target.value);load(e.target.value)}}>{projects.map(p=><option key={p.projectPath} value={p.projectPath}>{p.projectName}</option>)}</select><button onClick={async()=>{const r=await api.exportCollaborationReport({projectPath});if(r.filePath)await api.openCollaborationFile(r.filePath)}}>Export report</button></div></header>
 <section className="metrics">{[["Contributors",dashboard.contributors],["Open work",dashboard.open],["Overdue",dashboard.overdue],["Completed",dashboard.completed],["Comments",dashboard.comments]].map(([a,b])=><article key={String(a)}><b>{b||0}</b><span>{a}</span></article>)}</section>
 <nav className="tabs">{["board","assignments","contributors","activity"].map(t=><button className={tab===t?"active":""} onClick={()=>setTab(t)} key={t}>{t}</button>)}</nav>
 {tab==="board"&&<div className="board">{columns.map(c=><section key={c}><h3>{c}</h3>{assignments.filter(a=>a.status===c).map(a=><button key={a.id} className="card" onClick={()=>{setAf(a);setTab("assignments")}}><b>{a.title}</b><span>{a.module} · {a.priority}</span><small>{names[a.assigneeId]||"Unassigned"} · {a.progress}%</small></button>)}</section>)}</div>}
 {tab==="assignments"&&<div className="split"><section className="list"><h3>Assignments</h3>{assignments.map(a=><button key={a.id} className="record" onClick={()=>setAf(a)}><b>{a.title}</b><span>{a.status} · {names[a.assigneeId]||"Unassigned"}</span></button>)}</section><section className="form"><h3>{af.id?"Edit assignment":"New assignment"}</h3><label>Title<input value={af.title} onChange={e=>setAf({...af,title:e.target.value})}/></label><label>Description<textarea value={af.description} onChange={e=>setAf({...af,description:e.target.value})}/></label><div className="two"><label>Assignee<select value={af.assigneeId} onChange={e=>setAf({...af,assigneeId:e.target.value})}><option value="">Unassigned</option>{people.map(p=><option value={p.id} key={p.id}>{p.name}</option>)}</select></label><label>Reviewer<select value={af.reviewerId} onChange={e=>setAf({...af,reviewerId:e.target.value})}><option value="">None</option>{people.map(p=><option value={p.id} key={p.id}>{p.name}</option>)}</select></label></div><div className="three"><label>Module<input value={af.module} onChange={e=>setAf({...af,module:e.target.value})}/></label><label>Status<select value={af.status} onChange={e=>setAf({...af,status:e.target.value})}>{["Backlog","In Progress","In Review","Completed","Cancelled"].map(x=><option key={x}>{x}</option>)}</select></label><label>Priority<select value={af.priority} onChange={e=>setAf({...af,priority:e.target.value})}>{["Low","Medium","High","Critical"].map(x=><option key={x}>{x}</option>)}</select></label></div><div className="two"><label>Due date<input type="date" value={af.dueDate} onChange={e=>setAf({...af,dueDate:e.target.value})}/></label><label>Progress<input type="number" min="0" max="100" value={af.progress} onChange={e=>setAf({...af,progress:Number(e.target.value)})}/></label></div><label>Source reference<input value={af.sourceReference} onChange={e=>setAf({...af,sourceReference:e.target.value})}/></label><div className="buttons"><button onClick={saveAssignment}>Save</button><button onClick={()=>setAf(blankAssignment)}>Clear</button>{af.id&&<button className="danger" onClick={async()=>{await api.deleteCollaborationAssignment({projectPath,id:af.id});setAf(blankAssignment);await load(projectPath)}}>Delete</button>}</div>{af.id&&<div className="comments"><h4>Discussion</h4>{comments.filter(c=>c.assignmentId===af.id).map(c=><div key={c.id} className={c.resolved?"resolved":""}><p>{c.body}</p><small>{names[c.authorId]||"Contributor"} · {new Date(c.createdAt).toLocaleString()}</small><button onClick={async()=>{await api.resolveCollaborationComment({projectPath,id:c.id,resolved:!c.resolved});await load(projectPath)}}>{c.resolved?"Reopen":"Resolve"}</button></div>)}<textarea placeholder="Add a review comment" value={comment} onChange={e=>setComment(e.target.value)}/><button onClick={addComment}>Add comment</button></div>}</section></div>}
 {tab==="contributors"&&<div className="split"><section className="list"><h3>Contributors</h3>{people.map(p=><button className="record" key={p.id} onClick={()=>setPf(p)}><b>{p.name}</b><span>{p.role} · {p.status}</span></button>)}</section><section className="form"><h3>{pf.id?"Edit contributor":"New contributor"}</h3><label>Name<input value={pf.name} onChange={e=>setPf({...pf,name:e.target.value})}/></label><div className="two"><label>Email<input value={pf.email} onChange={e=>setPf({...pf,email:e.target.value})}/></label><label>Role<select value={pf.role} onChange={e=>setPf({...pf,role:e.target.value})}>{["Project Lead","Editor","Reviewer","Transcriber","Translator","Researcher","Administrator"].map(x=><option key={x}>{x}</option>)}</select></label></div><label>Expertise<input value={pf.expertise} onChange={e=>setPf({...pf,expertise:e.target.value})}/></label><label>Notes<textarea value={pf.notes} onChange={e=>setPf({...pf,notes:e.target.value})}/></label><div className="buttons"><button onClick={savePerson}>Save</button><button onClick={()=>setPf(blankPerson)}>Clear</button>{pf.id&&<button className="danger" onClick={async()=>{await api.deleteCollaborationContributor({projectPath,id:pf.id});setPf(blankPerson);await load(projectPath)}}>Delete</button>}</div></section></div>}
 {tab==="activity"&&<section className="activity"><h3>Project activity</h3>{activity.map(x=><article key={x.id}><b>{x.action}</b><p>{x.details}</p><small>{x.actor} · {new Date(x.createdAt).toLocaleString()}</small></article>)}</section>}
 </div>;
}
