import {useEffect,useMemo,useState} from "react";
import {useNavigate} from "react-router-dom";
import {getProjects} from "../../services/projectStorage";
import "./EditionManagerPage.css";
type E=any;
const empty={title:"",subtitle:"",description:"",language:"Sanskrit",tradition:"",editors:"",institution:"",version:"0.1",license:"All rights reserved",keywords:""};
export default function EditionManagerPage(){
 const navigate=useNavigate();
 const [workspaces,setWorkspaces]=useState<string[]>([]),[workspacePath,setWorkspacePath]=useState(""),[editions,setEditions]=useState<E[]>([]),[selected,setSelected]=useState<E|null>(null),[form,setForm]=useState<any>(empty),[showForm,setShowForm]=useState(false),[message,setMessage]=useState("Select a workspace."),[busy,setBusy]=useState(false);
 useEffect(()=>{void getProjects().then(ps=>{const w=[...new Set(ps.map(p=>p.workspacePath).filter(Boolean))] as string[];setWorkspaces(w);if(w[0])setWorkspacePath(w[0]);})},[]);
 const load=async()=>{if(!workspacePath)return;setBusy(true);const r=await window.ocrStudio.listEditions({workspacePath});setEditions(r.editions||[]);setSelected((r.editions||[])[0]||null);setMessage(r.message);setBusy(false)};
 useEffect(()=>{void load()},[workspacePath]);
 const totals=useMemo(()=>editions.reduce((a,e)=>({verses:a.verses+(e.stats?.verses||0),variants:a.variants+(e.stats?.variants||0),decisions:a.decisions+(e.stats?.decisions||0)}),{verses:0,variants:0,decisions:0}),[editions]);
 const create=async()=>{if(!form.title.trim())return setMessage("Edition title is required.");setBusy(true);const r=await window.ocrStudio.createEdition({workspacePath,...form,languages:[form.language],editors:form.editors.split(",").map((x:string)=>x.trim()).filter(Boolean),keywords:form.keywords.split(",").map((x:string)=>x.trim()).filter(Boolean)});setMessage(r.message);setBusy(false);if(r.success){setShowForm(false);setForm(empty);await load()}};
 const updateStatus=async(status:string)=>{if(!selected)return;const r=await window.ocrStudio.updateEdition({workspacePath,id:selected.id,status});setMessage(r.message);await load()};
 const del=async()=>{if(!selected||!confirm(`Delete ${selected.title}?`))return;const r=await window.ocrStudio.deleteEdition({workspacePath,id:selected.id});setMessage(r.message);await load()};
 return <div className="ed-page"><header className="ed-hero"><div><span>Phase 10.0A · Milestone 6</span><h2>Scholarly Edition Manager</h2><p>Organize critical editions, editorial metadata, versions and publication readiness in one workspace.</p></div><button onClick={()=>setShowForm(true)} disabled={!workspacePath}>＋ New edition</button></header>
 <section className="ed-toolbar"><label>Workspace<select value={workspacePath} onChange={e=>setWorkspacePath(e.target.value)}>{workspaces.map(w=><option key={w}>{w}</option>)}</select></label><span>{busy?"Working…":message}</span></section>
 <section className="ed-summary">{[["Editions",editions.length],["Verses",totals.verses],["Variants",totals.variants],["Editorial decisions",totals.decisions]].map(([l,v])=><article key={String(l)}><strong>{Number(v).toLocaleString()}</strong><span>{l}</span></article>)}</section>
 <div className="ed-layout"><section className="ed-list"><header><h3>Your editions</h3><span>{editions.length} total</span></header>{!editions.length?<div className="ed-empty"><b>No scholarly editions yet</b><p>Create an edition to begin assembling critical text, apparatus, commentary and publication metadata.</p><button onClick={()=>setShowForm(true)}>Create first edition</button></div>:editions.map(e=><button className={selected?.id===e.id?"active":""} onClick={()=>setSelected(e)} key={e.id}><div><h4>{e.title}</h4><p>{e.subtitle||e.description||"Scholarly edition"}</p></div><span className={`status ${String(e.status).toLowerCase().replaceAll(" ","-")}`}>{e.status}</span><footer><small>v{e.version}</small><small>{(e.languages||[]).join(", ")}</small><small>{new Date(e.updatedAt).toLocaleDateString()}</small></footer></button>)}</section>
 <section className="ed-detail">{selected?<><header><div><span>Edition workspace</span><h3>{selected.title}</h3><p>{selected.subtitle||selected.description}</p></div><div className="ed-open-actions"><button onClick={()=>navigate(`/editions/editor?workspace=${encodeURIComponent(workspacePath)}&edition=${selected.id}`)}>Open critical editor</button><button onClick={()=>navigate(`/editions/validator?workspace=${encodeURIComponent(workspacePath)}&edition=${selected.id}`)}>Publication validator</button><button onClick={()=>navigate(`/editions/publication?workspace=${encodeURIComponent(workspacePath)}&edition=${selected.id}`)}>Publication center</button><button onClick={()=>window.ocrStudio.openEditionFolder({workspacePath,id:selected.id})}>Open folder</button></div></header>
 <div className="ed-meta">{[["Version",selected.version],["Status",selected.status],["Language",(selected.languages||[]).join(", ")||"—"],["Tradition",selected.tradition||"—"],["Editors",(selected.editors||[]).join(", ")||"—"],["Institution",selected.institution||"—"],["License",selected.license||"—"],["DOI / ISBN",selected.doi||selected.isbn||"Not assigned"]].map(([l,v])=><article key={String(l)}><span>{l}</span><strong>{v}</strong></article>)}</div>
 <h4 className="section-title">Editorial progress</h4><div className="ed-progress">{Object.entries(selected.progress||{}).map(([k,v]:any)=><article key={k}><header><span>{k[0].toUpperCase()+k.slice(1)}</span><b>{v}%</b></header><i><em style={{width:`${v}%`}}/></i></article>)}</div>
 <h4 className="section-title">Edition analytics</h4><div className="ed-stats">{Object.entries(selected.stats||{}).map(([k,v]:any)=><article key={k}><strong>{Number(v).toLocaleString()}</strong><span>{k}</span></article>)}</div>
 <h4 className="section-title">Workflow status</h4><div className="ed-workflow">{["Draft","Internal Review","Peer Review","Approved","Published","Archived"].map(s=><button className={selected.status===s?"active":""} onClick={()=>updateStatus(s)} key={s}>{s}</button>)}</div>
 <h4 className="section-title">Version history</h4><div className="ed-revisions">{(selected.revisions||[]).slice().reverse().map((r:E)=><article key={r.id}><b>v{r.version}</b><div><strong>{r.label}</strong><span>{new Date(r.createdAt).toLocaleString()}</span></div></article>)}</div>
 <footer className="ed-actions"><button onClick={()=>window.ocrStudio.duplicateEdition({workspacePath,id:selected.id}).then(load)}>Duplicate edition</button><button className="danger" onClick={del}>Delete edition</button></footer></>:<div className="ed-empty"><b>Select an edition</b><p>Edition details and publication progress appear here.</p></div>}</section></div>
 {showForm&&<div className="ed-modal"><form onSubmit={e=>{e.preventDefault();void create()}}><header><div><span>New scholarly edition</span><h3>Create Edition</h3></div><button type="button" onClick={()=>setShowForm(false)}>×</button></header><div className="ed-form-grid"><label>Title<input value={form.title} onChange={e=>setForm({...form,title:e.target.value})} autoFocus/></label><label>Subtitle<input value={form.subtitle} onChange={e=>setForm({...form,subtitle:e.target.value})}/></label><label>Primary language<select value={form.language} onChange={e=>setForm({...form,language:e.target.value})}><option>Sanskrit</option><option>Telugu</option><option>Hindi</option><option>English</option><option>Multilingual</option></select></label><label>Tradition / recension<input value={form.tradition} onChange={e=>setForm({...form,tradition:e.target.value})}/></label><label>Editors<input placeholder="Names separated by commas" value={form.editors} onChange={e=>setForm({...form,editors:e.target.value})}/></label><label>Institution<input value={form.institution} onChange={e=>setForm({...form,institution:e.target.value})}/></label><label>Version<input value={form.version} onChange={e=>setForm({...form,version:e.target.value})}/></label><label>License<input value={form.license} onChange={e=>setForm({...form,license:e.target.value})}/></label><label className="wide">Keywords<input placeholder="dharma, critical edition, manuscript" value={form.keywords} onChange={e=>setForm({...form,keywords:e.target.value})}/></label><label className="wide">Description<textarea rows={4} value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></label></div><footer><button type="button" onClick={()=>setShowForm(false)}>Cancel</button><button className="primary">Create edition</button></footer></form></div>}</div>
}
