import {useEffect,useMemo,useState} from 'react';
import {useNavigate} from 'react-router-dom';
import {getProjects} from '../../services/projectStorage';
import './ScholarlyLibraryPage.css';
export default function ScholarlyLibraryPage(){
 const nav=useNavigate(),[workspaces,setWorkspaces]=useState<string[]>([]),[workspacePath,setWorkspacePath]=useState(''),[data,setData]=useState<any>(null),[query,setQuery]=useState(''),[collectionId,setCollectionId]=useState(''),[results,setResults]=useState<any[]>([]),[message,setMessage]=useState('Select a workspace.'),[form,setForm]=useState({name:'',description:'',curator:'',keywords:''}),[show,setShow]=useState(false);
 useEffect(()=>{void getProjects().then(ps=>{const w=[...new Set(ps.map(p=>p.workspacePath).filter(Boolean))] as string[];setWorkspaces(w);if(w[0])setWorkspacePath(w[0])})},[]);
 const load=async()=>{if(!workspacePath)return;const r=await window.ocrStudio.getScholarlyLibrary({workspacePath});setData(r);setMessage(r.message)};
 useEffect(()=>{void load()},[workspacePath]);
 const search=async()=>{const r=await window.ocrStudio.searchScholarlyLibrary({workspacePath,query,collectionId:collectionId||undefined});setResults(r.results||[]);setMessage(r.message)};
 const create=async()=>{const r=await window.ocrStudio.createLibraryCollection({workspacePath,...form,keywords:form.keywords.split(',').map(x=>x.trim()).filter(Boolean)});setMessage(r.message);if(r.success){setShow(false);setForm({name:'',description:'',curator:'',keywords:''});await load()}};
 const toggle=async(c:any,eid:string)=>{const ids=new Set(c.editionIds||[]);ids.has(eid)?ids.delete(eid):ids.add(eid);await window.ocrStudio.updateLibraryCollection({workspacePath,id:c.id,editionIds:[...ids]});await load()};
 const stats=data?.stats||{};const selected=useMemo(()=>data?.collections?.find((x:any)=>x.id===collectionId),[data,collectionId]);
 return <div className="sl-page"><header className="sl-hero"><div><span>Phase 10B · Milestone 1</span><h2>Digital Scholarly Library</h2><p>Curate collections, discover editions, and search critical text across the complete workspace.</p></div><button onClick={()=>setShow(true)} disabled={!workspacePath}>＋ New collection</button></header>
 <section className="sl-toolbar"><label>Workspace<select value={workspacePath} onChange={e=>setWorkspacePath(e.target.value)}>{workspaces.map(w=><option key={w}>{w}</option>)}</select></label><span>{message}</span></section>
 <section className="sl-stats">{[['Editions',stats.editions],['Collections',stats.collections],['Verses',stats.verses],['Published',stats.published],['Languages',stats.languages],['Traditions',stats.traditions]].map(([l,v])=><article key={String(l)}><b>{Number(v||0).toLocaleString()}</b><span>{l}</span></article>)}</section>
 <section className="sl-search"><input value={query} onChange={e=>setQuery(e.target.value)} onKeyDown={e=>e.key==='Enter'&&void search()} placeholder="Search title, editor, tradition, keyword, or verse text…"/><select value={collectionId} onChange={e=>setCollectionId(e.target.value)}><option value="">All editions</option>{data?.collections?.map((c:any)=><option value={c.id} key={c.id}>{c.name}</option>)}</select><button onClick={search}>Search library</button></section>
 <div className="sl-layout"><section className="sl-collections"><header><h3>Curated collections</h3><span>{data?.collections?.length||0}</span></header>{!data?.collections?.length?<p className="empty">Create a collection to group related editions.</p>:data.collections.map((c:any)=><article className={collectionId===c.id?'active':''} key={c.id} onClick={()=>setCollectionId(c.id)}><div><h4>{c.name}</h4><p>{c.description||'Scholarly collection'}</p><small>{(c.editionIds||[]).length} editions · {c.curator||'No curator'}</small></div><button onClick={async e=>{e.stopPropagation();if(confirm(`Delete ${c.name}?`)){await window.ocrStudio.deleteLibraryCollection({workspacePath,id:c.id});setCollectionId('');await load()}}}>Delete</button></article>)}</section>
 <section className="sl-main">{selected?<><header><div><span>Collection</span><h3>{selected.name}</h3><p>{selected.description}</p></div></header><div className="sl-editions">{data.editions.map((e:any)=><article key={e.id}><div><h4>{e.title}</h4><p>{e.subtitle||e.description||'Scholarly edition'}</p><small>{e.status} · v{e.version} · {(e.languages||[]).join(', ')}</small></div><label><input type="checkbox" checked={(selected.editionIds||[]).includes(e.id)} onChange={()=>toggle(selected,e.id)}/> In collection</label><button onClick={()=>nav(`/editions/editor?workspace=${encodeURIComponent(workspacePath)}&edition=${e.id}`)}>Open editor</button></article>)}</div></>:<><header><div><span>Library catalog</span><h3>{query?'Search results':'All scholarly editions'}</h3></div></header><div className="sl-results">{(query||results.length?results:data?.editions||[]).map((r:any,i:number)=>r.type==='verse'?<article key={`${r.verseId}-${i}`}><span className="kind">VERSE</span><div><h4>{r.editionTitle} · {r.bookTitle} · {r.chapterTitle} · Verse {r.verseNumber}</h4><p>{r.snippet}</p></div><button onClick={()=>nav(`/editions/editor?workspace=${encodeURIComponent(workspacePath)}&edition=${r.editionId}`)}>Open</button></article>:<article key={r.id||`${r.editionId}-${i}`}><span className="kind">EDITION</span><div><h4>{r.title}</h4><p>{r.subtitle||r.description||'Scholarly edition'}</p><small>{r.status} · v{r.version} · {(r.languages||[]).join(', ')}</small></div><button onClick={()=>nav(`/editions/editor?workspace=${encodeURIComponent(workspacePath)}&edition=${r.id||r.editionId}`)}>Open</button></article>)}</div></>}</section></div>
 {show&&<div className="sl-modal"><form onSubmit={e=>{e.preventDefault();void create()}}><header><h3>Create collection</h3><button type="button" onClick={()=>setShow(false)}>×</button></header><label>Name<input autoFocus value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></label><label>Description<textarea rows={4} value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></label><label>Curator<input value={form.curator} onChange={e=>setForm({...form,curator:e.target.value})}/></label><label>Keywords<input placeholder="epic, southern recension" value={form.keywords} onChange={e=>setForm({...form,keywords:e.target.value})}/></label><footer><button type="button" onClick={()=>setShow(false)}>Cancel</button><button className="primary">Create</button></footer></form></div>}</div>}
