import {useEffect,useMemo,useState} from "react";
import {useLocation,useNavigate} from "react-router-dom";
import "./CriticalTextEditorPage.css";
import EditorialDecisionEnginePanel from "./EditorialDecisionEnginePanel";
import EditorialAiAssistantPanel from "./EditorialAiAssistantPanel";
type Any=any;
const blankVerse={number:"",title:"",criticalText:"",languages:{Sanskrit:"",Telugu:"",English:"",Hindi:""},status:"Draft"};
export default function CriticalTextEditorPage(){
 const location=useLocation(),navigate=useNavigate();const params=new URLSearchParams(location.search);const workspacePath=params.get("workspace")||"",editionId=params.get("edition")||"";
 const [decisionRefresh,setDecisionRefresh]=useState(0);
 const [data,setData]=useState<Any|null>(null),[bookId,setBookId]=useState(""),[chapterId,setChapterId]=useState(""),[verseId,setVerseId]=useState(""),[verse,setVerse]=useState<Any>(blankVerse),[tab,setTab]=useState("apparatus"),[message,setMessage]=useState("Loading edition…"),[entry,setEntry]=useState<Any>({label:"",content:"",reading:"",witnesses:"",reason:"",confidence:80,editor:""});
 const load=async()=>{if(!workspacePath||!editionId){setMessage("Missing workspace or edition.");return}const r=await window.ocrStudio.getCriticalTextWorkspace({workspacePath,editionId});setMessage(r.message);if(r.success)setData(r.workspace)};
 useEffect(()=>{void load()},[workspacePath,editionId]);
 const books=data?.structure?.books||[];const book=books.find((x:Any)=>x.id===bookId)||books[0];const chapters=book?.chapters||[];const chapter=chapters.find((x:Any)=>x.id===chapterId)||chapters[0];const verses=chapter?.verses||[];const selectedVerse=verses.find((x:Any)=>x.id===verseId)||verses[0];
 useEffect(()=>{if(book&&!bookId)setBookId(book.id)},[data]);useEffect(()=>{if(chapter&&chapter.bookId!==chapterId)setChapterId(chapter.id)},[bookId,data]);useEffect(()=>{if(selectedVerse){setVerseId(selectedVerse.id);setVerse({...blankVerse,...selectedVerse,languages:{...blankVerse.languages,...selectedVerse.languages}})}else{setVerseId("");setVerse({...blankVerse,number:String(verses.length+1)})}},[chapterId,data]);
 const currentEntries=useMemo(()=>{if(!data||!verseId)return[];return (data[tab]?.entries||[]).filter((x:Any)=>x.verseId===verseId)},[data,tab,verseId]);
 const act=async(fn:()=>Promise<Any>)=>{const r=await fn();setMessage(r.message);if(r.success){setData(r.workspace);return r}return r};
 const addBook=async()=>{const title=prompt("Book title");if(title)await act(()=>window.ocrStudio.addEditionBook({workspacePath,editionId,title}))};
 const addChapter=async()=>{if(!book)return setMessage("Create a book first.");const title=prompt("Chapter title");if(title)await act(()=>window.ocrStudio.addEditionChapter({workspacePath,editionId,bookId:book.id,title}))};
 const newVerse=()=>{setVerseId("");setVerse({...blankVerse,number:String(verses.length+1)})};
 const saveVerse=async()=>{if(!chapter)return setMessage("Create a chapter first.");const r=await act(()=>window.ocrStudio.saveEditionVerse({workspacePath,editionId,bookId:book.id,chapterId:chapter.id,verseId,...verse}));if(r?.workspace){const vs=r.workspace.structure.books.find((b:Any)=>b.id===book.id)?.chapters.find((c:Any)=>c.id===chapter.id)?.verses||[];const found=vs.find((v:Any)=>v.number===verse.number);if(found)setVerseId(found.id)}};
 const delVerse=async()=>{if(!selectedVerse||!confirm("Delete this verse and its linked notes?"))return;await act(()=>window.ocrStudio.deleteEditionVerse({workspacePath,editionId,bookId:book.id,chapterId:chapter.id,verseId:selectedVerse.id}))};
 const saveEntry=async()=>{if(!verseId)return setMessage("Save the verse first.");const payload={workspacePath,editionId,verseId,label:entry.label,content:entry.content,reading:entry.reading,witnesses:String(entry.witnesses||"").split(",").map(x=>x.trim()).filter(Boolean),reason:entry.reason,confidence:Number(entry.confidence),editor:entry.editor};const map:Any={apparatus:window.ocrStudio.saveEditionApparatus,commentary:window.ocrStudio.saveEditionCommentary,footnotes:window.ocrStudio.saveEditionFootnote,decisions:window.ocrStudio.saveEditorialDecision};await act(()=>map[tab](payload));if(tab==="decisions")setDecisionRefresh(x=>x+1);setEntry({label:"",content:"",reading:"",witnesses:"",reason:"",confidence:80,editor:""})};
 return <div className="cte-page"><header className="cte-hero"><div><button onClick={()=>navigate("/editions")}>← Editions</button><span>Phase 10.0A · Milestone 4</span><h2>{data?.edition?.title||"Critical Text Editor"}</h2><p>Compose the base text, parallel translations, apparatus, commentary, footnotes and editorial decisions.</p></div><div className="cte-message">{message}</div></header>
 <div className="cte-shell"><aside className="cte-tree"><header><h3>Edition structure</h3><button onClick={addBook}>＋ Book</button></header>{books.map((b:Any)=><section key={b.id}><button className={b.id===book?.id?"active":""} onClick={()=>{setBookId(b.id);setChapterId("")}}><b>{b.number}. {b.title}</b><small>{(b.chapters||[]).length} chapters</small></button>{b.id===book?.id&&<div className="chapters">{(b.chapters||[]).map((c:Any)=><button className={c.id===chapter?.id?"active":""} key={c.id} onClick={()=>setChapterId(c.id)}>{c.number}. {c.title}</button>)}<button className="add" onClick={addChapter}>＋ Add chapter</button></div>}</section>)}{!books.length&&<div className="empty">Create the first book to begin.</div>}</aside>
 <aside className="cte-verses"><header><div><h3>{chapter?.title||"Verses"}</h3><small>{verses.length} entries</small></div><button onClick={newVerse} disabled={!chapter}>＋ Verse</button></header>{verses.map((v:Any)=><button key={v.id} className={v.id===verseId?"active":""} onClick={()=>{setVerseId(v.id);setVerse({...blankVerse,...v,languages:{...blankVerse.languages,...v.languages}})}}><strong>{v.number}</strong><div><b>{v.title||"Untitled verse"}</b><span>{String(v.criticalText||"").slice(0,80)||"No critical text"}</span></div><em>{v.status}</em></button>)}{!verses.length&&<div className="empty">No verses in this chapter.</div>}</aside>
 <main className="cte-editor"><header><div><span>{verseId?"Editing verse":"New verse"}</span><h3>{chapter?.title||"Select a chapter"}</h3></div><div><button className="danger" onClick={delVerse} disabled={!verseId}>Delete</button><button className="primary" onClick={saveVerse} disabled={!chapter}>Save verse</button></div></header><div className="cte-fields"><label>Verse number<input value={verse.number} onChange={e=>setVerse({...verse,number:e.target.value})}/></label><label>Title<input value={verse.title} onChange={e=>setVerse({...verse,title:e.target.value})}/></label><label>Status<select value={verse.status} onChange={e=>setVerse({...verse,status:e.target.value})}><option>Draft</option><option>Reviewed</option><option>Approved</option></select></label></div><label className="critical">Critical text<textarea rows={7} value={verse.criticalText} onChange={e=>setVerse({...verse,criticalText:e.target.value})} placeholder="Enter the established critical reading…"/></label><div className="parallel">{Object.entries(verse.languages||{}).map(([lang,text]:Any)=><label key={lang}><span>{lang}</span><textarea rows={5} value={text} onChange={e=>setVerse({...verse,languages:{...verse.languages,[lang]:e.target.value}})} placeholder={`${lang} parallel text`}/></label>)}</div>
 <section className="cte-notes"><nav>{[["apparatus","Apparatus"],["commentary","Commentary"],["footnotes","Footnotes"],["decisions","Editorial decisions"]].map(([k,l])=><button className={tab===k?"active":""} onClick={()=>setTab(k)} key={k}>{l}<small>{(data?.[k]?.entries||[]).filter((x:Any)=>x.verseId===verseId).length}</small></button>)}</nav><div className="note-grid"><div className="entry-form"><label>Label<input value={entry.label} onChange={e=>setEntry({...entry,label:e.target.value})} placeholder={tab==="apparatus"?"M1, Southern recension…":"Short title"}/></label>{tab==="apparatus"&&<><label>Variant reading<textarea rows={3} value={entry.reading} onChange={e=>setEntry({...entry,reading:e.target.value})}/></label><label>Witnesses<input value={entry.witnesses} onChange={e=>setEntry({...entry,witnesses:e.target.value})} placeholder="M1, M2, T1"/></label></>}{tab==="decisions"&&<><label>Editorial reason<textarea rows={3} value={entry.reason} onChange={e=>setEntry({...entry,reason:e.target.value})}/></label><div className="decision-row"><label>Confidence<input type="number" min="0" max="100" value={entry.confidence} onChange={e=>setEntry({...entry,confidence:e.target.value})}/></label><label>Editor<input value={entry.editor} onChange={e=>setEntry({...entry,editor:e.target.value})}/></label></div></>}<label>Content<textarea rows={4} value={entry.content} onChange={e=>setEntry({...entry,content:e.target.value})}/></label><button className="primary" onClick={saveEntry} disabled={!verseId}>Add {tab.replace("footnotes","footnote").replace("decisions","decision")}</button></div><div className="entry-list">{currentEntries.map((x:Any)=><article key={x.id}><header><b>{x.label||tab}</b><span>{new Date(x.updatedAt||x.createdAt).toLocaleString()}</span></header>{x.reading&&<blockquote>{x.reading}</blockquote>}<p>{x.content||x.reason}</p>{x.witnesses?.length>0&&<footer>{x.witnesses.map((w:string)=><em key={w}>{w}</em>)}</footer>}{x.confidence>0&&<strong>{x.confidence}% confidence</strong>}</article>)}{!currentEntries.length&&<div className="empty">No {tab} entries for this verse.</div>}</div></div></section>{tab==="decisions"&&<><EditorialDecisionEnginePanel workspacePath={workspacePath} editionId={editionId} verseId={verseId} refreshToken={decisionRefresh}/><EditorialAiAssistantPanel workspacePath={workspacePath} editionId={editionId} verseId={verseId}/></>}</main></div></div>
}
