import {useEffect,useMemo,useState} from "react";
import "./EditorialDecisionEnginePanel.css";

type Any=any;
export default function EditorialDecisionEnginePanel({workspacePath,editionId,verseId,refreshToken=0}:{workspacePath:string;editionId:string;verseId:string;refreshToken?:number}){
 const [data,setData]=useState<Any|null>(null),[selected,setSelected]=useState<string[]>([]),[message,setMessage]=useState(""),[review,setReview]=useState({status:"Under Review",reviewedBy:"",reviewNote:""}),[evidence,setEvidence]=useState({type:"Manuscript passage",title:"",source:"",locator:"",excerpt:"",note:"",strength:80}),[compare,setCompare]=useState<Any[]>([]);
 const load=async()=>{if(!verseId){setData(null);return}const r=await window.ocrStudio.getEditorialDecisionWorkspace({workspacePath,editionId,verseId});setMessage(r.message);if(r.success)setData(r.workspace)};
 useEffect(()=>{void load()},[workspacePath,editionId,verseId,refreshToken]);
 const decisions=data?.decisions||[];const active=useMemo(()=>decisions.find((x:Any)=>selected[0]===x.id)||decisions[0],[decisions,selected]);
 useEffect(()=>{if(active&&!selected.length)setSelected([active.id])},[data]);
 const run=async(fn:()=>Promise<Any>)=>{const r=await fn();setMessage(r.message);if(r.success&&r.workspace)setData(r.workspace);return r};
 const transition=async(status:string)=>{if(!active)return;await run(()=>window.ocrStudio.transitionEditorialDecision({workspacePath,editionId,verseId,decisionId:active.id,status,reviewedBy:review.reviewedBy,reviewNote:review.reviewNote}))};
 const addEvidence=async()=>{if(!active||!evidence.title.trim())return setMessage("Evidence title is required.");await run(()=>window.ocrStudio.addEditorialDecisionEvidence({workspacePath,editionId,verseId,decisionId:active.id,actor:review.reviewedBy,...evidence}));setEvidence({...evidence,title:"",source:"",locator:"",excerpt:"",note:""})};
 const doCompare=async()=>{if(selected.length<2)return setMessage("Select at least two decisions to compare.");const r=await window.ocrStudio.compareEditorialDecisions({workspacePath,editionId,decisionIds:selected});setMessage(r.message);if(r.success)setCompare(r.decisions||[])};
 const evidenceFor=(id:string)=>(data?.evidence||[]).filter((x:Any)=>x.decisionId===id);const revisionsFor=(id:string)=>(data?.revisions||[]).filter((x:Any)=>x.decisionId===id);
 if(!verseId)return <div className="ede-empty">Save or select a verse to manage editorial decisions.</div>;
 return <section className="ede"><header className="ede-head"><div><span>Phase 10.0A · Milestone 3</span><h3>Editorial Decision Engine</h3><p>Review, compare, support and restore evidence-backed editorial choices.</p></div><div className="ede-summary">{Object.entries(data?.summary||{}).map(([k,v]:Any)=><div key={k}><b>{v}</b><span>{k.replace(/([A-Z])/g," $1")}</span></div>)}</div></header>{message&&<div className="ede-message">{message}</div>}
 <div className="ede-layout"><aside className="ede-list"><header><b>Decisions</b><button onClick={doCompare} disabled={selected.length<2}>Compare {selected.length>1?`(${selected.length})`:""}</button></header>{decisions.map((d:Any)=><article key={d.id} className={active?.id===d.id?"active":""}><label><input type="checkbox" checked={selected.includes(d.id)} onChange={e=>setSelected(s=>e.target.checked?[...new Set([...s,d.id])]:s.filter(x=>x!==d.id))}/><span onClick={()=>setSelected([d.id])}><b>{d.label||"Editorial decision"}</b><small>{d.editor||"Unassigned editor"}</small></span></label><em className={`status ${String(d.status||"Proposed").toLowerCase().replaceAll(" ","-")}`}>{d.status||"Proposed"}</em><p>{d.reason||d.content||"No rationale recorded."}</p><footer><span>{Number(d.confidence||0)}% confidence</span><span>{evidenceFor(d.id).length} evidence</span><span>{revisionsFor(d.id).length} revisions</span></footer></article>)}{!decisions.length&&<div className="ede-empty">Create an editorial decision in the form above first.</div>}</aside>
 <main className="ede-detail">{active?<><section className="ede-card"><header><div><span>Current decision</span><h4>{active.label||"Editorial decision"}</h4></div><em className={`status ${String(active.status||"Proposed").toLowerCase().replaceAll(" ","-")}`}>{active.status||"Proposed"}</em></header>{active.reading&&<blockquote>{active.reading}</blockquote>}<p>{active.reason||active.content}</p><div className="ede-meta"><span>Editor <b>{active.editor||"—"}</b></span><span>Confidence <b>{active.confidence||0}%</b></span><span>Witnesses <b>{active.witnesses?.join(", ")||"—"}</b></span></div></section>
 <section className="ede-card"><h4>Review workflow</h4><div className="ede-grid"><label>Reviewer<input value={review.reviewedBy} onChange={e=>setReview({...review,reviewedBy:e.target.value})} placeholder="Reviewer name"/></label><label>Review note<textarea rows={3} value={review.reviewNote} onChange={e=>setReview({...review,reviewNote:e.target.value})}/></label></div><div className="ede-actions"><button onClick={()=>transition("Under Review")}>Send to review</button><button className="accept" onClick={()=>transition("Accepted")}>Accept</button><button className="reject" onClick={()=>transition("Rejected")}>Reject</button><button onClick={()=>transition("Superseded")}>Supersede</button><button onClick={()=>transition("Proposed")}>Return to proposed</button></div></section>
 <section className="ede-card"><h4>Attach supporting evidence</h4><div className="ede-grid three"><label>Evidence type<select value={evidence.type} onChange={e=>setEvidence({...evidence,type:e.target.value})}><option>Manuscript passage</option><option>Parallel reading</option><option>Commentary</option><option>Research note</option><option>Citation</option><option>Image witness</option></select></label><label>Title<input value={evidence.title} onChange={e=>setEvidence({...evidence,title:e.target.value})}/></label><label>Strength<input type="number" min="0" max="100" value={evidence.strength} onChange={e=>setEvidence({...evidence,strength:Number(e.target.value)})}/></label><label>Source<input value={evidence.source} onChange={e=>setEvidence({...evidence,source:e.target.value})}/></label><label>Locator<input value={evidence.locator} onChange={e=>setEvidence({...evidence,locator:e.target.value})} placeholder="Page, folio, verse…"/></label><label className="wide">Excerpt<textarea rows={3} value={evidence.excerpt} onChange={e=>setEvidence({...evidence,excerpt:e.target.value})}/></label></div><button className="primary" onClick={addEvidence}>Attach evidence</button><div className="ede-evidence">{evidenceFor(active.id).map((ev:Any)=><article key={ev.id}><header><b>{ev.title}</b><em>{ev.strength}% strength</em></header><small>{ev.type} · {ev.source||"Unspecified source"} {ev.locator&&`· ${ev.locator}`}</small>{ev.excerpt&&<blockquote>{ev.excerpt}</blockquote>}<button onClick={()=>run(()=>window.ocrStudio.deleteEditorialDecisionEvidence({workspacePath,editionId,verseId,evidenceId:ev.id,actor:review.reviewedBy}))}>Remove</button></article>)}{!evidenceFor(active.id).length&&<div className="ede-empty">No supporting evidence attached.</div>}</div></section>
 <section className="ede-card"><h4>Revision history</h4><div className="ede-history">{revisionsFor(active.id).map((rev:Any)=><article key={rev.id}><div><b>{rev.action}</b><span>{rev.actor} · {new Date(rev.createdAt).toLocaleString()}</span>{rev.note&&<p>{rev.note}</p>}</div><button onClick={()=>confirm("Restore this earlier decision state?")&&run(()=>window.ocrStudio.restoreEditorialDecisionRevision({workspacePath,editionId,verseId,revisionId:rev.id,actor:review.reviewedBy}))}>Restore</button></article>)}{!revisionsFor(active.id).length&&<div className="ede-empty">Workflow changes will appear here.</div>}</div></section></>:<div className="ede-empty">Select a decision.</div>}</main></div>
 {compare.length>0&&<div className="ede-compare"><header><h3>Decision comparison</h3><button onClick={()=>setCompare([])}>Close</button></header><div>{compare.map((d:Any)=><article key={d.id}><h4>{d.label||"Decision"}</h4><em className={`status ${String(d.status||"Proposed").toLowerCase().replaceAll(" ","-")}`}>{d.status||"Proposed"}</em><blockquote>{d.reading||d.content||"No selected reading"}</blockquote><p>{d.reason}</p><dl><div><dt>Editor</dt><dd>{d.editor||"—"}</dd></div><div><dt>Confidence</dt><dd>{d.confidence||0}%</dd></div><div><dt>Evidence</dt><dd>{d.evidence?.length||0}</dd></div><div><dt>Revisions</dt><dd>{d.revisions?.length||0}</dd></div></dl></article>)}</div></div>}</section>
}
