import {useEffect,useState} from "react";
import "./EditorialAiAssistantPanel.css";
type Any=any;
export default function EditorialAiAssistantPanel({workspacePath,editionId,verseId}:{workspacePath:string;editionId:string;verseId:string}){
 const [items,setItems]=useState<Any[]>([]),[message,setMessage]=useState(""),[busy,setBusy]=useState(false),[useOllama,setUseOllama]=useState(true),[reviewer,setReviewer]=useState("");
 const load=async()=>{if(!verseId)return setItems([]);const r=await window.ocrStudio.listEditorialAiSuggestions({workspacePath,editionId,verseId});setMessage(r.message);if(r.success)setItems(r.suggestions||[])};
 useEffect(()=>{void load()},[workspacePath,editionId,verseId]);
 const generate=async()=>{setBusy(true);const r=await window.ocrStudio.generateEditorialAiSuggestions({workspacePath,editionId,verseId,useOllama});setBusy(false);setMessage(r.message);if(r.success)setItems(r.suggestions||[])};
 const update=async(id:string,status:string)=>{const r=await window.ocrStudio.updateEditorialAiSuggestion({workspacePath,editionId,verseId,suggestionId:id,status,reviewedBy:reviewer});setMessage(r.message);if(r.success)setItems(r.suggestions||[])};
 if(!verseId)return null;
 return <section className="eai"><header><div><span>Phase 10.0A · Milestone 4</span><h3>AI Editorial Assistant</h3><p>Evidence-aware proposals for variant selection, transcription issues, missing material and editorial gaps.</p></div><div className="eai-controls"><label><input type="checkbox" checked={useOllama} onChange={e=>setUseOllama(e.target.checked)}/> Use local Ollama</label><input value={reviewer} onChange={e=>setReviewer(e.target.value)} placeholder="Reviewer name"/><button onClick={generate} disabled={busy}>{busy?"Analyzing…":"Analyze verse"}</button></div></header>{message&&<div className="eai-message">{message}</div>}<div className="eai-grid">{items.map(x=><article key={x.id} className={`sev-${String(x.severity||"Medium").toLowerCase()}`}><header><div><small>{x.type}</small><h4>{x.title}</h4></div><em>{x.confidence}%</em></header><p>{x.suggestion}</p><div className="eai-meta"><span>{x.severity} priority</span><span>{x.generatedBy}</span><span>{x.status}</span></div>{x.evidenceRefs?.length>0&&<footer>Evidence: {x.evidenceRefs.join(", ")}</footer>}<nav><button onClick={()=>update(x.id,"Accepted")}>Accept proposal</button><button onClick={()=>update(x.id,"Applied")}>Mark applied</button><button onClick={()=>update(x.id,"Rejected")}>Reject</button></nav></article>)}{!items.length&&!busy&&<div className="eai-empty">Run the assistant to produce conservative, reviewable editorial suggestions. It will not modify the critical text automatically.</div>}</div><p className="eai-note">AI output is advisory. Every proposal must be verified against manuscript evidence before acceptance.</p></section>
}
