import { useEffect, useMemo, useState } from "react";
import "./IiifManuscriptPage.css";

type Project={projectPath:string;projectName:string};
type Manifest={id:string;title:string;repository?:string;shelfmark?:string;summary?:string;rights?:string;provider?:string;sourceManifestUrl?:string};
type Canvas={id:string;manifestId:string;label:string;imageUrl:string;thumbnailUrl?:string;width:number;height:number;order:number;transcription?:string;ocrText?:string};
type Annotation={id:string;canvasId:string;type:string;motivation:string;text:string;language:string;x:number;y:number;width:number;height:number;sourceReference?:string;status:string};
const api=window.ocrStudio;
const blankManifest={id:"",title:"",repository:"",shelfmark:"",summary:"",rights:"",provider:"",sourceManifestUrl:""};
const blankCanvas={id:"",manifestId:"",label:"",imageUrl:"",thumbnailUrl:"",width:900,height:1200,order:0,transcription:"",ocrText:""};
const blankAnnotation={id:"",canvasId:"",type:"Region",motivation:"commenting",text:"",language:"en",x:20,y:20,width:160,height:80,sourceReference:"",status:"Draft"};
export default function IiifManuscriptPage(){
 const[projects,setProjects]=useState<Project[]>([]);const[projectPath,setProjectPath]=useState("");const[manifests,setManifests]=useState<Manifest[]>([]);const[canvases,setCanvases]=useState<Canvas[]>([]);const[annotations,setAnnotations]=useState<Annotation[]>([]);const[manifestId,setManifestId]=useState("");const[canvasId,setCanvasId]=useState("");const[mf,setMf]=useState<any>(blankManifest);const[cf,setCf]=useState<any>(blankCanvas);const[af,setAf]=useState<any>(blankAnnotation);const[tab,setTab]=useState("viewer");const[zoom,setZoom]=useState(70);const[message,setMessage]=useState("");
 const load=async(p=projectPath)=>{if(!p)return;const r=await api.getIiifProject({projectPath:p});setManifests(r.manifests||[]);setCanvases(r.canvases||[]);setAnnotations(r.annotations||[]);const mid=manifestId||(r.manifests?.[0]?.id||"");setManifestId(mid);const cid=(r.canvases||[]).find((c:Canvas)=>c.manifestId===mid)?.id||"";if(!canvasId)setCanvasId(cid)};
 useEffect(()=>{(async()=>{const r=await api.getIiifWorkspace();setProjects(r.projects||[]);if(r.projects?.[0]){setProjectPath(r.projects[0].projectPath);const d=await api.getIiifProject({projectPath:r.projects[0].projectPath});setManifests(d.manifests||[]);setCanvases(d.canvases||[]);setAnnotations(d.annotations||[]);setManifestId(d.manifests?.[0]?.id||"");setCanvasId(d.canvases?.[0]?.id||"")}})()},[]);
 const currentManifest=manifests.find(m=>m.id===manifestId);const manifestCanvases=useMemo(()=>canvases.filter(c=>c.manifestId===manifestId).sort((a,b)=>a.order-b.order),[canvases,manifestId]);const currentCanvas=canvases.find(c=>c.id===canvasId);const currentAnnotations=annotations.filter(a=>a.canvasId===canvasId);
 const saveManifest=async()=>{if(!mf.title.trim())return setMessage("Title is required.");const r=await api.saveIiifManifest({...mf,projectPath});setMf(blankManifest);setManifestId(r.manifest.id);setMessage("Manuscript manifest saved.");await load(projectPath)};
 const saveCanvas=async()=>{if(!manifestId||!cf.imageUrl.trim())return setMessage("Select a manifest and provide an image URL or file URL.");const r=await api.saveIiifCanvas({...cf,projectPath,manifestId});setCf({...blankCanvas,manifestId});setCanvasId(r.canvas.id);setMessage("Canvas saved.");await load(projectPath)};
 const saveAnnotation=async()=>{if(!canvasId||!af.text.trim())return setMessage("Select a folio and enter annotation text.");await api.saveIiifAnnotation({...af,projectPath,canvasId});setAf({...blankAnnotation,canvasId});setMessage("Region annotation saved.");await load(projectPath)};
 const exportFile=async(kind:"manifest"|"annotations")=>{if(!manifestId)return setMessage("Select a manifest first.");const r=kind==="manifest"?await api.exportIiifManifest({projectPath,manifestId}):await api.exportIiifAnnotations({projectPath,manifestId});if(r.filePath)await api.openIiifFile(r.filePath);setMessage(`${kind==="manifest"?"IIIF manifest":"Web annotations"} exported.`)};
 return <div className="iiif-page"><header className="iiif-head"><div><span>PHASE 10C · MILESTONE 3</span><h2>IIIF Digital Manuscript Viewer</h2><p>Link high-resolution folios, transcription and evidence-grounded image annotations.</p></div><div className="iiif-actions"><select value={projectPath} onChange={async e=>{setProjectPath(e.target.value);setManifestId("");setCanvasId("");await load(e.target.value)}}>{projects.map(p=><option key={p.projectPath} value={p.projectPath}>{p.projectName}</option>)}</select><button onClick={()=>exportFile("manifest")}>Export IIIF</button><button onClick={()=>exportFile("annotations")}>Export Annotations</button></div></header>{message&&<div className="iiif-message">{message}</div>}
 <nav className="iiif-tabs">{["viewer","manuscripts","folios","annotations","comparison"].map(x=><button key={x} className={tab===x?"active":""} onClick={()=>setTab(x)}>{x[0].toUpperCase()+x.slice(1)}</button>)}</nav>
 {tab==="viewer"&&<div className="viewer-grid"><aside className="folio-strip"><h3>{currentManifest?.title||"No manuscript"}</h3>{manifestCanvases.map(c=><button className={c.id===canvasId?"active":""} key={c.id} onClick={()=>setCanvasId(c.id)}><span>{c.order+1}</span><b>{c.label}</b></button>)}</aside><section className="image-panel"><div className="viewer-toolbar"><button onClick={()=>setZoom(Math.max(25,zoom-10))}>−</button><b>{zoom}%</b><button onClick={()=>setZoom(Math.min(200,zoom+10))}>＋</button><button onClick={()=>setZoom(70)}>Fit</button></div><div className="image-stage">{currentCanvas?.imageUrl?<div className="image-wrap" style={{width:`${zoom}%`}}><img src={currentCanvas.imageUrl} alt={currentCanvas.label}/>{currentAnnotations.map(a=><button key={a.id} className="region" title={a.text} style={{left:`${a.x/currentCanvas.width*100}%`,top:`${a.y/currentCanvas.height*100}%`,width:`${a.width/currentCanvas.width*100}%`,height:`${a.height/currentCanvas.height*100}%`}} onClick={()=>{setAf(a);setTab("annotations")}}/>)}</div>:<p>Add a folio image URL to begin.</p>}</div></section><aside className="text-panel"><h3>{currentCanvas?.label||"Transcription"}</h3><h4>Critical transcription</h4><p>{currentCanvas?.transcription||"No transcription linked."}</p><h4>OCR text</h4><p>{currentCanvas?.ocrText||"No OCR text linked."}</p><h4>Annotations</h4>{currentAnnotations.map(a=><article key={a.id}><b>{a.type}</b><span>{a.status}</span><p>{a.text}</p></article>)}</aside></div>}
 {tab==="manuscripts"&&<div className="editor-grid"><section className="iiif-panel"><h3>Manuscript catalog</h3>{manifests.map(m=><button className="record" key={m.id} onClick={()=>{setManifestId(m.id);setMf(m)}}><b>{m.title}</b><span>{m.repository||"Repository not recorded"} · {m.shelfmark||"No shelfmark"}</span></button>)}</section><section className="iiif-panel form"><h3>{mf.id?"Edit manifest":"New IIIF manifest"}</h3><label>Title<input value={mf.title} onChange={e=>setMf({...mf,title:e.target.value})}/></label><div className="two"><label>Repository<input value={mf.repository} onChange={e=>setMf({...mf,repository:e.target.value})}/></label><label>Shelfmark<input value={mf.shelfmark} onChange={e=>setMf({...mf,shelfmark:e.target.value})}/></label></div><label>Summary<textarea value={mf.summary} onChange={e=>setMf({...mf,summary:e.target.value})}/></label><label>Source IIIF manifest URL<input value={mf.sourceManifestUrl} onChange={e=>setMf({...mf,sourceManifestUrl:e.target.value})}/></label><div className="form-actions"><button onClick={saveManifest}>Save manifest</button><button onClick={()=>setMf(blankManifest)}>Clear</button>{mf.id&&<button className="danger" onClick={async()=>{await api.deleteIiifManifest({projectPath,id:mf.id});setMf(blankManifest);setManifestId("");await load(projectPath)}}>Delete</button>}</div></section></div>}
 {tab==="folios"&&<div className="editor-grid"><section className="iiif-panel"><h3>Canvases / folios</h3><select value={manifestId} onChange={e=>setManifestId(e.target.value)}>{manifests.map(m=><option key={m.id} value={m.id}>{m.title}</option>)}</select>{manifestCanvases.map(c=><button className="record" key={c.id} onClick={()=>{setCanvasId(c.id);setCf(c)}}><b>{c.label}</b><span>{c.width} × {c.height} · order {c.order+1}</span></button>)}</section><section className="iiif-panel form"><h3>{cf.id?"Edit folio":"Add folio"}</h3><label>Folio label<input value={cf.label} onChange={e=>setCf({...cf,label:e.target.value})}/></label><label>Image URL or file URL<input value={cf.imageUrl} onChange={e=>setCf({...cf,imageUrl:e.target.value})} placeholder="file:///C:/.../folio.jpg or https://..."/></label><div className="three"><label>Width<input type="number" value={cf.width} onChange={e=>setCf({...cf,width:Number(e.target.value)})}/></label><label>Height<input type="number" value={cf.height} onChange={e=>setCf({...cf,height:Number(e.target.value)})}/></label><label>Order<input type="number" value={cf.order} onChange={e=>setCf({...cf,order:Number(e.target.value)})}/></label></div><label>Transcription<textarea value={cf.transcription} onChange={e=>setCf({...cf,transcription:e.target.value})}/></label><label>OCR text<textarea value={cf.ocrText} onChange={e=>setCf({...cf,ocrText:e.target.value})}/></label><div className="form-actions"><button onClick={saveCanvas}>Save folio</button><button onClick={()=>setCf({...blankCanvas,manifestId})}>Clear</button>{cf.id&&<button className="danger" onClick={async()=>{await api.deleteIiifCanvas({projectPath,id:cf.id});setCf({...blankCanvas,manifestId});await load(projectPath)}}>Delete</button>}</div></section></div>}
 {tab==="annotations"&&<div className="editor-grid"><section className="iiif-panel"><h3>Image annotations</h3><select value={canvasId} onChange={e=>setCanvasId(e.target.value)}>{manifestCanvases.map(c=><option key={c.id} value={c.id}>{c.label}</option>)}</select>{currentAnnotations.map(a=><button className="record" key={a.id} onClick={()=>setAf(a)}><b>{a.type} · {a.status}</b><span>{a.text}</span></button>)}</section><section className="iiif-panel form"><h3>{af.id?"Edit annotation":"New region annotation"}</h3><div className="two"><label>Type<select value={af.type} onChange={e=>setAf({...af,type:e.target.value})}><option>Region</option><option>Line</option><option>Word</option><option>Damage</option><option>Marginalia</option><option>Decoration</option></select></label><label>Status<select value={af.status} onChange={e=>setAf({...af,status:e.target.value})}><option>Draft</option><option>Reviewed</option><option>Approved</option></select></label></div><label>Annotation text<textarea value={af.text} onChange={e=>setAf({...af,text:e.target.value})}/></label><div className="four">{["x","y","width","height"].map(k=><label key={k}>{k.toUpperCase()}<input type="number" value={af[k]} onChange={e=>setAf({...af,[k]:Number(e.target.value)})}/></label>)}</div><label>Source reference<input value={af.sourceReference} onChange={e=>setAf({...af,sourceReference:e.target.value})}/></label><div className="form-actions"><button onClick={saveAnnotation}>Save annotation</button><button onClick={()=>setAf({...blankAnnotation,canvasId})}>Clear</button>{af.id&&<button className="danger" onClick={async()=>{await api.deleteIiifAnnotation({projectPath,id:af.id});setAf({...blankAnnotation,canvasId});await load(projectPath)}}>Delete</button>}</div></section></div>}
 {tab==="comparison"&&<section className="iiif-panel comparison"><h3>Synchronized Folio Comparison</h3><p>Compare the selected folio with another canvas at the same zoom level.</p><div className="compare-images">{manifestCanvases.slice(0,2).map(c=><article key={c.id}><h4>{c.label}</h4>{c.imageUrl?<img src={c.imageUrl} alt={c.label}/>:<div>No image</div>}<p>{c.transcription||"No transcription"}</p></article>)}</div></section>}
 </div>}
