import { useEffect, useMemo, useState } from "react";
import "./ScholarlyAssistantPage.css";
type Evidence={id:string;sourceType:string;text:string;relativePath:string;field:string;score:number};
type Conversation={id:string;title:string;updatedAt:string;messages:any[]};
export default function ScholarlyAssistantPage(){
 const api=window.ocrStudio;const[projects,setProjects]=useState<any[]>([]);const[projectPath,setProjectPath]=useState("");const[conversations,setConversations]=useState<Conversation[]>([]);const[current,setCurrent]=useState<Conversation|null>(null);const[prompts,setPrompts]=useState<any[]>([]);const[notebooks,setNotebooks]=useState<any[]>([]);const[bookmarks,setBookmarks]=useState<any[]>([]);const[index,setIndex]=useState<any>(null);const[question,setQuestion]=useState("");const[busy,setBusy]=useState(false);const[tab,setTab]=useState("assistant");const[message,setMessage]=useState("");
 const load=async(p=projectPath)=>{const r=await api.getScholarlyAssistantWorkspace({projectPath:p});setProjects(r.projects||[]);setConversations(r.conversations||[]);setPrompts(r.prompts||[]);setNotebooks(r.notebooks||[]);setBookmarks(r.bookmarks||[]);setIndex(r.index);if(r.projectPath&&!projectPath)setProjectPath(r.projectPath)};
 useEffect(()=>{load()},[]);
 const lastAssistant=useMemo(()=>[...(current?.messages||[])].reverse().find(m=>m.role==="assistant"),[current]);
 const ask=async()=>{if(!question.trim()||!projectPath)return;setBusy(true);setMessage("");const r=await api.askScholarlyAssistant({projectPath,conversationId:current?.id||null,question});if(r.success){setCurrent(r.conversation);setQuestion("");await load(projectPath)}else setMessage(r.message||"Question failed.");setBusy(false)};
 const saveNote=async()=>{if(!lastAssistant)return;const title=prompt("Notebook title",current?.title||"Research note");if(!title)return;await api.saveScholarlyNotebook({projectPath,notebook:{title,body:lastAssistant.content,tags:["assistant"],conversationId:current?.id,evidence:lastAssistant.evidence||[]}});await load(projectPath);setTab("notebooks")};
 const bookmark=async(e:Evidence)=>{await api.saveScholarlyBookmark({projectPath,bookmark:{title:e.sourceType,sourceType:e.sourceType,sourcePath:e.relativePath,text:e.text}});await load(projectPath);setMessage("Evidence bookmarked.")};
 const reindex=async()=>{setBusy(true);const r=await api.rebuildScholarlySemanticIndex({projectPath});setIndex(r.index);setMessage(r.message);setBusy(false)};
 const exportConversation=async(format:string)=>{if(!current)return;const r=await api.exportScholarlyConversation({projectPath,conversationId:current.id,format});if(r.filePath)await api.openScholarlyAssistantFile(r.filePath)};
 return <div className="sa-page"><header className="sa-head"><div><span>PHASE 10C · MILESTONE 2</span><h2>Research Assistant & Scholarly Copilot</h2><p>Ask evidence-grounded questions across editions, manuscripts, apparatus, translations, decisions and the knowledge graph.</p></div><div className="sa-actions"><select value={projectPath} onChange={async e=>{setProjectPath(e.target.value);setCurrent(null);await load(e.target.value)}}>{projects.map(p=><option key={p.projectPath} value={p.projectPath}>{p.projectName}</option>)}</select><button onClick={reindex} disabled={busy}>Rebuild index</button></div></header>
 <div className="sa-metrics"><div><b>{index?.documentCount||0}</b><span>Indexed evidence items</span></div><div><b>{conversations.length}</b><span>Conversations</span></div><div><b>{notebooks.length}</b><span>Notebook entries</span></div><div><b>{bookmarks.length}</b><span>Bookmarks</span></div></div>
 <nav className="sa-tabs">{["assistant","prompts","notebooks","bookmarks"].map(t=><button className={tab===t?"active":""} onClick={()=>setTab(t)} key={t}>{t}</button>)}</nav>{message&&<p className="sa-message">{message}</p>}
 {tab==="assistant"&&<div className="sa-grid"><aside className="sa-history"><button className="primary" onClick={()=>setCurrent(null)}>＋ New conversation</button>{conversations.map(c=><button key={c.id} className={current?.id===c.id?"selected":""} onClick={()=>setCurrent(c)}><b>{c.title}</b><small>{new Date(c.updatedAt).toLocaleString()}</small></button>)}</aside><main className="sa-chat"><div className="sa-messages">{!current&&<div className="sa-empty"><h3>Grounded scholarly research</h3><p>Answers are assembled only from indexed project evidence. Each result exposes its source and location.</p></div>}{current?.messages.map(m=><article key={m.id} className={`sa-msg ${m.role}`}><div className="role">{m.role==="assistant"?"Scholarly Copilot":"You"}</div><p>{m.content}</p>{m.confidence!=null&&<div className="confidence">Evidence confidence: {Math.round(m.confidence*100)}%</div>}{(m.evidence||[]).map((e:Evidence)=><details key={e.id}><summary>{e.sourceType} · {e.relativePath}</summary><p>{e.text}</p><button onClick={()=>bookmark(e)}>Bookmark evidence</button></details>)}</article>)}</div><div className="sa-composer"><textarea value={question} onChange={e=>setQuestion(e.target.value)} placeholder="Ask a question grounded in this project's scholarly evidence…" onKeyDown={e=>{if(e.key==="Enter"&&e.ctrlKey)ask()}}/><div><span>Ctrl + Enter to ask</span><button onClick={saveNote} disabled={!lastAssistant}>Save answer</button><button onClick={()=>exportConversation("html")} disabled={!current}>Export</button><button className="primary" onClick={ask} disabled={busy||!question.trim()}>{busy?"Searching…":"Ask"}</button></div></div></main></div>}
 {tab==="prompts"&&<section className="sa-cards">{prompts.map(p=><article key={p.id}><small>{p.category}</small><h3>{p.title}</h3><p>{p.prompt}</p><button onClick={()=>{setQuestion(p.prompt);setTab("assistant")}}>Use prompt</button></article>)}</section>}
 {tab==="notebooks"&&<section className="sa-cards">{notebooks.map(n=><article key={n.id}><h3>{n.title}</h3><p>{n.body}</p><small>{(n.tags||[]).join(" · ")}</small><button onClick={async()=>{await api.deleteScholarlyNotebook({projectPath,id:n.id});load(projectPath)}}>Delete</button></article>)}</section>}
 {tab==="bookmarks"&&<section className="sa-cards">{bookmarks.map(b=><article key={b.id}><small>{b.sourceType}</small><h3>{b.title}</h3><p>{b.text}</p><code>{b.sourcePath}</code><button onClick={async()=>{await api.deleteScholarlyBookmark({projectPath,id:b.id});load(projectPath)}}>Delete</button></article>)}</section>}
 </div>}
