import { useEffect, useMemo, useState } from "react";
import { getProjects } from "../../services/projectStorage";
import type { Project } from "../../services/projectStorage";
import type { Collection } from "../../types/Collection";
import "./CollectionsPage.css";

const fmt=(n:number)=>new Intl.NumberFormat().format(n||0);
const bytes=(n:number)=>{if(!n)return "0 B";const u=["B","KB","MB","GB","TB"];const i=Math.min(Math.floor(Math.log(n)/Math.log(1024)),4);return `${(n/1024**i).toFixed(i?1:0)} ${u[i]}`};

export default function CollectionsPage(){
 const [workspace,setWorkspace]=useState(""); const [workspaces,setWorkspaces]=useState<string[]>([]); const [collections,setCollections]=useState<Collection[]>([]); const [unassigned,setUnassigned]=useState<Project[]>([]); const [selected,setSelected]=useState<Collection|null>(null); const [showForm,setShowForm]=useState(false); const [message,setMessage]=useState(""); const [search,setSearch]=useState("");
 const [editingId,setEditingId]=useState<string|null>(null);
 const [form,setForm]=useState({name:"",description:"",institution:"",owner:"",license:"",languages:"",tags:"",color:"#c2410c",icon:"📚"});
 useEffect(()=>{void getProjects().then(p=>{const ws=[...new Set(p.map(x=>x.workspacePath).filter(Boolean))] as string[];setWorkspaces(ws);if(ws[0])setWorkspace(ws[0]);});},[]);
 const load=async()=>{if(!workspace)return;const r=await window.ocrStudio.listCollections({workspacePath:workspace});setCollections(r.collections||[]);setUnassigned(r.unassignedProjects||[]);if(selected)setSelected((r.collections||[]).find((x:Collection)=>x.id===selected.id)||null);};
 useEffect(()=>{void load();},[workspace]);
 const filtered=useMemo(()=>collections.filter(c=>(c.name+" "+c.description+" "+c.tags.join(" ")).toLowerCase().includes(search.toLowerCase())),[collections,search]);
 const save=async()=>{if(!form.name.trim())return setMessage("Collection name is required.");const payload={...form,languages:form.languages.split(",").map(x=>x.trim()).filter(Boolean),tags:form.tags.split(",").map(x=>x.trim()).filter(Boolean)};const r=editingId?await window.ocrStudio.updateCollection({workspacePath:workspace,collection:{id:editingId,...payload}}):await window.ocrStudio.createCollection({workspacePath:workspace,...payload});setMessage(r.message);setShowForm(false);setEditingId(null);setForm({name:"",description:"",institution:"",owner:"",license:"",languages:"",tags:"",color:"#c2410c",icon:"📚"});await load();};
 const edit=(c:Collection)=>{setEditingId(c.id);setForm({name:c.name,description:c.description,institution:c.institution,owner:c.owner,license:c.license,languages:c.languages.join(", "),tags:c.tags.join(", "),color:c.color,icon:c.icon});setShowForm(true);};
 const assign=async(projectId:number,collectionId:string)=>{const r=await window.ocrStudio.assignProjectToCollection({workspacePath:workspace,projectId,collectionId:collectionId||null});setMessage(r.message);await load();};
 const remove=async(c:Collection)=>{if(!confirm(`Delete collection "${c.name}"? Projects will not be deleted.`))return;const r=await window.ocrStudio.deleteCollection({workspacePath:workspace,collectionId:c.id});setMessage(r.message);setSelected(null);await load();};
 const exportOne=async(c:Collection)=>{const r=await window.ocrStudio.exportCollection({workspacePath:workspace,collectionId:c.id});setMessage(r.message+(r.filePath?` ${r.filePath}`:""));};
 return <div className="collections-page">
  <div className="collections-header"><div><span className="eyebrow">Digital library</span><h2>Collections Manager</h2><p>Organize OCR projects into searchable, measurable library collections.</p></div><button className="primary" disabled={!workspace} onClick={()=>setShowForm(true)}>＋ New Collection</button></div>
  <div className="collections-toolbar"><select value={workspace} onChange={e=>setWorkspace(e.target.value)}><option value="">Select workspace</option>{workspaces.map(w=><option key={w}>{w}</option>)}</select><input placeholder="Search collections..." value={search} onChange={e=>setSearch(e.target.value)}/><button onClick={()=>void load()}>Refresh statistics</button></div>
  {!workspace&&<div className="collections-empty">Create a project first or select a workspace.</div>}
  <div className="collection-grid">{filtered.map(c=><article className="collection-card" key={c.id} style={{borderTopColor:c.color}} onClick={()=>setSelected(c)}><div className="collection-card-title"><span>{c.icon}</span><div><h3>{c.name}</h3><p>{c.description||"No description"}</p></div></div><div className="collection-kpis"><div><strong>{c.statistics.projectCount}</strong><span>Projects</span></div><div><strong>{fmt(c.statistics.pages)}</strong><span>Pages</span></div><div><strong>{fmt(c.statistics.words)}</strong><span>Words</span></div><div><strong>{c.statistics.reviewPercent}%</strong><span>Reviewed</span></div></div><div className="collection-meta"><span>{c.languages.join(", ")||"Languages not set"}</span><span>{bytes(c.statistics.storageBytes)}</span></div></article>)}</div>
  {unassigned.length>0&&<section className="unassigned-panel"><h3>Unassigned projects</h3><p>Place these projects into a collection.</p>{unassigned.map(p=><div className="project-assignment" key={p.id}><div><strong>{p.name}</strong><small>{p.projectPath}</small></div><select defaultValue="" onChange={e=>void assign(p.id,e.target.value)}><option value="">Choose collection</option>{collections.map(c=><option value={c.id} key={c.id}>{c.name}</option>)}</select></div>)}</section>}
  {selected&&<div className="collection-detail"><div className="collection-detail-head"><div><span>{selected.icon}</span><h2>{selected.name}</h2><p>{selected.description}</p></div><div><button onClick={()=>edit(selected)}>Edit metadata</button><button onClick={()=>void exportOne(selected)}>Export ZIP</button><button className="danger" onClick={()=>void remove(selected)}>Delete</button><button onClick={()=>setSelected(null)}>Close</button></div></div><div className="detail-stats">{Object.entries({Projects:selected.statistics.projectCount,Documents:selected.statistics.documents,Pages:fmt(selected.statistics.pages),Words:fmt(selected.statistics.words),Confidence:`${selected.statistics.averageConfidence}%`,Reviewed:`${selected.statistics.reviewPercent}%`,Published:selected.statistics.publishedDocuments,Storage:bytes(selected.statistics.storageBytes)}).map(([k,v])=><div key={k}><span>{k}</span><strong>{v}</strong></div>)}</div><h3>Projects</h3>{selected.projects.length?selected.projects.map(p=><div className="project-assignment" key={p.id}><div><strong>{p.name}</strong><small>{p.language} · {p.workflow}</small></div><select value={selected.id} onChange={e=>void assign(p.id,e.target.value)}><option value="">Unassigned</option>{collections.map(c=><option value={c.id} key={c.id}>{c.name}</option>)}</select></div>):<p>No projects assigned.</p>}</div>}
  {showForm&&<div className="collection-modal-backdrop"><div className="collection-modal"><h2>{editingId?"Edit Collection":"New Collection"}</h2><div className="collection-form"><input placeholder="Collection name" value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/><textarea placeholder="Description" value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/><input placeholder="Languages, comma separated" value={form.languages} onChange={e=>setForm({...form,languages:e.target.value})}/><input placeholder="Tags, comma separated" value={form.tags} onChange={e=>setForm({...form,tags:e.target.value})}/><input placeholder="Institution" value={form.institution} onChange={e=>setForm({...form,institution:e.target.value})}/><input placeholder="Owner" value={form.owner} onChange={e=>setForm({...form,owner:e.target.value})}/><input placeholder="License" value={form.license} onChange={e=>setForm({...form,license:e.target.value})}/><div className="form-inline"><input aria-label="Icon" value={form.icon} onChange={e=>setForm({...form,icon:e.target.value})}/><input type="color" value={form.color} onChange={e=>setForm({...form,color:e.target.value})}/></div></div><div className="modal-actions"><button onClick={()=>{setShowForm(false);setEditingId(null)}}>Cancel</button><button className="primary" onClick={()=>void save()}>{editingId?"Save Changes":"Create Collection"}</button></div></div></div>}
  {message&&<div className="collection-message">{message}<button onClick={()=>setMessage("")}>×</button></div>}
 </div>;
}
