import { useEffect, useMemo, useState } from "react";
import "./KnowledgeGraphPage.css";

type Evidence={documentName?:string;documentId?:number;pageNumber?:number;excerpt?:string;quote?:string};
type Entity={id:string;name:string;type:string;aliases:string[];description:string;status:string;confidence:number;evidence:Evidence[]};
type Relationship={id:string;sourceId:string;targetId:string;type:string;status:string;confidence:number;evidence?:Evidence;extractionMethod?:string};

type Analytics={connected:Array<{entity:Entity;count:number}>;byType:Array<{type:string;count:number}>;relationTypes:Array<{type:string;count:number}>;isolated:number;verified:number;suggested:number};
const emptyAnalytics:Analytics={connected:[],byType:[],relationTypes:[],isolated:0,verified:0,suggested:0};

export default function KnowledgeGraphPage(){
 const [workspace,setWorkspace]=useState<any>({projects:[],totals:{}});
 const [projectPath,setProjectPath]=useState("");
 const [graph,setGraph]=useState<any>({entities:[],relationships:[],reviewQueue:[]});
 const [analytics,setAnalytics]=useState<Analytics>(emptyAnalytics);
 const [selected,setSelected]=useState<Entity|null>(null);
 const [selectedRelationship,setSelectedRelationship]=useState<Relationship|null>(null);
 const [search,setSearch]=useState("");
 const [typeFilter,setTypeFilter]=useState("All");
 const [statusFilter,setStatusFilter]=useState("All");
 const [message,setMessage]=useState("");
 const [busy,setBusy]=useState(false);
 const [activeView,setActiveView]=useState<"network"|"analytics">("network");

 const loadWorkspace=async()=>{const r=await window.ocrStudio.getKnowledgeGraphWorkspace();setWorkspace(r);if(!projectPath&&r.projects?.[0]){setProjectPath(r.projects[0].projectPath);await loadProject(r.projects[0].projectPath)}};
 const loadProject=async(p:string)=>{const r=await window.ocrStudio.getProjectKnowledgeGraph({projectPath:p});setGraph(r.graph);setAnalytics(r.analytics||emptyAnalytics);setSelected(null);setSelectedRelationship(null)};
 useEffect(()=>{void loadWorkspace()},[]);
 const entities=useMemo(()=>graph.entities.filter((e:Entity)=>{const text=(e.name+" "+e.type+" "+(e.aliases||[]).join(" ")).toLowerCase();return text.includes(search.toLowerCase())&&(typeFilter==="All"||e.type===typeFilter)&&(statusFilter==="All"||e.status===statusFilter)}),[graph,search,typeFilter,statusFilter]);
 const types=useMemo(()=>["All",...Array.from(new Set<string>(graph.entities.map((e:Entity)=>e.type)))],[graph.entities]);
 const name=(id:string)=>graph.entities.find((e:Entity)=>e.id===id)?.name||"Unknown";
 const refresh=(r:any)=>{if(r.graph)setGraph(r.graph);if(r.analytics)setAnalytics(r.analytics);setMessage(r.message||"")};
 const extract=async()=>{if(!projectPath)return;setBusy(true);try{refresh(await window.ocrStudio.extractKnowledgeGraph({projectPath}));await loadWorkspace()}finally{setBusy(false)}};
 const discover=async()=>{if(!projectPath)return;const model=prompt("Ollama model","llama3.2:3b")||"llama3.2:3b";const pages=Number(prompt("Maximum pages to analyze in this run","12")||12);setBusy(true);setMessage("Local AI is reading reviewed OCR passages…");try{const r=await window.ocrStudio.discoverKnowledgeGraphRelationships({projectPath,endpoint:"http://127.0.0.1:11434",model,pageLimit:pages});refresh(r);await loadWorkspace()}catch(error){setMessage(error instanceof Error?error.message:"AI relationship discovery failed.")}finally{setBusy(false)}};
 const addEntity=async()=>{const n=prompt("Entity name");if(!n)return;const type=prompt("Type (Person / Character, Place, Concept, Event, Text)","Person / Character")||"Concept";const d=prompt("Description (optional)","")||"";refresh(await window.ocrStudio.addKnowledgeGraphEntity({projectPath,name:n,type,description:d}))};
 const addRel=async()=>{if(!selected)return;const targetName=prompt("Target entity name");const target=graph.entities.find((e:Entity)=>e.name.toLowerCase()===targetName?.toLowerCase());if(!target){setMessage("Target entity not found.");return}const type=prompt("Relationship","Related to")||"Related to";refresh(await window.ocrStudio.addKnowledgeGraphRelationship({projectPath,sourceId:selected.id,targetId:target.id,type}))};
 const review=async(id:string,decision:string)=>{const note=decision==="Rejected"?(prompt("Reason for rejection (optional)","")||""):"";refresh(await window.ocrStudio.reviewKnowledgeGraphItem({projectPath,reviewId:id,decision,note}))};
 const exportGraph=async()=>{const r=await window.ocrStudio.exportKnowledgeGraph({projectPath});setMessage(r.message);if(r.filePath)await window.ocrStudio.openKnowledgeGraphFile(r.filePath)};
 const related=selected?graph.relationships.filter((r:Relationship)=>r.sourceId===selected.id||r.targetId===selected.id):[];
 const pending=graph.reviewQueue.filter((q:any)=>q.status==="Pending");
 return <div className="kg-page">
  <header className="kg-head"><div><p className="eyebrow">PHASE 7.0B</p><h2>AI Relationship Discovery</h2><p>Discover evidence-backed relationships with local AI, review every claim, and explore the manuscript as a scholarly network.</p></div><div className="actions"><button onClick={addEntity}>＋ Entity</button><button onClick={extract} disabled={busy}>Extract basics</button><button className="ai-button" onClick={discover} disabled={busy}>{busy?"Analyzing…":"✦ Discover with Ollama"}</button><button onClick={exportGraph}>Export JSON</button></div></header>
  <div className="metrics"><article><b>{workspace.totals?.entities||0}</b><span>Entities</span></article><article><b>{workspace.totals?.relationships||0}</b><span>Relationships</span></article><article><b>{workspace.totals?.pending||0}</b><span>Needs review</span></article><article><b>{analytics.verified||0}</b><span>Verified links</span></article></div>
  <div className="toolbar"><select value={projectPath} onChange={e=>{setProjectPath(e.target.value);void loadProject(e.target.value)}}>{workspace.projects?.map((p:any)=><option key={p.projectPath} value={p.projectPath}>{p.projectName}</option>)}</select><input placeholder="Search entities, aliases, types…" value={search} onChange={e=>setSearch(e.target.value)}/><select value={typeFilter} onChange={e=>setTypeFilter(e.target.value)}>{types.map(t=><option key={t}>{t}</option>)}</select><select value={statusFilter} onChange={e=>setStatusFilter(e.target.value)}><option>All</option><option>Suggested</option><option>Verified</option><option>Rejected</option></select><div className="view-switch"><button className={activeView==="network"?"active":""} onClick={()=>setActiveView("network")}>Network</button><button className={activeView==="analytics"?"active":""} onClick={()=>setActiveView("analytics")}>Analytics</button></div></div>
  {message&&<div className="kg-message">{message}</div>}
  {activeView==="network"?<div className="kg-grid">
   <section className="panel"><h3>Entity Explorer <small>{entities.length}</small></h3><div className="entity-list">{entities.map((e:Entity)=><button className={selected?.id===e.id?"entity active":"entity"} key={e.id} onClick={()=>{setSelected(e);setSelectedRelationship(null)}}><span className="node">{e.name.slice(0,1)}</span><span><b>{e.name}</b><small>{e.type} · {e.status} · {e.evidence?.length||0} citations</small></span></button>)}</div></section>
   <section className="panel graph"><h3>Relationship Network <small>{graph.relationships.length}</small></h3>{graph.relationships.length===0?<div className="empty">Run extraction or local AI discovery to begin the graph.</div>:<div className="network-stage">{graph.relationships.slice(0,120).map((r:Relationship)=><button className={`edge-card ${r.status.toLowerCase()}`} key={r.id} onClick={()=>{setSelectedRelationship(r);setSelected(graph.entities.find((e:Entity)=>e.id===r.sourceId)||null)}}><span className="entity-pill">{name(r.sourceId)}</span><span className="relation-arrow">{r.type}<i>→</i></span><span className="entity-pill">{name(r.targetId)}</span><small>{Math.round((r.confidence||0)*100)}% · {r.status} · {r.extractionMethod||"Unknown"}</small></button>)}</div>}</section>
   <aside className="panel detail"><h3>Evidence Inspector</h3>{selectedRelationship?<><div className="relationship-title"><b>{name(selectedRelationship.sourceId)}</b><span>{selectedRelationship.type}</span><b>{name(selectedRelationship.targetId)}</b></div><div className="confidence"><span style={{width:`${Math.round((selectedRelationship.confidence||0)*100)}%`}}/></div><p><b>{Math.round((selectedRelationship.confidence||0)*100)}% confidence</b> · {selectedRelationship.extractionMethod||"Unknown method"}</p>{selectedRelationship.evidence?<div className="citation"><b>{selectedRelationship.evidence.documentName}</b><span>Page {selectedRelationship.evidence.pageNumber}</span>{selectedRelationship.evidence.quote&&<blockquote>“{selectedRelationship.evidence.quote}”</blockquote>}<p>{selectedRelationship.evidence.excerpt}</p></div>:<p>No source evidence attached.</p>}</>:selected?<><h2>{selected.name}</h2><span className="badge">{selected.type}</span><p>{selected.description||"No scholarly description yet."}</p><h4>Aliases</h4><p>{selected.aliases?.join(", ")||"None"}</p><h4>Connections ({related.length})</h4>{related.slice(0,8).map((r:Relationship)=><button className="mini-relation" key={r.id} onClick={()=>setSelectedRelationship(r)}>{name(r.sourceId)} — {r.type} — {name(r.targetId)}</button>)}<h4>Evidence</h4>{selected.evidence?.slice(0,5).map((x:Evidence,i:number)=><div className="citation" key={i}><b>{x.documentName}</b><span>Page {x.pageNumber}</span><p>{x.excerpt}</p></div>)}<button onClick={addRel}>＋ Add relationship</button></>:<div className="empty">Select an entity or relationship to inspect its evidence.</div>}</aside>
  </div>:<section className="analytics-grid"><article className="panel"><h3>Most Connected Entities</h3>{analytics.connected.map((x,i)=><div className="rank-row" key={x.entity?.id||i}><b>{i+1}</b><span>{x.entity?.name||"Unknown"}<small>{x.entity?.type}</small></span><strong>{x.count}</strong></div>)}</article><article className="panel"><h3>Entity Types</h3>{analytics.byType.map(x=><div className="bar-row" key={x.type}><span>{x.type}</span><div><i style={{width:`${Math.min(100,x.count/Math.max(1,graph.entities.length)*100)}%`}}/></div><b>{x.count}</b></div>)}</article><article className="panel"><h3>Relationship Types</h3>{analytics.relationTypes.slice(0,12).map(x=><div className="bar-row" key={x.type}><span>{x.type}</span><div><i style={{width:`${Math.min(100,x.count/Math.max(1,graph.relationships.length)*100)}%`}}/></div><b>{x.count}</b></div>)}</article><article className="panel summary-card"><h3>Graph Health</h3><b>{analytics.verified}</b><span>verified relationships</span><b>{analytics.suggested}</b><span>awaiting review</span><b>{analytics.isolated}</b><span>isolated entities</span></article></section>}
  <section className="panel review"><div className="review-head"><h3>Relationship Review Queue</h3><span>{pending.length} pending</span></div>{pending.length===0?<div className="empty compact">No suggestions are waiting for review.</div>:pending.slice(0,30).map((q:any)=>{const rel=graph.relationships.find((r:Relationship)=>r.id===q.targetId);return <div className="review-row" key={q.id}><span><b>{q.kind}</b> · {q.kind==="Entity"?name(q.targetId):rel?`${name(rel.sourceId)} — ${rel.type} — ${name(rel.targetId)}`:"Relationship"}<small>{rel?.extractionMethod} {rel?`· ${Math.round(rel.confidence*100)}% confidence`:""}</small></span><div><button onClick={()=>review(q.id,"Approved")}>Approve</button><button onClick={()=>review(q.id,"Rejected")}>Reject</button></div></div>})}</section>
 </div>
}
