import fs from "fs";
import path from "path";
import crypto from "crypto";

const now=()=>new Date().toISOString();
const uid=(p)=>`${p}-${Date.now()}-${crypto.randomBytes(3).toString("hex")}`;
const root=(projectPath)=>path.join(projectPath,".ocr-studio","collaboration");
const file=(projectPath,name)=>path.join(root(projectPath),name);
const read=(p,f)=>{try{return JSON.parse(fs.readFileSync(p,"utf8"));}catch{return f;}};
const write=(p,v)=>{fs.mkdirSync(path.dirname(p),{recursive:true});fs.writeFileSync(p,JSON.stringify(v,null,2),"utf8");};
const clean=(v)=>String(v??"").trim();
function ensure(projectPath){fs.mkdirSync(root(projectPath),{recursive:true});for(const n of ["contributors.json","assignments.json","comments.json","activity.json","settings.json"]){if(!fs.existsSync(file(projectPath,n)))write(file(projectPath,n),n==="settings.json"?{}:[]);}}
function data(projectPath){ensure(projectPath);return{contributors:read(file(projectPath,"contributors.json"),[]),assignments:read(file(projectPath,"assignments.json"),[]),comments:read(file(projectPath,"comments.json"),[]),activity:read(file(projectPath,"activity.json"),[]),settings:read(file(projectPath,"settings.json"),{})};}
function save(projectPath,name,value){write(file(projectPath,name),value);}
function log(projectPath,action,details,actor="Local User"){const items=read(file(projectPath,"activity.json"),[]);items.unshift({id:uid("activity"),action,details,actor,createdAt:now()});save(projectPath,"activity.json",items.slice(0,500));}
function dashboard(d){const open=d.assignments.filter(a=>!["Completed","Cancelled"].includes(a.status)).length;const overdue=d.assignments.filter(a=>a.dueDate&&new Date(a.dueDate)<new Date()&&!["Completed","Cancelled"].includes(a.status)).length;return{contributors:d.contributors.length,assignments:d.assignments.length,open,overdue,comments:d.comments.length,completed:d.assignments.filter(a=>a.status==="Completed").length};}
export function registerCollaborationIpc({ipcMain,shell,getProjects}){
 ipcMain.handle("collab:getWorkspace",async()=>({success:true,projects:((await getProjects())||[]).map(p=>({projectPath:p.projectPath,projectName:p.name}))}));
 ipcMain.handle("collab:getProject",async(_,{projectPath})=>{const d=data(projectPath);return{success:true,...d,dashboard:dashboard(d)};});
 ipcMain.handle("collab:saveContributor",async(_,x)=>{const d=data(x.projectPath);const v={id:x.id||uid("person"),name:clean(x.name)||"Unnamed contributor",email:clean(x.email),role:x.role||"Editor",expertise:clean(x.expertise),status:x.status||"Active",notes:clean(x.notes),createdAt:x.createdAt||now(),updatedAt:now()};const i=d.contributors.findIndex(a=>a.id===v.id);if(i>=0)d.contributors[i]=v;else d.contributors.push(v);save(x.projectPath,"contributors.json",d.contributors);log(x.projectPath,x.id?"Contributor updated":"Contributor added",v.name);return{success:true,contributor:v};});
 ipcMain.handle("collab:deleteContributor",async(_,{projectPath,id})=>{const d=data(projectPath);const p=d.contributors.find(x=>x.id===id);save(projectPath,"contributors.json",d.contributors.filter(x=>x.id!==id));log(projectPath,"Contributor removed",p?.name||id);return{success:true};});
 ipcMain.handle("collab:saveAssignment",async(_,x)=>{const d=data(x.projectPath);const v={id:x.id||uid("assignment"),title:clean(x.title)||"Untitled assignment",description:clean(x.description),assigneeId:x.assigneeId||"",reviewerId:x.reviewerId||"",module:x.module||"General",sourceReference:clean(x.sourceReference),priority:x.priority||"Medium",status:x.status||"Backlog",dueDate:x.dueDate||"",progress:Math.max(0,Math.min(100,Number(x.progress)||0)),createdAt:x.createdAt||now(),updatedAt:now()};const i=d.assignments.findIndex(a=>a.id===v.id);if(i>=0)d.assignments[i]=v;else d.assignments.push(v);save(x.projectPath,"assignments.json",d.assignments);log(x.projectPath,x.id?"Assignment updated":"Assignment created",`${v.title} · ${v.status}`);return{success:true,assignment:v};});
 ipcMain.handle("collab:deleteAssignment",async(_,{projectPath,id})=>{const d=data(projectPath);const a=d.assignments.find(x=>x.id===id);save(projectPath,"assignments.json",d.assignments.filter(x=>x.id!==id));save(projectPath,"comments.json",d.comments.filter(x=>x.assignmentId!==id));log(projectPath,"Assignment deleted",a?.title||id);return{success:true};});
 ipcMain.handle("collab:addComment",async(_,x)=>{const d=data(x.projectPath);const v={id:uid("comment"),assignmentId:x.assignmentId||"",authorId:x.authorId||"",body:clean(x.body),type:x.type||"Comment",resolved:false,createdAt:now(),updatedAt:now()};d.comments.unshift(v);save(x.projectPath,"comments.json",d.comments);log(x.projectPath,"Comment added",v.body.slice(0,120));return{success:true,comment:v};});
 ipcMain.handle("collab:resolveComment",async(_,{projectPath,id,resolved})=>{const d=data(projectPath);const i=d.comments.findIndex(x=>x.id===id);if(i>=0){d.comments[i]={...d.comments[i],resolved:Boolean(resolved),updatedAt:now()};save(projectPath,"comments.json",d.comments);log(projectPath,resolved?"Comment resolved":"Comment reopened",d.comments[i].body.slice(0,120));}return{success:true};});
 ipcMain.handle("collab:saveSettings",async(_,{projectPath,settings})=>{save(projectPath,"settings.json",settings||{});log(projectPath,"Collaboration settings updated","Project workflow settings changed");return{success:true};});
 ipcMain.handle("collab:export",async(_,{projectPath})=>{const d=data(projectPath);const out=path.join(root(projectPath),`collaboration-report-${Date.now()}.html`);const names=Object.fromEntries(d.contributors.map(p=>[p.id,p.name]));const rows=d.assignments.map(a=>`<tr><td>${a.title}</td><td>${a.module}</td><td>${names[a.assigneeId]||"Unassigned"}</td><td>${a.status}</td><td>${a.priority}</td><td>${a.dueDate||""}</td></tr>`).join("");fs.writeFileSync(out,`<!doctype html><meta charset="utf-8"><title>OCR Studio Collaboration Report</title><style>body{font-family:Arial;margin:40px}table{border-collapse:collapse;width:100%}th,td{border:1px solid #ccc;padding:8px;text-align:left}</style><h1>Collaboration Report</h1><p>Generated ${now()}</p><p>${d.contributors.length} contributors · ${d.assignments.length} assignments · ${d.comments.length} comments</p><table><thead><tr><th>Assignment</th><th>Module</th><th>Assignee</th><th>Status</th><th>Priority</th><th>Due</th></tr></thead><tbody>${rows}</tbody></table>`,`utf8`);return{success:true,filePath:out};});
 ipcMain.handle("collab:openFile",async(_,p)=>shell.openPath(p));
}
