import fs from "fs";
import path from "path";
import crypto from "crypto";

const now=()=>new Date().toISOString();
const read=(f,d)=>{try{return fs.existsSync(f)?JSON.parse(fs.readFileSync(f,"utf8")):d}catch{return d}};
const write=(f,v)=>{fs.mkdirSync(path.dirname(f),{recursive:true});fs.writeFileSync(f,JSON.stringify(v,null,2),"utf8")};
const editionIndex=(ws)=>path.join(ws,".ocr-studio","editions","editions.json");
function edition(ws,id){const x=read(editionIndex(ws),{editions:[]}).editions||[];return x.find(e=>e.id===id)||null}
function dir(ws,e){return path.join(ws,".ocr-studio","editions",e.folderName)}
const files=(ws,e)=>({structure:path.join(dir(ws,e),"structure.json"),apparatus:path.join(dir(ws,e),"apparatus.json"),commentary:path.join(dir(ws,e),"commentary.json"),footnotes:path.join(dir(ws,e),"footnotes.json"),decisions:path.join(dir(ws,e),"editorial-decisions.json")});
function normalizeStructure(data){return {books:Array.isArray(data?.books)?data.books:[]}}
function workspace(ws,id){const e=edition(ws,id);if(!e)return null;const f=files(ws,e);return {edition:e,structure:normalizeStructure(read(f.structure,{books:[]})),apparatus:read(f.apparatus,{entries:[]}),commentary:read(f.commentary,{entries:[]}),footnotes:read(f.footnotes,{entries:[]}),decisions:read(f.decisions,{entries:[]})}}
function saveStructure(ws,e,s){write(files(ws,e).structure,normalizeStructure(s))}
function updateStats(ws,e,w){const idx=read(editionIndex(ws),{version:1,editions:[]});const verses=w.structure.books.flatMap(b=>b.chapters||[]).flatMap(c=>c.verses||[]);const target=idx.editions.find(x=>x.id===e.id);if(target){target.stats={...(target.stats||{}),books:w.structure.books.length,chapters:w.structure.books.reduce((n,b)=>n+(b.chapters||[]).length,0),verses:verses.length,variants:(w.apparatus.entries||[]).length,decisions:(w.decisions.entries||[]).length,footnotes:(w.footnotes.entries||[]).length,commentary:(w.commentary.entries||[]).length};target.updatedAt=now();write(editionIndex(ws),idx)}}
function locate(structure,bookId,chapterId,verseId){const book=structure.books.find(x=>x.id===bookId);const chapter=book?.chapters?.find(x=>x.id===chapterId);const verse=chapter?.verses?.find(x=>x.id===verseId);return{book,chapter,verse}}
function addBook(ws,id,input){const w=workspace(ws,id);if(!w)return{success:false,message:"Edition not found."};w.structure.books.push({id:crypto.randomUUID(),title:String(input?.title||"Untitled book"),number:Number(input?.number||w.structure.books.length+1),description:String(input?.description||""),chapters:[]});saveStructure(ws,w.edition,w.structure);updateStats(ws,w.edition,w);return{success:true,message:"Book added.",workspace:workspace(ws,id)}}
function addChapter(ws,id,input){const w=workspace(ws,id);if(!w)return{success:false,message:"Edition not found."};const book=w.structure.books.find(x=>x.id===input?.bookId);if(!book)return{success:false,message:"Book not found."};book.chapters??=[];book.chapters.push({id:crypto.randomUUID(),title:String(input?.title||"Untitled chapter"),number:Number(input?.number||book.chapters.length+1),verses:[]});saveStructure(ws,w.edition,w.structure);updateStats(ws,w.edition,w);return{success:true,message:"Chapter added.",workspace:workspace(ws,id)}}
function saveVerse(ws,id,input){const w=workspace(ws,id);if(!w)return{success:false,message:"Edition not found."};const {chapter,verse}=locate(w.structure,input?.bookId,input?.chapterId,input?.verseId);if(!chapter)return{success:false,message:"Chapter not found."};chapter.verses??=[];const payload={number:String(input?.number||chapter.verses.length+1),title:String(input?.title||""),criticalText:String(input?.criticalText||""),languages:input?.languages&&typeof input.languages==="object"?input.languages:{},status:String(input?.status||"Draft"),updatedAt:now()};if(verse)Object.assign(verse,payload);else chapter.verses.push({id:crypto.randomUUID(),createdAt:now(),...payload});saveStructure(ws,w.edition,w.structure);updateStats(ws,w.edition,w);return{success:true,message:verse?"Verse saved.":"Verse created.",workspace:workspace(ws,id)}}
function deleteVerse(ws,id,input){const w=workspace(ws,id);if(!w)return{success:false,message:"Edition not found."};const {chapter}=locate(w.structure,input?.bookId,input?.chapterId);if(!chapter)return{success:false,message:"Chapter not found."};chapter.verses=(chapter.verses||[]).filter(v=>v.id!==input?.verseId);for(const key of ["apparatus","commentary","footnotes","decisions"]){w[key].entries=(w[key].entries||[]).filter(x=>x.verseId!==input?.verseId);write(files(ws,w.edition)[key],w[key])}saveStructure(ws,w.edition,w.structure);updateStats(ws,w.edition,w);return{success:true,message:"Verse deleted.",workspace:workspace(ws,id)}}
function saveEntry(kind,ws,id,input){const w=workspace(ws,id);if(!w)return{success:false,message:"Edition not found."};const bucket=w[kind];const existing=(bucket.entries||[]).find(x=>x.id===input?.entryId);const payload={verseId:String(input?.verseId||""),label:String(input?.label||""),content:String(input?.content||""),witnesses:Array.isArray(input?.witnesses)?input.witnesses:[],reading:String(input?.reading||""),reason:String(input?.reason||""),confidence:Number(input?.confidence||0),editor:String(input?.editor||""),updatedAt:now(),...(kind==="decisions"?{status:String(input?.status||existing?.status||"Proposed")}:{})};let saved;if(existing){Object.assign(existing,payload);saved=existing}else{saved={id:crypto.randomUUID(),createdAt:now(),...payload};bucket.entries.push(saved)}write(files(ws,w.edition)[kind],bucket);if(kind==="decisions"){const rf=path.join(dir(ws,w.edition),"editorial-decision-revisions.json");const revisions=read(rf,{entries:[]});revisions.entries??=[];revisions.entries.unshift({id:crypto.randomUUID(),decisionId:saved.id,verseId:saved.verseId,action:existing?"Decision edited":"Decision created",actor:saved.editor||"Unknown editor",note:"",snapshot:{label:saved.label,content:saved.content,reading:saved.reading,reason:saved.reason,confidence:saved.confidence,editor:saved.editor,status:saved.status,witnesses:saved.witnesses},createdAt:now()});write(rf,revisions)}updateStats(ws,w.edition,w);return{success:true,message:`${kind[0].toUpperCase()+kind.slice(1)} entry saved.`,workspace:workspace(ws,id)}}
function deleteEntry(kind,ws,id,input){const w=workspace(ws,id);if(!w)return{success:false,message:"Edition not found."};w[kind].entries=(w[kind].entries||[]).filter(x=>x.id!==input?.entryId);write(files(ws,w.edition)[kind],w[kind]);updateStats(ws,w.edition,w);return{success:true,message:"Entry deleted.",workspace:workspace(ws,id)}}
export function registerCriticalTextIpc({ipcMain}){
 ipcMain.handle("criticalText:get",async(_e,d)=>{const w=workspace(String(d?.workspacePath||""),String(d?.editionId||""));return w?{success:true,message:"Critical edition loaded.",workspace:w}:{success:false,message:"Edition not found."}});
 ipcMain.handle("criticalText:addBook",async(_e,d)=>addBook(String(d?.workspacePath||""),String(d?.editionId||""),d));
 ipcMain.handle("criticalText:addChapter",async(_e,d)=>addChapter(String(d?.workspacePath||""),String(d?.editionId||""),d));
 ipcMain.handle("criticalText:saveVerse",async(_e,d)=>saveVerse(String(d?.workspacePath||""),String(d?.editionId||""),d));
 ipcMain.handle("criticalText:deleteVerse",async(_e,d)=>deleteVerse(String(d?.workspacePath||""),String(d?.editionId||""),d));
 for(const kind of ["apparatus","commentary","footnotes","decisions"]){ipcMain.handle(`criticalText:save:${kind}`,async(_e,d)=>saveEntry(kind,String(d?.workspacePath||""),String(d?.editionId||""),d));ipcMain.handle(`criticalText:delete:${kind}`,async(_e,d)=>deleteEntry(kind,String(d?.workspacePath||""),String(d?.editionId||""),d));}
}
