import fs from 'fs';
import path from 'path';
import crypto from 'crypto';

const now=()=>new Date().toISOString();
const read=(f,d)=>{try{return fs.existsSync(f)?JSON.parse(fs.readFileSync(f,'utf8')):d}catch{return d}};
const write=(f,v)=>{fs.mkdirSync(path.dirname(f),{recursive:true});fs.writeFileSync(f,JSON.stringify(v,null,2),'utf8')};
const editionsFile=ws=>path.join(ws,'.ocr-studio','editions','editions.json');
const comparisonRoot=ws=>path.join(ws,'.ocr-studio','scholarly-library','comparisons');
const editionDir=(ws,e)=>path.join(ws,'.ocr-studio','editions',e.folderName);
const listEditions=ws=>read(editionsFile(ws),{editions:[]}).editions||[];
const normalize=s=>String(s||'').normalize('NFKC').replace(/\s+/g,' ').trim();
const tokens=s=>new Set(normalize(s).toLowerCase().split(/[^\p{L}\p{N}]+/u).filter(Boolean));
const similarity=(a,b)=>{const A=tokens(a),B=tokens(b);if(!A.size&&!B.size)return 100;if(!A.size||!B.size)return 0;let n=0;for(const x of A)if(B.has(x))n++;return Math.round((2*n/(A.size+B.size))*100)};
const structure=(ws,e)=>read(path.join(editionDir(ws,e),'structure.json'),{books:[]});
const flatten=(ws,e)=>{const rows=[];for(const b of structure(ws,e).books||[])for(const c of b.chapters||[])for(const v of c.verses||[])rows.push({key:`${b.number||0}.${c.number||0}.${v.number||0}`,bookNumber:b.number||0,bookTitle:b.title||`Book ${b.number}`,chapterNumber:c.number||0,chapterTitle:c.title||`Chapter ${c.number}`,verseNumber:v.number||0,verseId:v.id,criticalText:normalize(v.criticalText),languages:v.languages||{},status:v.status||'Draft'});return rows};
const apparatus=(ws,e)=>read(path.join(editionDir(ws,e),'apparatus.json'),{items:[]}).items||[];
const decisions=(ws,e)=>read(path.join(editionDir(ws,e),'editorial-decisions.json'),{items:[]}).items||[];
function catalog(ws){return{success:true,message:'Comparison catalog loaded.',editions:listEditions(ws).map(e=>({id:e.id,title:e.title,subtitle:e.subtitle||'',version:e.version,status:e.status,languages:e.languages||[],tradition:e.tradition||'',stats:e.stats||{}}))}}
function compare(ws,editionIds){const chosen=listEditions(ws).filter(e=>editionIds.includes(e.id));if(chosen.length<2)return{success:false,message:'Select at least two scholarly editions.'};const maps=chosen.map(e=>({edition:e,rows:flatten(ws,e),apparatus:apparatus(ws,e),decisions:decisions(ws,e)}));const keys=[...new Set(maps.flatMap(x=>x.rows.map(r=>r.key)))].sort((a,b)=>a.localeCompare(b,undefined,{numeric:true}));const rows=keys.map(key=>{const cells=maps.map(m=>{const row=m.rows.find(r=>r.key===key);return{editionId:m.edition.id,editionTitle:m.edition.title,present:Boolean(row),...(row||{criticalText:'',languages:{},status:'Missing'})}});const present=cells.filter(c=>c.present);const base=present[0]?.criticalText||'';const scores=present.slice(1).map(c=>similarity(base,c.criticalText));const agreement=scores.length?Math.round(scores.reduce((a,b)=>a+b,0)/scores.length):present.length===1?0:100;const distinct=[...new Set(present.map(c=>normalize(c.criticalText)).filter(Boolean))];return{key,bookNumber:cells.find(c=>c.present)?.bookNumber||0,chapterNumber:cells.find(c=>c.present)?.chapterNumber||0,verseNumber:cells.find(c=>c.present)?.verseNumber||0,cells,agreement,classification:present.length<chosen.length?'Missing witness':distinct.length<=1?'Agreement':agreement>=70?'Minor variation':'Substantive variation'}});
 const counts={agreement:rows.filter(r=>r.classification==='Agreement').length,minor:rows.filter(r=>r.classification==='Minor variation').length,substantive:rows.filter(r=>r.classification==='Substantive variation').length,missing:rows.filter(r=>r.classification==='Missing witness').length};
 const languageSet=[...new Set(maps.flatMap(m=>m.rows.flatMap(r=>Object.keys(r.languages||{}))))];
 const coverage=maps.map(m=>({editionId:m.edition.id,title:m.edition.title,verses:m.rows.length,languages:Object.fromEntries(languageSet.map(l=>[l,m.rows.filter(r=>normalize(r.languages?.[l])).length])) ,apparatus:m.apparatus.length,decisions:m.decisions.length}));
 const report={id:crypto.randomUUID(),createdAt:now(),editionIds,editions:chosen.map(e=>({id:e.id,title:e.title,version:e.version,status:e.status})),summary:{totalAlignedRows:rows.length,...counts,averageAgreement:rows.length?Math.round(rows.reduce((a,r)=>a+r.agreement,0)/rows.length):0},coverage,rows};
 return{success:true,message:`Compared ${chosen.length} editions across ${rows.length} aligned verse location(s).`,report};}
function saveComparison(ws,report,name){const id=report?.id||crypto.randomUUID(),file=path.join(comparisonRoot(ws),`${id}.json`);const payload={...report,id,name:String(name||'Untitled comparison').trim(),updatedAt:now()};write(file,payload);return{success:true,message:'Comparison saved.',comparison:payload,filePath:file}}
function history(ws){const root=comparisonRoot(ws);if(!fs.existsSync(root))return{success:true,message:'No saved comparisons yet.',items:[]};const items=fs.readdirSync(root).filter(x=>x.endsWith('.json')).map(x=>read(path.join(root,x),null)).filter(Boolean).sort((a,b)=>String(b.updatedAt||b.createdAt).localeCompare(String(a.updatedAt||a.createdAt))).map(x=>({id:x.id,name:x.name,createdAt:x.createdAt,updatedAt:x.updatedAt,editions:x.editions,summary:x.summary}));return{success:true,message:`Loaded ${items.length} saved comparison(s).`,items}}
function getSaved(ws,id){const item=read(path.join(comparisonRoot(ws),`${id}.json`),null);return item?{success:true,message:'Comparison loaded.',report:item}:{success:false,message:'Saved comparison not found.'}}
function removeSaved(ws,id){const f=path.join(comparisonRoot(ws),`${id}.json`);if(!fs.existsSync(f))return{success:false,message:'Saved comparison not found.'};fs.unlinkSync(f);return{success:true,message:'Comparison deleted.'}}
function exportHtml(ws,report){const dir=path.join(comparisonRoot(ws),'exports');fs.mkdirSync(dir,{recursive:true});const safe=(report.name||'edition-comparison').replace(/[^a-z0-9_-]+/gi,'-').replace(/^-|-$/g,'').toLowerCase();const f=path.join(dir,`${safe||'edition-comparison'}-${Date.now()}.html`);const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));const headers=report.editions.map(e=>`<th>${esc(e.title)}<small>v${esc(e.version)}</small></th>`).join('');const body=report.rows.map(r=>`<tr><td>${esc(r.key)}<br><small>${esc(r.classification)} · ${r.agreement}%</small></td>${r.cells.map(c=>`<td class="${c.present?'':'missing'}">${c.present?esc(c.criticalText):'Missing'}</td>`).join('')}</tr>`).join('');fs.writeFileSync(f,`<!doctype html><meta charset="utf-8"><title>${esc(report.name||'Edition Comparison')}</title><style>body{font-family:system-ui;margin:32px;color:#29231f}table{border-collapse:collapse;width:100%}th,td{border:1px solid #d8cec4;padding:10px;vertical-align:top}th{background:#f5eee8}.missing{color:#9b2c2c;background:#fff4f4}small{display:block;color:#725f51;margin-top:4px}</style><h1>${esc(report.name||'Edition Comparison')}</h1><p>${report.editions.map(e=>esc(e.title)).join(' · ')}</p><p>Aligned verses: ${report.summary.totalAlignedRows} · Average agreement: ${report.summary.averageAgreement}%</p><table><thead><tr><th>Location</th>${headers}</tr></thead><tbody>${body}</tbody></table>`,`utf8`);return{success:true,message:'HTML comparison exported.',filePath:f}}
export function registerEditionComparisonIpc({ipcMain,shell}){
 ipcMain.handle('editionComparison:catalog',async(_e,d)=>catalog(String(d?.workspacePath||'')));
 ipcMain.handle('editionComparison:compare',async(_e,d)=>compare(String(d?.workspacePath||''),Array.isArray(d?.editionIds)?d.editionIds:[]));
 ipcMain.handle('editionComparison:save',async(_e,d)=>saveComparison(String(d?.workspacePath||''),d?.report,d?.name));
 ipcMain.handle('editionComparison:history',async(_e,d)=>history(String(d?.workspacePath||'')));
 ipcMain.handle('editionComparison:getSaved',async(_e,d)=>getSaved(String(d?.workspacePath||''),String(d?.id||'')));
 ipcMain.handle('editionComparison:delete',async(_e,d)=>removeSaved(String(d?.workspacePath||''),String(d?.id||'')));
 ipcMain.handle('editionComparison:export',async(_e,d)=>exportHtml(String(d?.workspacePath||''),d?.report||{}));
 ipcMain.handle('editionComparison:open',async(_e,d)=>{const err=await shell.openPath(String(d?.filePath||''));return{success:!err,message:err||'Opened comparison export.'}});
}
