import fs from "fs";
import path from "path";
import crypto from "crypto";

const uid=(p)=>`${p}-${Date.now()}-${crypto.randomBytes(3).toString("hex")}`;
const now=()=>new Date().toISOString();
const dir=(projectPath)=>path.join(projectPath,".ocr-studio","knowledge");
const file=(projectPath,name)=>path.join(dir(projectPath),name);
const read=(p,f)=>{try{return JSON.parse(fs.readFileSync(p,"utf8"));}catch{return f;}};
const write=(p,v)=>{fs.mkdirSync(path.dirname(p),{recursive:true});fs.writeFileSync(p,JSON.stringify(v,null,2),"utf8");};
const clean=(v)=>String(v??"").normalize("NFKC").replace(/\s+/g," ").trim();
const list=(projectPath,name)=>read(file(projectPath,name),[]);
const saveList=(projectPath,name,value)=>write(file(projectPath,name),value);
function ensure(projectPath){fs.mkdirSync(path.join(dir(projectPath),"exports"),{recursive:true});for(const n of ["entities.json","relationships.json","timelines.json","maps.json","graph-layouts.json"]){if(!fs.existsSync(file(projectPath,n)))write(file(projectPath,n),[]);}const legacy=read(path.join(projectPath,".ocr-studio","knowledge-graph","graph.json"),null);const entities=list(projectPath,"entities.json");if(!entities.length&&legacy?.entities?.length){saveList(projectPath,"entities.json",legacy.entities.map(e=>({...e,canonicalName:e.name,alternateNames:e.aliases||[],editorialStatus:e.status||"Suggested"})));saveList(projectPath,"relationships.json",(legacy.relationships||[]).map(r=>({...r,approvalStatus:r.status||"Suggested"})));}}
function data(projectPath){ensure(projectPath);return{entities:list(projectPath,"entities.json"),relationships:list(projectPath,"relationships.json"),timelines:list(projectPath,"timelines.json"),maps:list(projectPath,"maps.json"),views:list(projectPath,"graph-layouts.json")};}
function metrics(d){const active=d.relationships.filter(r=>r.approvalStatus!=="Rejected");const degree=new Map();active.forEach(r=>{degree.set(r.sourceId,(degree.get(r.sourceId)||0)+1);degree.set(r.targetId,(degree.get(r.targetId)||0)+1)});const components=(()=>{const adj=new Map();d.entities.forEach(e=>adj.set(e.id,new Set()));active.forEach(r=>{adj.get(r.sourceId)?.add(r.targetId);adj.get(r.targetId)?.add(r.sourceId)});let count=0;const seen=new Set();for(const e of d.entities){if(seen.has(e.id))continue;count++;const stack=[e.id];while(stack.length){const x=stack.pop();if(!x||seen.has(x))continue;seen.add(x);for(const y of adj.get(x)||[])stack.push(y)}}return count})();const possible=d.entities.length>1?d.entities.length*(d.entities.length-1):1;return{entities:d.entities.length,relationships:active.length,timelineEvents:d.timelines.length,mappedPlaces:d.maps.length,reviewed:d.entities.filter(e=>e.editorialStatus==="Verified").length,pending:d.entities.filter(e=>e.editorialStatus==="Suggested").length,unlinked:d.entities.filter(e=>!degree.has(e.id)).length,components,density:Number((active.length/possible).toFixed(4)),mostReferenced:[...degree.entries()].sort((a,b)=>b[1]-a[1]).slice(0,8).map(([id,count])=>({entity:d.entities.find(e=>e.id===id),count}))};}
function esc(v){return clean(v).replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"}[m]));}
function exportContent(format,d){if(format==="json")return JSON.stringify(d,null,2);if(format==="csv")return `kind,id,name_or_type,source,target,status\n${d.entities.map(e=>`entity,${e.id},"${clean(e.canonicalName||e.name).replaceAll('"','""')}",,,${e.editorialStatus||""}`).join("\n")}\n${d.relationships.map(r=>`relationship,${r.id},"${clean(r.type).replaceAll('"','""')}",${r.sourceId},${r.targetId},${r.approvalStatus||""}`).join("\n")}`;if(format==="graphml"){return `<?xml version="1.0" encoding="UTF-8"?><graphml xmlns="http://graphml.graphdrawing.org/xmlns"><graph edgedefault="directed">${d.entities.map(e=>`<node id="${esc(e.id)}"><data key="label">${esc(e.canonicalName||e.name)}</data><data key="type">${esc(e.type)}</data></node>`).join("")}${d.relationships.map(r=>`<edge id="${esc(r.id)}" source="${esc(r.sourceId)}" target="${esc(r.targetId)}"><data key="label">${esc(r.type)}</data></edge>`).join("")}</graph></graphml>`;}if(format==="rdf")return `<?xml version="1.0"?><rdf:RDF xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#" xmlns:kg="urn:ocr-studio:kg:">${d.entities.map(e=>`<rdf:Description rdf:about="urn:entity:${esc(e.id)}"><kg:label>${esc(e.canonicalName||e.name)}</kg:label><kg:type>${esc(e.type)}</kg:type></rdf:Description>`).join("")}</rdf:RDF>`;return `<!doctype html><meta charset="utf-8"><title>Entity Intelligence Report</title><style>body{font-family:Arial;max-width:1100px;margin:40px auto}table{border-collapse:collapse;width:100%}td,th{border:1px solid #ddd;padding:8px}</style><h1>Entity Intelligence Report</h1><p>${d.entities.length} entities · ${d.relationships.length} relationships</p><h2>Entities</h2><table><tr><th>Name</th><th>Type</th><th>Status</th><th>Description</th></tr>${d.entities.map(e=>`<tr><td>${esc(e.canonicalName||e.name)}</td><td>${esc(e.type)}</td><td>${esc(e.editorialStatus)}</td><td>${esc(e.description)}</td></tr>`).join("")}</table>`;}
export function registerEntityIntelligenceIpc({ipcMain,shell,getProjects}){
 ipcMain.handle("entityIntel:getWorkspace",async()=>({success:true,projects:((await getProjects())||[]).map(p=>({projectPath:p.projectPath,projectName:p.name}))}));
 ipcMain.handle("entityIntel:getProject",async(_,{projectPath})=>{const d=data(projectPath);return{success:true,...d,metrics:metrics(d)}});
 ipcMain.handle("entityIntel:saveEntity",async(_,x)=>{const a=list(x.projectPath,"entities.json");const value={id:x.id||uid("entity"),canonicalName:clean(x.canonicalName),name:clean(x.canonicalName),alternateNames:(x.alternateNames||[]).map(clean).filter(Boolean),sanskritForm:clean(x.sanskritForm),transliteration:clean(x.transliteration),translations:x.translations||{},description:clean(x.description),type:clean(x.type)||"Concept",period:clean(x.period),externalReferences:x.externalReferences||[],editorialNotes:clean(x.editorialNotes),editorialStatus:x.editorialStatus||"Verified",evidence:x.evidence||[],latitude:x.latitude===""?null:Number(x.latitude),longitude:x.longitude===""?null:Number(x.longitude),updatedAt:now(),createdAt:x.createdAt||now()};const i=a.findIndex(e=>e.id===value.id);if(i>=0)a[i]=value;else a.push(value);saveList(x.projectPath,"entities.json",a);return{success:true,message:"Entity saved."};});
 ipcMain.handle("entityIntel:deleteEntity",async(_,{projectPath,id})=>{saveList(projectPath,"entities.json",list(projectPath,"entities.json").filter(e=>e.id!==id));saveList(projectPath,"relationships.json",list(projectPath,"relationships.json").filter(r=>r.sourceId!==id&&r.targetId!==id));return{success:true,message:"Entity deleted."};});
 ipcMain.handle("entityIntel:saveRelationship",async(_,x)=>{const a=list(x.projectPath,"relationships.json");const value={id:x.id||uid("rel"),sourceId:x.sourceId,targetId:x.targetId,type:clean(x.type)||"Related to",confidence:Math.max(0,Math.min(1,Number(x.confidence)||1)),approvalStatus:x.approvalStatus||"Verified",evidence:clean(x.evidence),sourcePassages:clean(x.sourcePassages),notes:clean(x.notes),updatedAt:now(),createdAt:x.createdAt||now()};const i=a.findIndex(r=>r.id===value.id);if(i>=0)a[i]=value;else a.push(value);saveList(x.projectPath,"relationships.json",a);return{success:true,message:"Relationship saved."};});
 ipcMain.handle("entityIntel:deleteRelationship",async(_,{projectPath,id})=>{saveList(projectPath,"relationships.json",list(projectPath,"relationships.json").filter(r=>r.id!==id));return{success:true};});
 ipcMain.handle("entityIntel:saveTimeline",async(_,x)=>{const a=list(x.projectPath,"timelines.json");const v={id:x.id||uid("event"),title:clean(x.title),dateLabel:clean(x.dateLabel),sortOrder:Number(x.sortOrder)||0,entityIds:x.entityIds||[],description:clean(x.description),sourceReference:clean(x.sourceReference),createdAt:x.createdAt||now(),updatedAt:now()};const i=a.findIndex(e=>e.id===v.id);if(i>=0)a[i]=v;else a.push(v);saveList(x.projectPath,"timelines.json",a);return{success:true};});
 ipcMain.handle("entityIntel:saveMap",async(_,x)=>{const a=list(x.projectPath,"maps.json");const v={id:x.id||uid("map"),entityId:x.entityId,label:clean(x.label),latitude:Number(x.latitude),longitude:Number(x.longitude),period:clean(x.period),notes:clean(x.notes),createdAt:x.createdAt||now(),updatedAt:now()};const i=a.findIndex(e=>e.id===v.id);if(i>=0)a[i]=v;else a.push(v);saveList(x.projectPath,"maps.json",a);return{success:true};});
 ipcMain.handle("entityIntel:compare",async(_,{projectPath,entityIds})=>{const d=data(projectPath);const selected=d.entities.filter(e=>entityIds.includes(e.id));return{success:true,entities:selected,sharedRelationships:d.relationships.filter(r=>entityIds.includes(r.sourceId)&&entityIds.includes(r.targetId)),sharedEvents:d.timelines.filter(t=>(t.entityIds||[]).filter(id=>entityIds.includes(id)).length>1),commonTypes:[...new Set(selected.map(e=>e.type))]};});
 ipcMain.handle("entityIntel:saveView",async(_,x)=>{const a=list(x.projectPath,"graph-layouts.json");a.unshift({id:uid("view"),name:clean(x.name)||"Saved view",filters:x.filters||{},positions:x.positions||{},createdAt:now()});saveList(x.projectPath,"graph-layouts.json",a.slice(0,50));return{success:true};});
 ipcMain.handle("entityIntel:export",async(_,{projectPath,format})=>{const d=data(projectPath);const ext={html:"html",json:"json",csv:"csv",graphml:"graphml",rdf:"rdf"}[format]||"json";const out=path.join(dir(projectPath),"exports",`entity-intelligence-${Date.now()}.${ext}`);fs.writeFileSync(out,exportContent(format,d),"utf8");return{success:true,filePath:out,message:`${format.toUpperCase()} export created.`};});
 ipcMain.handle("entityIntel:openFile",async(_,p)=>shell.openPath(p));
}
