import fs from "fs";
import path from "path";
import crypto from "crypto";

const now=()=>new Date().toISOString();
const uid=(p)=>`${p}-${Date.now()}-${crypto.randomBytes(3).toString("hex")}`;
const root=(projectPath)=>path.join(projectPath,".ocr-studio","iiif");
const file=(projectPath,name)=>path.join(root(projectPath),name);
const read=(p,f)=>{try{return JSON.parse(fs.readFileSync(p,"utf8"));}catch{return f;}};
const write=(p,v)=>{fs.mkdirSync(path.dirname(p),{recursive:true});fs.writeFileSync(p,JSON.stringify(v,null,2),"utf8");};
const clean=(v)=>String(v??"").trim();
function ensure(projectPath){fs.mkdirSync(path.join(root(projectPath),"exports"),{recursive:true});for(const n of ["manifests.json","canvases.json","annotations.json","viewer-settings.json"]){if(!fs.existsSync(file(projectPath,n)))write(file(projectPath,n),n==="viewer-settings.json"?{}:[]);}}
function data(projectPath){ensure(projectPath);return{manifests:read(file(projectPath,"manifests.json"),[]),canvases:read(file(projectPath,"canvases.json"),[]),annotations:read(file(projectPath,"annotations.json"),[]),settings:read(file(projectPath,"viewer-settings.json"),{})};}
function save(projectPath,name,value){write(file(projectPath,name),value);}
function manifestJson(projectPath,manifestId){const d=data(projectPath);const m=d.manifests.find(x=>x.id===manifestId);if(!m)throw new Error("Manifest not found.");const canvases=d.canvases.filter(x=>x.manifestId===manifestId).sort((a,b)=>a.order-b.order);return{"@context":"http://iiif.io/api/presentation/3/context.json",id:`urn:ocr-studio:manifest:${m.id}`,type:"Manifest",label:{en:[m.title]},metadata:[{label:{en:["Repository"]},value:{en:[m.repository||""]}},{label:{en:["Shelfmark"]},value:{en:[m.shelfmark||""]}}],items:canvases.map(c=>({id:`urn:ocr-studio:canvas:${c.id}`,type:"Canvas",label:{en:[c.label]},height:c.height||1200,width:c.width||900,items:[{id:`urn:ocr-studio:page:${c.id}`,type:"AnnotationPage",items:[{id:`urn:ocr-studio:image:${c.id}`,type:"Annotation",motivation:"painting",body:{id:c.imageUrl,type:"Image",format:c.mimeType||"image/jpeg",height:c.height||1200,width:c.width||900},target:`urn:ocr-studio:canvas:${c.id}`}]}],annotations:[{id:`urn:ocr-studio:annotations:${c.id}`,type:"AnnotationPage",items:d.annotations.filter(a=>a.canvasId===c.id).map(a=>({id:`urn:ocr-studio:annotation:${a.id}`,type:"Annotation",motivation:a.motivation||"commenting",body:{type:"TextualBody",value:a.text||"",format:"text/plain",language:a.language||"en"},target:{source:`urn:ocr-studio:canvas:${c.id}`,selector:{type:"FragmentSelector",conformsTo:"http://www.w3.org/TR/media-frags/",value:`xywh=${a.x},${a.y},${a.width},${a.height}`}}}))}]}))};}
export function registerIiifManuscriptIpc({ipcMain,shell,getProjects}){
 ipcMain.handle("iiif:getWorkspace",async()=>({success:true,projects:((await getProjects())||[]).map(p=>({projectPath:p.projectPath,projectName:p.name}))}));
 ipcMain.handle("iiif:getProject",async(_,{projectPath})=>({success:true,...data(projectPath)}));
 ipcMain.handle("iiif:saveManifest",async(_,x)=>{const d=data(x.projectPath);const v={id:x.id||uid("manifest"),title:clean(x.title)||"Untitled manuscript",repository:clean(x.repository),shelfmark:clean(x.shelfmark),summary:clean(x.summary),rights:clean(x.rights),provider:clean(x.provider),sourceManifestUrl:clean(x.sourceManifestUrl),createdAt:x.createdAt||now(),updatedAt:now()};const i=d.manifests.findIndex(m=>m.id===v.id);if(i>=0)d.manifests[i]=v;else d.manifests.push(v);save(x.projectPath,"manifests.json",d.manifests);return{success:true,manifest:v};});
 ipcMain.handle("iiif:deleteManifest",async(_,{projectPath,id})=>{const d=data(projectPath);const canvasIds=d.canvases.filter(c=>c.manifestId===id).map(c=>c.id);save(projectPath,"manifests.json",d.manifests.filter(m=>m.id!==id));save(projectPath,"canvases.json",d.canvases.filter(c=>c.manifestId!==id));save(projectPath,"annotations.json",d.annotations.filter(a=>!canvasIds.includes(a.canvasId)));return{success:true};});
 ipcMain.handle("iiif:saveCanvas",async(_,x)=>{const d=data(x.projectPath);const siblings=d.canvases.filter(c=>c.manifestId===x.manifestId);const v={id:x.id||uid("canvas"),manifestId:x.manifestId,label:clean(x.label)||`Folio ${siblings.length+1}`,imageUrl:clean(x.imageUrl),thumbnailUrl:clean(x.thumbnailUrl),mimeType:x.mimeType||"image/jpeg",width:Number(x.width)||900,height:Number(x.height)||1200,order:Number.isFinite(Number(x.order))?Number(x.order):siblings.length,transcription:clean(x.transcription),ocrText:clean(x.ocrText),createdAt:x.createdAt||now(),updatedAt:now()};const i=d.canvases.findIndex(c=>c.id===v.id);if(i>=0)d.canvases[i]=v;else d.canvases.push(v);save(x.projectPath,"canvases.json",d.canvases);return{success:true,canvas:v};});
 ipcMain.handle("iiif:deleteCanvas",async(_,{projectPath,id})=>{const d=data(projectPath);save(projectPath,"canvases.json",d.canvases.filter(c=>c.id!==id));save(projectPath,"annotations.json",d.annotations.filter(a=>a.canvasId!==id));return{success:true};});
 ipcMain.handle("iiif:saveAnnotation",async(_,x)=>{const d=data(x.projectPath);const v={id:x.id||uid("annotation"),canvasId:x.canvasId,type:x.type||"Region",motivation:x.motivation||"commenting",text:clean(x.text),language:x.language||"en",x:Math.max(0,Number(x.x)||0),y:Math.max(0,Number(x.y)||0),width:Math.max(1,Number(x.width)||100),height:Math.max(1,Number(x.height)||50),sourceReference:clean(x.sourceReference),status:x.status||"Draft",createdAt:x.createdAt||now(),updatedAt:now()};const i=d.annotations.findIndex(a=>a.id===v.id);if(i>=0)d.annotations[i]=v;else d.annotations.push(v);save(x.projectPath,"annotations.json",d.annotations);return{success:true,annotation:v};});
 ipcMain.handle("iiif:deleteAnnotation",async(_,{projectPath,id})=>{const d=data(projectPath);save(projectPath,"annotations.json",d.annotations.filter(a=>a.id!==id));return{success:true};});
 ipcMain.handle("iiif:saveSettings",async(_,{projectPath,settings})=>{save(projectPath,"viewer-settings.json",settings||{});return{success:true};});
 ipcMain.handle("iiif:exportManifest",async(_,{projectPath,manifestId})=>{ensure(projectPath);const json=manifestJson(projectPath,manifestId);const out=path.join(root(projectPath),"exports",`iiif-manifest-${manifestId}.json`);write(out,json);return{success:true,filePath:out};});
 ipcMain.handle("iiif:exportAnnotations",async(_,{projectPath,manifestId})=>{const d=data(projectPath);const canvasIds=d.canvases.filter(c=>c.manifestId===manifestId).map(c=>c.id);const out=path.join(root(projectPath),"exports",`web-annotations-${manifestId}.json`);write(out,{"@context":"http://www.w3.org/ns/anno.jsonld",type:"AnnotationCollection",items:d.annotations.filter(a=>canvasIds.includes(a.canvasId))});return{success:true,filePath:out};});
 ipcMain.handle("iiif:openFile",async(_,p)=>shell.openPath(p));
}
