import fs from "fs";
import path from "path";
import crypto from "crypto";

const now=()=>new Date().toISOString();
const id=(p)=>`${p}-${Date.now()}-${crypto.randomBytes(3).toString("hex")}`;
const dir=(projectPath)=>path.join(projectPath,".ocr-studio","repository");
const file=(projectPath,name)=>path.join(dir(projectPath),name);
function ensure(projectPath){fs.mkdirSync(path.join(dir(projectPath),"exports"),{recursive:true});for(const n of ["deposits.json","publications.json","identifiers.json","metadata-profiles.json","access-policies.json","preservation-events.json"]){if(!fs.existsSync(file(projectPath,n)))fs.writeFileSync(file(projectPath,n),"[]","utf8");}}
function read(projectPath,name){ensure(projectPath);try{return JSON.parse(fs.readFileSync(file(projectPath,name),"utf8"));}catch{return [];}}
function write(projectPath,name,data){ensure(projectPath);fs.writeFileSync(file(projectPath,name),JSON.stringify(data,null,2),"utf8");return data;}
function upsert(projectPath,name,record,prefix){const rows=read(projectPath,name);const value={...record,id:record.id||id(prefix),updatedAt:now(),createdAt:record.createdAt||now()};const i=rows.findIndex(x=>x.id===value.id);if(i>=0)rows[i]=value;else rows.unshift(value);write(projectPath,name,rows);return value;}
function remove(projectPath,name,recordId){const rows=read(projectPath,name).filter(x=>x.id!==recordId);write(projectPath,name,rows);return rows;}
function checksum(target){const hash=crypto.createHash("sha256");hash.update(fs.readFileSync(target));return hash.digest("hex");}
function walk(root){if(!fs.existsSync(root))return[];const out=[];for(const e of fs.readdirSync(root,{withFileTypes:true})){const p=path.join(root,e.name);if(e.isDirectory()&&!p.includes(`${path.sep}.ocr-studio${path.sep}repository`))out.push(...walk(p));else if(e.isFile())out.push(p);}return out;}
function metrics(projectPath){const publications=read(projectPath,"publications.json"),deposits=read(projectPath,"deposits.json"),events=read(projectPath,"preservation-events.json");return{publications:publications.length,published:publications.filter(x=>x.status==="Published").length,deposits:deposits.length,validated:deposits.filter(x=>x.validationStatus==="Valid").length,preservationEvents:events.length,publicAccess:publications.filter(x=>x.access==="Public").length};}
function validate(record){const issues=[];for(const k of ["title","creator","publisher","license","access"]){if(!String(record?.[k]||"").trim())issues.push(`Missing ${k}`);}if(record?.status==="Published"&&!record?.version)issues.push("Published records require a version");return{valid:issues.length===0,issues,checkedAt:now()};}
function xmlEscape(v=""){return String(v).replace(/[<>&'\"]/g,c=>({"<":"&lt;",">":"&gt;","&":"&amp;","'":"&apos;",'"':"&quot;"}[c]));}
function exportMetadata(projectPath,publication,format){ensure(projectPath);const out=path.join(dir(projectPath),"exports");const base=(publication.title||"publication").replace(/[^a-z0-9]+/gi,"-").replace(/^-|-$/g,"").toLowerCase()||"publication";let content="",ext="json";
 if(format==="dublin-core"){ext="xml";content=`<?xml version="1.0" encoding="UTF-8"?><record xmlns:dc="http://purl.org/dc/elements/1.1/"><dc:title>${xmlEscape(publication.title)}</dc:title><dc:creator>${xmlEscape(publication.creator)}</dc:creator><dc:publisher>${xmlEscape(publication.publisher)}</dc:publisher><dc:date>${xmlEscape(publication.publicationDate||now().slice(0,10))}</dc:date><dc:rights>${xmlEscape(publication.license)}</dc:rights><dc:identifier>${xmlEscape(publication.doi||publication.localIdentifier||publication.id)}</dc:identifier><dc:description>${xmlEscape(publication.description)}</dc:description></record>`;}
 else if(format==="datacite"){ext="json";content=JSON.stringify({data:{type:"dois",attributes:{doi:publication.doi||"",titles:[{title:publication.title}],creators:[{name:publication.creator}],publisher:publication.publisher,publicationYear:String((publication.publicationDate||now()).slice(0,4)),types:{resourceTypeGeneral:"Text"},rightsList:[{rights:publication.license}],descriptions:[{description:publication.description||"",descriptionType:"Abstract"}]}}},null,2);}
 else if(format==="oai-dc"){ext="xml";content=`<?xml version="1.0"?><OAI-PMH xmlns="http://www.openarchives.org/OAI/2.0/"><responseDate>${now()}</responseDate><GetRecord><record><header><identifier>${xmlEscape(publication.localIdentifier||publication.id)}</identifier><datestamp>${now().slice(0,10)}</datestamp></header><metadata><oai_dc:dc xmlns:oai_dc="http://www.openarchives.org/OAI/2.0/oai_dc/" xmlns:dc="http://purl.org/dc/elements/1.1/"><dc:title>${xmlEscape(publication.title)}</dc:title><dc:creator>${xmlEscape(publication.creator)}</dc:creator><dc:rights>${xmlEscape(publication.license)}</dc:rights></oai_dc:dc></metadata></record></GetRecord></OAI-PMH>`;}
 else content=JSON.stringify(publication,null,2);
 const target=path.join(out,`${base}-${format}.${ext}`);fs.writeFileSync(target,content,"utf8");return target;}
function createBag(projectPath,publication){ensure(projectPath);const root=path.join(dir(projectPath),"exports",`${(publication.title||"deposit").replace(/[^a-z0-9]+/gi,"-").toLowerCase()}-bag-${Date.now()}`);const data=path.join(root,"data");fs.mkdirSync(data,{recursive:true});const source=projectPath;const files=walk(source).filter(p=>!p.startsWith(dir(projectPath))).slice(0,500);const manifest=[];for(const src of files){const rel=path.relative(source,src);const dst=path.join(data,rel);fs.mkdirSync(path.dirname(dst),{recursive:true});fs.copyFileSync(src,dst);manifest.push(`${checksum(dst)}  data/${rel.replace(/\\/g,"/")}`);}fs.writeFileSync(path.join(root,"bagit.txt"),"BagIt-Version: 0.97\nTag-File-Character-Encoding: UTF-8\n");fs.writeFileSync(path.join(root,"bag-info.txt"),`Source-Organization: ${publication.publisher||"OCR Studio"}\nBagging-Date: ${now().slice(0,10)}\nExternal-Identifier: ${publication.doi||publication.localIdentifier||publication.id}\n`);fs.writeFileSync(path.join(root,"manifest-sha256.txt"),manifest.join("\n"));const event=upsert(projectPath,"preservation-events.json",{publicationId:publication.id,type:"BagIt package created",details:`${manifest.length} files packaged`,outcome:"Success",packagePath:root},"event");return{root,event,fileCount:manifest.length};}
export function registerInstitutionalRepositoryIpc({ipcMain,shell,getProjects}){
 ipcMain.handle("repo:getWorkspace",()=>({success:true,projects:getProjects()}));
 ipcMain.handle("repo:getProject",(_,d)=>({success:true,publications:read(d.projectPath,"publications.json"),deposits:read(d.projectPath,"deposits.json"),identifiers:read(d.projectPath,"identifiers.json"),events:read(d.projectPath,"preservation-events.json"),metrics:metrics(d.projectPath)}));
 ipcMain.handle("repo:savePublication",(_,d)=>({success:true,publication:upsert(d.projectPath,"publications.json",d,"pub")}));
 ipcMain.handle("repo:deletePublication",(_,d)=>({success:true,publications:remove(d.projectPath,"publications.json",d.id)}));
 ipcMain.handle("repo:validatePublication",(_,d)=>({success:true,validation:validate(d)}));
 ipcMain.handle("repo:saveDeposit",(_,d)=>({success:true,deposit:upsert(d.projectPath,"deposits.json",d,"dep")}));
 ipcMain.handle("repo:deleteDeposit",(_,d)=>({success:true,deposits:remove(d.projectPath,"deposits.json",d.id)}));
 ipcMain.handle("repo:saveIdentifier",(_,d)=>({success:true,identifier:upsert(d.projectPath,"identifiers.json",d,"pid")}));
 ipcMain.handle("repo:exportMetadata",(_,d)=>({success:true,filePath:exportMetadata(d.projectPath,d.publication,d.format)}));
 ipcMain.handle("repo:createBag",(_,d)=>({success:true,...createBag(d.projectPath,d.publication)}));
 ipcMain.handle("repo:openFile",(_,p)=>shell.openPath(p));
}
