import fs from 'fs';
import path from 'path';
import crypto from 'crypto';

const now=()=>new Date().toISOString();
const read=(f,d)=>{try{return fs.existsSync(f)?JSON.parse(fs.readFileSync(f,'utf8')):d}catch{return d}};
const write=(f,v)=>{fs.mkdirSync(path.dirname(f),{recursive:true});fs.writeFileSync(f,JSON.stringify(v,null,2),'utf8')};
const root=ws=>path.join(ws,'.ocr-studio','manuscripts');
const files=ws=>({witnesses:path.join(root(ws),'witnesses.json'),groups:path.join(root(ws),'witness-groups.json'),collations:path.join(root(ws),'collations.json'),variants:path.join(root(ws),'variant-index.json')});
const editionsFile=ws=>path.join(ws,'.ocr-studio','editions','editions.json');
const editionDir=(ws,e)=>path.join(ws,'.ocr-studio','editions',e.folderName);
const listEditions=ws=>read(editionsFile(ws),{editions:[]}).editions||[];
const normalize=s=>String(s||'').normalize('NFKC').replace(/\s+/g,' ').trim();
const tokenize=s=>normalize(s).toLowerCase().split(/[^\p{L}\p{N}]+/u).filter(Boolean);
function classify(a,b){a=normalize(a);b=normalize(b);if(!a&&!b)return'Agreement';if(!a||!b)return'Omission';if(a===b)return'Agreement';const A=tokenize(a),B=tokenize(b);if(A.length===B.length&&A.slice().sort().join('|')===B.slice().sort().join('|'))return'Transposition';if(A.length<B.length)return'Addition';if(A.length>B.length)return'Omission';const strip=s=>s.replace(/[\p{P}\p{M}\s]/gu,'').toLowerCase();if(strip(a)===strip(b))return'Orthographic';return A.length===B.length?'Substitution':'Lexical'}
function load(ws){const f=files(ws);return{success:true,message:'Manuscript workspace loaded.',witnesses:read(f.witnesses,{items:[]}).items||[],groups:read(f.groups,{items:[]}).items||[],collations:read(f.collations,{items:[]}).items||[],variants:read(f.variants,{items:[]}).items||[],editions:listEditions(ws).map(e=>({id:e.id,title:e.title,folderName:e.folderName,version:e.version,status:e.status}))}}
function saveWitness(ws,item){const f=files(ws).witnesses,d=read(f,{items:[]});const i={id:item?.id||crypto.randomUUID(),siglum:normalize(item?.siglum),title:normalize(item?.title),repository:normalize(item?.repository),shelfmark:normalize(item?.shelfmark),script:normalize(item?.script),language:normalize(item?.language),material:normalize(item?.material),date:normalize(item?.date),region:normalize(item?.region),provenance:normalize(item?.provenance),condition:normalize(item?.condition),notes:String(item?.notes||''),imagePaths:Array.isArray(item?.imagePaths)?item.imagePaths:[],updatedAt:now(),createdAt:item?.createdAt||now()};if(!i.siglum)return{success:false,message:'Witness siglum is required.'};const idx=d.items.findIndex(x=>x.id===i.id);idx>=0?d.items[idx]=i:d.items.push(i);write(f,d);return{success:true,message:'Witness saved.',witness:i}}
function deleteWitness(ws,id){const f=files(ws).witnesses,d=read(f,{items:[]});d.items=d.items.filter(x=>x.id!==id);write(f,d);const gf=files(ws).groups,g=read(gf,{items:[]});g.items=g.items.map(x=>({...x,witnessIds:(x.witnessIds||[]).filter(w=>w!==id)}));write(gf,g);return{success:true,message:'Witness deleted.'}}
function saveGroup(ws,item){const f=files(ws).groups,d=read(f,{items:[]});const i={id:item?.id||crypto.randomUUID(),name:normalize(item?.name),description:String(item?.description||''),witnessIds:Array.isArray(item?.witnessIds)?item.witnessIds:[],updatedAt:now(),createdAt:item?.createdAt||now()};if(!i.name)return{success:false,message:'Group name is required.'};const idx=d.items.findIndex(x=>x.id===i.id);idx>=0?d.items[idx]=i:d.items.push(i);write(f,d);return{success:true,message:'Witness group saved.',group:i}}
function deleteGroup(ws,id){const f=files(ws).groups,d=read(f,{items:[]});d.items=d.items.filter(x=>x.id!==id);write(f,d);return{success:true,message:'Witness group deleted.'}}
function editionRows(ws,editionId){const e=listEditions(ws).find(x=>x.id===editionId);if(!e)return[];const s=read(path.join(editionDir(ws,e),'structure.json'),{books:[]});const rows=[];for(const b of s.books||[])for(const c of b.chapters||[])for(const v of c.verses||[])rows.push({key:`${b.number||0}.${c.number||0}.${v.number||0}`,bookNumber:b.number||0,chapterNumber:c.number||0,verseNumber:v.number||0,verseId:v.id,criticalText:normalize(v.criticalText),languages:v.languages||{}});return rows}
function buildCollation(ws,payload){const witnessIds=Array.isArray(payload?.witnessIds)?payload.witnessIds:[];const witnesses=read(files(ws).witnesses,{items:[]}).items.filter(w=>witnessIds.includes(w.id));if(!payload?.editionId)return{success:false,message:'Select an edition.'};if(witnesses.length<2)return{success:false,message:'Select at least two manuscript witnesses.'};const baseRows=editionRows(ws,payload.editionId);const manual=payload?.readings||{};const rows=baseRows.map(v=>{const readings=witnesses.map(w=>({witnessId:w.id,siglum:w.siglum,text:normalize(manual?.[v.key]?.[w.id]??(w.id===witnesses[0].id?v.criticalText:''))}));const adopted=normalize(manual?.[v.key]?.adopted||v.criticalText||readings.find(r=>r.text)?.text||'');return{...v,adopted,readings,variants:readings.filter(r=>r.text!==adopted).map(r=>({witnessId:r.witnessId,siglum:r.siglum,reading:r.text,type:classify(adopted,r.text)}))}});const variantCount=rows.reduce((n,r)=>n+r.variants.length,0);return{success:true,message:`Collated ${rows.length} verse location(s) across ${witnesses.length} witnesses.`,collation:{id:payload?.id||crypto.randomUUID(),name:normalize(payload?.name)||'Untitled collation',editionId:payload.editionId,witnessIds,witnesses:witnesses.map(w=>({id:w.id,siglum:w.siglum,title:w.title})),rows,summary:{verseCount:rows.length,witnessCount:witnesses.length,variantCount,agreementCount:rows.filter(r=>r.variants.length===0).length},createdAt:payload?.createdAt||now(),updatedAt:now()}}}
function saveCollation(ws,item){const f=files(ws).collations,d=read(f,{items:[]});const idx=d.items.findIndex(x=>x.id===item.id);idx>=0?d.items[idx]=item:d.items.push(item);write(f,d);const variants=[];for(const c of d.items)for(const r of c.rows||[])for(const v of r.variants||[])variants.push({id:`${c.id}:${r.key}:${v.witnessId}`,collationId:c.id,collationName:c.name,editionId:c.editionId,location:r.key,adopted:r.adopted,...v});write(files(ws).variants,{items:variants,updatedAt:now()});return{success:true,message:'Collation saved.',collation:item}}
function deleteCollation(ws,id){const f=files(ws).collations,d=read(f,{items:[]});d.items=d.items.filter(x=>x.id!==id);write(f,d);return{success:true,message:'Collation deleted.'}}
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function exportCollation(ws,item,format){const dir=path.join(root(ws),'exports');fs.mkdirSync(dir,{recursive:true});const stem=(item.name||'collation').replace(/[^a-z0-9_-]+/gi,'-').replace(/^-|-$/g,'').toLowerCase()||'collation';const stamp=Date.now();let filePath;if(format==='csv'){filePath=path.join(dir,`${stem}-${stamp}.csv`);const lines=['Location,Adopted,Witness,Siglum,Reading,Variant Type'];for(const r of item.rows||[])for(const rd of r.readings||[]){const v=(r.variants||[]).find(x=>x.witnessId===rd.witnessId);lines.push([r.key,r.adopted,rd.witnessId,rd.siglum,rd.text,v?.type||'Agreement'].map(x=>`"${String(x??'').replace(/"/g,'""')}"`).join(','))}fs.writeFileSync(filePath,lines.join('\n'),'utf8')}else if(format==='json'){filePath=path.join(dir,`${stem}-${stamp}.json`);write(filePath,item)}else{filePath=path.join(dir,`${stem}-${stamp}.html`);const headers=(item.witnesses||[]).map(w=>`<th>${esc(w.siglum)}<small>${esc(w.title)}</small></th>`).join('');const body=(item.rows||[]).map(r=>`<tr><td><b>${esc(r.key)}</b><small>Adopted: ${esc(r.adopted)}</small></td>${(r.readings||[]).map(rd=>{const v=(r.variants||[]).find(x=>x.witnessId===rd.witnessId);return`<td class="${v?'variant':''}">${esc(rd.text||'—')}<small>${esc(v?.type||'Agreement')}</small></td>`}).join('')}</tr>`).join('');fs.writeFileSync(filePath,`<!doctype html><meta charset="utf-8"><title>${esc(item.name)}</title><style>body{font-family:system-ui;margin:32px;color:#2d241f}table{border-collapse:collapse;width:100%}th,td{border:1px solid #d8cec4;padding:10px;vertical-align:top}th{background:#f5eee8}.variant{background:#fff7e8}small{display:block;color:#725f51;margin-top:4px}</style><h1>${esc(item.name)}</h1><p>${item.summary?.verseCount||0} verses · ${item.summary?.witnessCount||0} witnesses · ${item.summary?.variantCount||0} variants</p><table><thead><tr><th>Location</th>${headers}</tr></thead><tbody>${body}</tbody></table>`,'utf8')};return{success:true,message:`${format.toUpperCase()} collation exported.`,filePath}}
export function registerManuscriptCollationIpc({ipcMain,shell}){
 ipcMain.handle('manuscripts:get',async(_e,d)=>load(String(d?.workspacePath||'')));
 ipcMain.handle('manuscripts:saveWitness',async(_e,d)=>saveWitness(String(d?.workspacePath||''),d?.witness||{}));
 ipcMain.handle('manuscripts:deleteWitness',async(_e,d)=>deleteWitness(String(d?.workspacePath||''),String(d?.id||'')));
 ipcMain.handle('manuscripts:saveGroup',async(_e,d)=>saveGroup(String(d?.workspacePath||''),d?.group||{}));
 ipcMain.handle('manuscripts:deleteGroup',async(_e,d)=>deleteGroup(String(d?.workspacePath||''),String(d?.id||'')));
 ipcMain.handle('manuscripts:buildCollation',async(_e,d)=>buildCollation(String(d?.workspacePath||''),d||{}));
 ipcMain.handle('manuscripts:saveCollation',async(_e,d)=>saveCollation(String(d?.workspacePath||''),d?.collation||{}));
 ipcMain.handle('manuscripts:deleteCollation',async(_e,d)=>deleteCollation(String(d?.workspacePath||''),String(d?.id||'')));
 ipcMain.handle('manuscripts:export',async(_e,d)=>exportCollation(String(d?.workspacePath||''),d?.collation||{},String(d?.format||'html')));
 ipcMain.handle('manuscripts:open',async(_e,d)=>{const err=await shell.openPath(String(d?.filePath||''));return{success:!err,message:err||'Opened export.'}});
}
