import fs from 'fs';
import path from 'path';
import crypto from 'crypto';

const now=()=>new Date().toISOString();
const read=(f,d)=>{try{return fs.existsSync(f)?JSON.parse(fs.readFileSync(f,'utf8')):d}catch{return d}};
const write=(f,v)=>{fs.mkdirSync(path.dirname(f),{recursive:true});fs.writeFileSync(f,JSON.stringify(v,null,2),'utf8')};
const esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const root=ws=>path.join(ws,'.ocr-studio','corpus');
const files=ws=>({corpora:path.join(root(ws),'corpora.json'),alignments:path.join(root(ws),'alignments.json'),memory:path.join(root(ws),'translation-memory.json'),terminology:path.join(root(ws),'terminology.json')});
const collection=(f)=>read(f,{items:[],updatedAt:null});
function dashboard(ws){const f=files(ws),corpora=collection(f.corpora).items,alignments=collection(f.alignments).items,memory=collection(f.memory).items,terminology=collection(f.terminology).items;const aligned=alignments.filter(a=>a.status==='Approved').length;const coverage=alignments.length?Math.round(aligned/alignments.length*100):0;return{success:true,message:`Loaded ${corpora.length} parallel corpus project(s).`,corpora,alignments,memory,terminology,summary:{corpora:corpora.length,alignments:alignments.length,approved:aligned,coverage,terms:terminology.length,memory:memory.length}}}
function saveItem(ws,key,item){const f=files(ws)[key],d=collection(f),value={...item,id:item.id||crypto.randomUUID(),updatedAt:now(),createdAt:item.createdAt||now()};const i=d.items.findIndex(x=>x.id===value.id);if(i>=0)d.items[i]=value;else d.items.unshift(value);d.updatedAt=now();write(f,d);return{success:true,message:`${key==='corpora'?'Corpus':key==='alignments'?'Alignment':key==='memory'?'Translation memory entry':'Terminology entry'} saved.`,item:value}}
function deleteItem(ws,key,id){const f=files(ws)[key],d=collection(f),before=d.items.length;d.items=d.items.filter(x=>x.id!==id);d.updatedAt=now();write(f,d);return{success:d.items.length<before,message:d.items.length<before?'Item deleted.':'Item not found.'}}
function suggest(ws,sourceText,targetLanguage){const d=dashboard(ws),q=String(sourceText||'').trim().toLowerCase();const exact=d.memory.filter(x=>String(x.sourceText||'').trim().toLowerCase()===q&&(!targetLanguage||x.targetLanguage===targetLanguage));const terms=d.terminology.filter(x=>q.includes(String(x.sourceTerm||'').trim().toLowerCase())&&(!targetLanguage||x.targetLanguage===targetLanguage));return{success:true,message:`Found ${exact.length+terms.length} suggestion(s).`,suggestions:[...exact.map(x=>({...x,type:'Translation memory'})),...terms.map(x=>({...x,type:'Terminology'}))]}}
function quality(ws,corpusId){const d=dashboard(ws),rows=d.alignments.filter(a=>!corpusId||a.corpusId===corpusId),total=rows.length,approved=rows.filter(a=>a.status==='Approved').length,missing=rows.filter(a=>!String(a.sourceText||'').trim()||!String(a.targetText||'').trim()).length,ai=rows.filter(a=>a.provenance==='AI').length,avg=total?Math.round(rows.reduce((s,a)=>s+Number(a.confidence||0),0)/total):0;return{success:true,message:'Alignment quality calculated.',quality:{total,approved,missing,coverage:total?Math.round((total-missing)/total*100):0,approvalRate:total?Math.round(approved/total*100):0,averageConfidence:avg,ai,human:total-ai}}}
function exportCorpus(ws,format,corpusId){const d=dashboard(ws),corpus=d.corpora.find(c=>c.id===corpusId)||d.corpora[0],rows=d.alignments.filter(a=>!corpus||a.corpusId===corpus.id),dir=path.join(root(ws),'exports');fs.mkdirSync(dir,{recursive:true});const stamp=Date.now();let filePath;const title=corpus?.name||'Parallel Corpus';
 if(format==='json'){filePath=path.join(dir,`parallel-corpus-${stamp}.json`);write(filePath,{generatedAt:now(),corpus,alignments:rows,terminology:d.terminology,memory:d.memory})}
 else if(format==='csv'){filePath=path.join(dir,`parallel-corpus-${stamp}.csv`);const q=v=>`"${String(v??'').replace(/"/g,'""')}"`;const lines=['Location,Source Language,Source Text,Target Language,Target Text,Level,Relation,Confidence,Status,Provenance',...rows.map(a=>[a.location,a.sourceLanguage,a.sourceText,a.targetLanguage,a.targetText,a.level,a.relation,a.confidence,a.status,a.provenance].map(q).join(','))];fs.writeFileSync(filePath,lines.join('\n'),'utf8')}
 else if(format==='tmx'){filePath=path.join(dir,`translation-memory-${stamp}.tmx`);const units=rows.map(a=>`<tu tuid="${esc(a.id)}"><tuv xml:lang="${esc(a.sourceLanguage||'und')}"><seg>${esc(a.sourceText)}</seg></tuv><tuv xml:lang="${esc(a.targetLanguage||'und')}"><seg>${esc(a.targetText)}</seg></tuv></tu>`).join('');fs.writeFileSync(filePath,`<?xml version="1.0" encoding="UTF-8"?><tmx version="1.4"><header creationtool="OCR Studio" creationtoolversion="1.0" segtype="sentence" adminlang="en" srclang="${esc(corpus?.sourceLanguage||'und')}" datatype="PlainText"/><body>${units}</body></tmx>`,'utf8')}
 else if(format==='xliff'){filePath=path.join(dir,`parallel-corpus-${stamp}.xlf`);const units=rows.map(a=>`<trans-unit id="${esc(a.id)}"><source>${esc(a.sourceText)}</source><target>${esc(a.targetText)}</target><note>${esc(a.location||'')}</note></trans-unit>`).join('');fs.writeFileSync(filePath,`<?xml version="1.0" encoding="UTF-8"?><xliff version="1.2"><file source-language="${esc(corpus?.sourceLanguage||'und')}" target-language="${esc(corpus?.targetLanguages?.[0]||'und')}" datatype="plaintext" original="ocr-studio"><body>${units}</body></file></xliff>`,'utf8')}
 else if(format==='tei'){filePath=path.join(dir,`parallel-corpus-${stamp}.xml`);const body=rows.map(a=>`<linkGrp type="translation" n="${esc(a.location||'')}"><ab xml:lang="${esc(a.sourceLanguage||'und')}" type="source">${esc(a.sourceText)}</ab><ab xml:lang="${esc(a.targetLanguage||'und')}" type="translation">${esc(a.targetText)}</ab></linkGrp>`).join('');fs.writeFileSync(filePath,`<?xml version="1.0" encoding="UTF-8"?><TEI xmlns="http://www.tei-c.org/ns/1.0"><teiHeader><fileDesc><titleStmt><title>${esc(title)}</title></titleStmt><publicationStmt><p>Generated by OCR Studio</p></publicationStmt><sourceDesc><p>Parallel corpus alignment</p></sourceDesc></fileDesc></teiHeader><text><body>${body}</body></text></TEI>`,'utf8')}
 else {filePath=path.join(dir,`parallel-corpus-${stamp}.html`);const body=rows.map(a=>`<article><div><small>${esc(a.location||'')}</small><h3>${esc(a.sourceText)}</h3><p>${esc(a.sourceLanguage)}</p></div><div><small>${esc(a.relation||'Equivalent')} · ${esc(a.confidence||0)}%</small><h3>${esc(a.targetText)}</h3><p>${esc(a.targetLanguage)}</p></div></article>`).join('');fs.writeFileSync(filePath,`<!doctype html><meta charset="utf-8"><title>${esc(title)}</title><style>body{font-family:system-ui;max-width:1100px;margin:40px auto;color:#33251d}article{display:grid;grid-template-columns:1fr 1fr;gap:24px;padding:18px 0;border-bottom:1px solid #eadfd6}small{color:#9b4f18}</style><h1>${esc(title)}</h1><p>${rows.length} aligned segment(s)</p>${body}`,'utf8')}
 return{success:true,message:`${format.toUpperCase()} export created with ${rows.length} alignment(s).`,filePath,count:rows.length}}
export function registerParallelCorpusIpc({ipcMain,shell}){
 ipcMain.handle('parallelCorpus:get',async(_e,d)=>dashboard(String(d?.workspacePath||'')));
 ipcMain.handle('parallelCorpus:saveCorpus',async(_e,d)=>saveItem(String(d?.workspacePath||''),'corpora',d?.corpus||{}));
 ipcMain.handle('parallelCorpus:deleteCorpus',async(_e,d)=>deleteItem(String(d?.workspacePath||''),'corpora',String(d?.id||'')));
 ipcMain.handle('parallelCorpus:saveAlignment',async(_e,d)=>saveItem(String(d?.workspacePath||''),'alignments',d?.alignment||{}));
 ipcMain.handle('parallelCorpus:deleteAlignment',async(_e,d)=>deleteItem(String(d?.workspacePath||''),'alignments',String(d?.id||'')));
 ipcMain.handle('parallelCorpus:saveMemory',async(_e,d)=>saveItem(String(d?.workspacePath||''),'memory',d?.entry||{}));
 ipcMain.handle('parallelCorpus:saveTerm',async(_e,d)=>saveItem(String(d?.workspacePath||''),'terminology',d?.entry||{}));
 ipcMain.handle('parallelCorpus:deleteTerm',async(_e,d)=>deleteItem(String(d?.workspacePath||''),'terminology',String(d?.id||'')));
 ipcMain.handle('parallelCorpus:suggest',async(_e,d)=>suggest(String(d?.workspacePath||''),d?.sourceText,d?.targetLanguage));
 ipcMain.handle('parallelCorpus:quality',async(_e,d)=>quality(String(d?.workspacePath||''),d?.corpusId));
 ipcMain.handle('parallelCorpus:export',async(_e,d)=>exportCorpus(String(d?.workspacePath||''),String(d?.format||'html'),d?.corpusId));
 ipcMain.handle('parallelCorpus:open',async(_e,d)=>{const err=await shell.openPath(String(d?.filePath||''));return{success:!err,message:err||'Opened parallel corpus export.'}});
}
