import fs from 'fs';
import path from 'path';
import crypto from 'crypto';

const now=()=>new Date().toISOString();
const read=(f,d)=>{try{return fs.existsSync(f)?JSON.parse(fs.readFileSync(f,'utf8')):d}catch{return d}};
const write=(f,v)=>{fs.mkdirSync(path.dirname(f),{recursive:true});fs.writeFileSync(f,JSON.stringify(v,null,2),'utf8')};
const esc=v=>String(v??'').replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));
const idx=ws=>path.join(ws,'.ocr-studio','editions','editions.json');
const getEdition=(ws,id)=>(read(idx(ws),{editions:[]}).editions||[]).find(x=>x.id===id)||null;
const edir=(ws,e)=>path.join(ws,'.ocr-studio','editions',e.folderName);
const entries=(ws,e,n)=>{const x=read(path.join(edir(ws,e),n),{entries:[]});return Array.isArray(x.entries)?x.entries:[]};
const verses=s=>{const a=[];for(const b of s.books||[])for(const c of b.chapters||[])for(const v of c.verses||[])a.push({book:b,chapter:c,verse:v});return a};
const slug=s=>String(s||'edition').toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'')||'edition';
const publicationFile=(ws,e)=>path.join(edir(ws,e),'publication.json');
const historyFile=(ws,e)=>path.join(edir(ws,e),'publication-history.json');
const profileFile=(ws,e)=>path.join(edir(ws,e),'export-profiles.json');
const defaultProfiles=[
 {id:'reader',name:'Reader Edition',description:'Clean reading text, translations and commentary.',include:{apparatus:false,commentary:true,footnotes:true,decisions:false,ai:false}},
 {id:'academic',name:'Academic Edition',description:'Critical text, apparatus, commentary, notes and editorial metadata.',include:{apparatus:true,commentary:true,footnotes:true,decisions:true,ai:false}},
 {id:'research',name:'Research Edition',description:'Complete archival export including decisions, evidence and AI review.',include:{apparatus:true,commentary:true,footnotes:true,decisions:true,ai:true}}
];
function ensure(ws,e){
 const pub=read(publicationFile(ws,e),{title:e.title,subtitle:e.subtitle||'',publisher:e.institution||'',authors:[],editors:e.editors||[],contributors:[],abstract:e.description||'',license:e.license||'',doi:e.doi||'',isbn:e.isbn||'',keywords:e.keywords||[],version:e.version||'1.0',updatedAt:now()});
 const profiles=read(profileFile(ws,e),{profiles:defaultProfiles});
 const history=read(historyFile(ws,e),{entries:[]});
 write(publicationFile(ws,e),pub);write(profileFile(ws,e),profiles);write(historyFile(ws,e),history);
 return {pub,profiles:profiles.profiles||defaultProfiles,history:history.entries||[]};
}
function loadBundle(ws,e){
 const structure=read(path.join(edir(ws,e),'structure.json'),{books:[]});
 return {edition:e,structure,apparatus:entries(ws,e,'apparatus.json'),commentary:entries(ws,e,'commentary.json'),footnotes:entries(ws,e,'footnotes.json'),decisions:entries(ws,e,'editorial-decisions.json'),evidence:entries(ws,e,'editorial-decision-evidence.json'),ai:entries(ws,e,'editorial-ai-suggestions.json'),validation:read(path.join(edir(ws,e),'publication-validation-report.json'),null)};
}
function renderMarkdown(b,p,profile){let out=`# ${p.title||b.edition.title}\n\n`;if(p.subtitle)out+=`## ${p.subtitle}\n\n`;if(p.abstract)out+=`${p.abstract}\n\n`;for(const book of b.structure.books||[]){out+=`# ${book.title||`Book ${book.number}`}\n\n`;for(const ch of book.chapters||[]){out+=`## ${ch.title||`Chapter ${ch.number}`}\n\n`;for(const v of ch.verses||[]){out+=`### Verse ${v.number}\n\n${v.criticalText||''}\n\n`;for(const [lang,text] of Object.entries(v.languages||{}))if(text)out+=`**${lang}:** ${text}\n\n`;if(profile.include.commentary)for(const x of b.commentary.filter(a=>a.verseId===v.id))out+=`> Commentary: ${x.content||''}\n\n`;if(profile.include.footnotes)for(const x of b.footnotes.filter(a=>a.verseId===v.id))out+=`[^${x.id}]: ${x.content||''}\n\n`;if(profile.include.apparatus){const a=b.apparatus.filter(x=>x.verseId===v.id);if(a.length){out+=`**Apparatus**\n\n`;for(const x of a)out+=`- ${x.label||''}: ${x.reading||''} (${(x.witnesses||[]).join(', ')})\n`;out+='\n';}}}}}return out;}
function renderHtml(b,p,profile){const body=(b.structure.books||[]).map(book=>`<section><h1>${esc(book.title||`Book ${book.number}`)}</h1>${(book.chapters||[]).map(ch=>`<article><h2>${esc(ch.title||`Chapter ${ch.number}`)}</h2>${(ch.verses||[]).map(v=>`<div class="verse" id="verse-${esc(v.id)}"><h3>Verse ${esc(v.number)}</h3><div class="critical">${esc(v.criticalText||'')}</div>${Object.entries(v.languages||{}).filter(([,t])=>t).map(([l,t])=>`<p><b>${esc(l)}:</b> ${esc(t)}</p>`).join('')}${profile.include.apparatus?`<details><summary>Apparatus</summary>${b.apparatus.filter(x=>x.verseId===v.id).map(x=>`<p>${esc(x.label)}: ${esc(x.reading)} <i>${esc((x.witnesses||[]).join(', '))}</i></p>`).join('')}</details>`:''}${profile.include.commentary?b.commentary.filter(x=>x.verseId===v.id).map(x=>`<aside>${esc(x.content)}</aside>`).join(''):''}</div>`).join('')}</article>`).join('')}</section>`).join('');return `<!doctype html><html><head><meta charset="utf-8"><title>${esc(p.title||b.edition.title)}</title><style>body{max-width:900px;margin:40px auto;font:17px Georgia,serif;line-height:1.65;padding:0 24px;color:#231f1a}header{text-align:center;border-bottom:1px solid #bbb;margin-bottom:40px}.verse{margin:28px 0}.critical{font-size:1.2em;white-space:pre-wrap}aside{background:#f5f0e8;padding:12px;margin:12px 0}details{margin:12px 0}</style></head><body><header><h1>${esc(p.title||b.edition.title)}</h1><h2>${esc(p.subtitle||'')}</h2><p>${esc(p.abstract||'')}</p></header>${body}<footer><p>${esc(p.license||'')}</p></footer></body></html>`;}
function renderTei(b,p){const books=(b.structure.books||[]).map(book=>`<div type="book" n="${esc(book.number)}"><head>${esc(book.title||'')}</head>${(book.chapters||[]).map(ch=>`<div type="chapter" n="${esc(ch.number)}"><head>${esc(ch.title||'')}</head>${(ch.verses||[]).map(v=>`<lg type="verse" n="${esc(v.number)}" xml:id="v-${esc(v.id)}"><l>${esc(v.criticalText||'')}</l>${b.apparatus.filter(x=>x.verseId===v.id).map(x=>`<app><rdg wit="${esc((x.witnesses||[]).map(w=>'#'+w).join(' '))}">${esc(x.reading||'')}</rdg></app>`).join('')}${b.commentary.filter(x=>x.verseId===v.id).map(x=>`<note type="commentary">${esc(x.content||'')}</note>`).join('')}</lg>`).join('')}</div>`).join('')}</div>`).join('');return `<?xml version="1.0" encoding="UTF-8"?><TEI xmlns="http://www.tei-c.org/ns/1.0"><teiHeader><fileDesc><titleStmt><title>${esc(p.title||b.edition.title)}</title><editor>${esc((p.editors||[]).join(', '))}</editor></titleStmt><publicationStmt><publisher>${esc(p.publisher||'')}</publisher><availability>${esc(p.license||'')}</availability></publicationStmt><sourceDesc><p>Generated by OCR Studio</p></sourceDesc></fileDesc></teiHeader><text><body>${books}</body></text></TEI>`;}
function extFor(format){return {html:'html',markdown:'md',tei:'xml',json:'json',archive:'ocrstudio'}[format]||format}
function generate(ws,id,format,profileId){const e=getEdition(ws,id);if(!e)return{success:false,message:'Edition not found.'};const {pub,profiles}=ensure(ws,e),profile=profiles.find(x=>x.id===profileId)||profiles[0];const b=loadBundle(ws,e);if(b.validation?.counts?.blockers>0)return{success:false,message:`Export blocked: ${b.validation.counts.blockers} publication blocker(s) remain.`};const out=path.join(edir(ws,e),'exports');fs.mkdirSync(out,{recursive:true});const stamp=now().replace(/[:.]/g,'-'),base=`${slug(pub.title||e.title)}-${profile.id}-${stamp}`,formatKey=String(format||'html');let content;if(formatKey==='html')content=renderHtml(b,pub,profile);else if(formatKey==='markdown')content=renderMarkdown(b,pub,profile);else if(formatKey==='tei')content=renderTei(b,pub);else if(formatKey==='json')content=JSON.stringify({publication:pub,profile,bundle:b},null,2);else if(formatKey==='archive')content=JSON.stringify({format:'OCRStudioArchive',version:1,createdAt:now(),publication:pub,profile,bundle:b},null,2);else return{success:false,message:'Unsupported export format.'};const target=path.join(out,`${base}.${extFor(formatKey)}`);fs.writeFileSync(target,content,'utf8');const h=read(historyFile(ws,e),{entries:[]});const row={id:crypto.randomUUID(),createdAt:now(),format:formatKey,profileId:profile.id,profileName:profile.name,filePath:target,readiness:b.validation?.readiness??null,editionVersion:e.version};h.entries=[row,...(h.entries||[])];write(historyFile(ws,e),h);return{success:true,message:`${formatKey.toUpperCase()} export created.`,entry:row,filePath:target};}
export function registerPublicationExporterIpc({ipcMain,shell}){
 ipcMain.handle('editionExporter:get',async(_e,d)=>{const e=getEdition(String(d?.workspacePath||''),String(d?.editionId||''));if(!e)return{success:false,message:'Edition not found.'};const s=ensure(String(d.workspacePath),e);return{success:true,message:'Publication center loaded.',edition:e,publication:s.pub,profiles:s.profiles,history:s.history,validation:read(path.join(edir(String(d.workspacePath),e),'publication-validation-report.json'),null)};});
 ipcMain.handle('editionExporter:saveMetadata',async(_e,d)=>{const e=getEdition(String(d?.workspacePath||''),String(d?.editionId||''));if(!e)return{success:false,message:'Edition not found.'};const value={...(d.metadata||{}),updatedAt:now()};write(publicationFile(String(d.workspacePath),e),value);return{success:true,message:'Publication metadata saved.',publication:value};});
 ipcMain.handle('editionExporter:generate',async(_e,d)=>generate(String(d?.workspacePath||''),String(d?.editionId||''),String(d?.format||'html'),String(d?.profileId||'reader')));
 ipcMain.handle('editionExporter:open',async(_e,d)=>{const err=await shell.openPath(String(d?.filePath||''));return{success:!err,message:err||'Opened export.'}});
}
