import fs from "fs";
import path from "path";
import crypto from "crypto";

const now=()=>new Date().toISOString();
const id=(p)=>`${p}-${crypto.randomUUID()}`;
const readJson=(f,d)=>{try{return fs.existsSync(f)?JSON.parse(fs.readFileSync(f,"utf8")):d}catch{return d}};
const writeJson=(f,v)=>{fs.mkdirSync(path.dirname(f),{recursive:true});fs.writeFileSync(f,JSON.stringify(v,null,2),"utf8")};
const esc=(s)=>String(s??"").replace(/[&<>\"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;"}[c]));
const root=(projectPath)=>path.join(projectPath,".ocr-studio","assistant");
const files=(projectPath)=>({
 conversations:path.join(root(projectPath),"conversations.json"), notebooks:path.join(root(projectPath),"notebooks.json"),
 prompts:path.join(root(projectPath),"prompts.json"), bookmarks:path.join(root(projectPath),"bookmarks.json"), index:path.join(root(projectPath),"semantic-index.json"), exports:path.join(root(projectPath),"exports")
});
const defaultPrompts=[
 {id:"prompt-compare",title:"Compare manuscript traditions",prompt:"Compare the manuscript evidence for this passage and identify agreements, omissions, and substantive variants.",category:"Textual criticism"},
 {id:"prompt-summary",title:"Summarize chapter",prompt:"Summarize this chapter using only evidence available in the project corpus.",category:"Synthesis"},
 {id:"prompt-apparatus",title:"Explain apparatus",prompt:"Explain the critical apparatus and the evidence supporting the adopted reading.",category:"Critical edition"},
 {id:"prompt-ocr",title:"Detect OCR issues",prompt:"Find probable OCR errors, suspicious readings, and inconsistent spellings.",category:"OCR review"},
 {id:"prompt-translation",title:"Compare translations",prompt:"Compare the available translations and identify terminology or interpretive differences.",category:"Translation"},
 {id:"prompt-glossary",title:"Build glossary",prompt:"Create an evidence-grounded glossary of important terms in this material.",category:"Terminology"}
];
const aliases={compassion:["compassion","daya","dayā","karuna","karuṇā","mercy","kindness","anukampa"],dharma:["dharma","धर्म","ధర్మ","righteousness","duty"],krishna:["krishna","kṛṣṇa","कृष्ण","కృష్ణ"],arjuna:["arjuna","arjunaḥ","अर्जुन","అర్జున"],bhishma:["bhishma","bhīṣma","भीष्म","భీష్మ"]};
function ensure(projectPath){const f=files(projectPath);fs.mkdirSync(root(projectPath),{recursive:true});if(!fs.existsSync(f.conversations))writeJson(f.conversations,[]);if(!fs.existsSync(f.notebooks))writeJson(f.notebooks,[]);if(!fs.existsSync(f.prompts))writeJson(f.prompts,defaultPrompts);if(!fs.existsSync(f.bookmarks))writeJson(f.bookmarks,[]);return f}
function walk(dir,out=[],depth=0){if(depth>5||!fs.existsSync(dir))return out;for(const e of fs.readdirSync(dir,{withFileTypes:true})){if(["node_modules","dist","exports","assistant"].includes(e.name))continue;const p=path.join(dir,e.name);if(e.isDirectory())walk(p,out,depth+1);else if(/\.(json|txt|md)$/i.test(e.name)&&fs.statSync(p).size<5_000_000)out.push(p)}return out}
function flatten(value,prefix="",out=[]){if(value==null)return out;if(typeof value==="string"||typeof value==="number"){const text=String(value).trim();if(text.length>2)out.push({field:prefix||"text",text});return out}if(Array.isArray(value)){value.forEach((v,i)=>flatten(v,`${prefix}[${i}]`,out));return out}if(typeof value==="object")Object.entries(value).forEach(([k,v])=>flatten(v,prefix?`${prefix}.${k}`:k,out));return out}
function labelFor(file){const n=file.toLowerCase();if(n.includes("apparatus"))return"Critical apparatus";if(n.includes("collation")||n.includes("witness"))return"Manuscript witness";if(n.includes("decision"))return"Editorial decision";if(n.includes("translation")||n.includes("corpus"))return"Parallel translation";if(n.includes("entities")||n.includes("relationship"))return"Knowledge graph";if(n.includes("edition"))return"Scholarly edition";return"Project source"}
function buildIndex(projectPath){const docs=[];for(const file of walk(path.join(projectPath,".ocr-studio"))){try{const raw=fs.readFileSync(file,"utf8");const items=file.endsWith(".json")?flatten(JSON.parse(raw)): [{field:"text",text:raw}];for(const item of items){if(item.text.length<3)continue;docs.push({id:id("src"),sourceType:labelFor(file),filePath:file,relativePath:path.relative(projectPath,file),field:item.field,text:item.text.slice(0,4000),searchText:item.text.toLowerCase()})}}catch{}}
 const payload={builtAt:now(),documentCount:docs.length,documents:docs};writeJson(files(projectPath).index,payload);return payload}
function expandQuery(q){const lower=q.toLowerCase();const terms=new Set(lower.match(/[\p{L}\p{N}]+/gu)||[]);for(const [key,vals] of Object.entries(aliases))if(lower.includes(key)||vals.some(v=>lower.includes(v.toLowerCase())))vals.forEach(v=>terms.add(v.toLowerCase()));return [...terms].filter(t=>t.length>1)}
function search(projectPath,query,limit=12){const f=ensure(projectPath);let idx=readJson(f.index,null);if(!idx||!Array.isArray(idx.documents))idx=buildIndex(projectPath);const terms=expandQuery(query);const results=idx.documents.map(d=>{const hay=d.searchText||d.text.toLowerCase();let score=0;for(const t of terms){if(hay.includes(t))score+=t.length>5?3:1}if(hay.includes(query.toLowerCase()))score+=8;return{...d,score}}).filter(x=>x.score>0).sort((a,b)=>b.score-a.score).slice(0,limit);return{terms,results,index:idx}}
function answerFromResults(question,results){if(!results.length)return{answer:"No supporting evidence was found in the indexed project sources. Rebuild the semantic index after adding or updating scholarly data.",confidence:0};const grouped={};results.forEach(r=>{(grouped[r.sourceType]??=[]).push(r)});const lines=[`The project contains ${results.length} relevant evidence item${results.length===1?"":"s"} for this question.`];for(const [kind,items] of Object.entries(grouped).slice(0,5)){const sample=items[0];lines.push(`${kind}: ${sample.text.replace(/\s+/g," ").slice(0,240)}${sample.text.length>240?"…":""}`)}lines.push("This response is a retrieval-based synthesis. Review the cited evidence before adopting it in an edition or publication.");const confidence=Math.min(0.95,0.42+results.length*0.045);return{answer:lines.join("\n\n"),confidence}}
function citation(e,style="Chicago"){const title=e.sourceType||"OCR Studio source";const loc=e.relativePath||e.filePath||"project data";const accessed=new Date().toISOString().slice(0,10);if(style==="MLA")return`“${title}.” OCR Studio Project, ${loc}. Accessed ${accessed}.`;if(style==="APA")return`OCR Studio Project. (${accessed}). ${title} [Project data]. ${loc}.`;if(style==="SBL")return`${title}. OCR Studio project data, ${loc} (accessed ${accessed}).`;return`${title}, OCR Studio project data, ${loc}, accessed ${accessed}.`}
export function registerScholarlyAssistantIpc({ipcMain,shell,getProjects}){
 ipcMain.handle("scholarlyAssistant:workspace",async(_,d={})=>{const projects=(await Promise.resolve(getProjects?.()||[])).map(p=>({projectPath:p.projectPath||p.workspacePath,projectName:p.name||p.projectName||path.basename(p.projectPath||p.workspacePath||"")})).filter(p=>p.projectPath);const projectPath=d.projectPath||projects[0]?.projectPath;if(!projectPath)return{success:true,projects,conversations:[],notebooks:[],prompts:defaultPrompts,bookmarks:[],index:null};const f=ensure(projectPath);return{success:true,projects,projectPath,conversations:readJson(f.conversations,[]),notebooks:readJson(f.notebooks,[]),prompts:readJson(f.prompts,defaultPrompts),bookmarks:readJson(f.bookmarks,[]),index:readJson(f.index,null)}});
 ipcMain.handle("scholarlyAssistant:reindex",async(_,d)=>({success:true,index:buildIndex(d.projectPath),message:"Semantic index rebuilt."}));
 ipcMain.handle("scholarlyAssistant:ask",async(_,d)=>{const f=ensure(d.projectPath);const found=search(d.projectPath,d.question,d.limit||12);const synth=answerFromResults(d.question,found.results);const conversations=readJson(f.conversations,[]);let conv=conversations.find(c=>c.id===d.conversationId);if(!conv){conv={id:id("conversation"),title:d.question.slice(0,70),createdAt:now(),updatedAt:now(),messages:[]};conversations.unshift(conv)}conv.messages.push({id:id("message"),role:"user",content:d.question,createdAt:now()});conv.messages.push({id:id("message"),role:"assistant",content:synth.answer,confidence:synth.confidence,evidence:found.results.map(r=>({...r,citations:{Chicago:citation(r,"Chicago"),MLA:citation(r,"MLA"),APA:citation(r,"APA"),SBL:citation(r,"SBL")}})),createdAt:now()});conv.updatedAt=now();writeJson(f.conversations,conversations);return{success:true,conversation:conv,answer:synth.answer,confidence:synth.confidence,evidence:found.results};});
 ipcMain.handle("scholarlyAssistant:deleteConversation",async(_,d)=>{const f=ensure(d.projectPath);writeJson(f.conversations,readJson(f.conversations,[]).filter(x=>x.id!==d.id));return{success:true}});
 ipcMain.handle("scholarlyAssistant:saveNotebook",async(_,d)=>{const f=ensure(d.projectPath),all=readJson(f.notebooks,[]);const n={...d.notebook,id:d.notebook.id||id("note"),updatedAt:now(),createdAt:d.notebook.createdAt||now()};const i=all.findIndex(x=>x.id===n.id);i>=0?all.splice(i,1,n):all.unshift(n);writeJson(f.notebooks,all);return{success:true,notebook:n}});
 ipcMain.handle("scholarlyAssistant:deleteNotebook",async(_,d)=>{const f=ensure(d.projectPath);writeJson(f.notebooks,readJson(f.notebooks,[]).filter(x=>x.id!==d.id));return{success:true}});
 ipcMain.handle("scholarlyAssistant:savePrompt",async(_,d)=>{const f=ensure(d.projectPath),all=readJson(f.prompts,defaultPrompts);const p={...d.prompt,id:d.prompt.id||id("prompt")};const i=all.findIndex(x=>x.id===p.id);i>=0?all.splice(i,1,p):all.unshift(p);writeJson(f.prompts,all);return{success:true,prompt:p}});
 ipcMain.handle("scholarlyAssistant:saveBookmark",async(_,d)=>{const f=ensure(d.projectPath),all=readJson(f.bookmarks,[]);const b={...d.bookmark,id:d.bookmark.id||id("bookmark"),createdAt:d.bookmark.createdAt||now()};all.unshift(b);writeJson(f.bookmarks,all);return{success:true,bookmark:b}});
 ipcMain.handle("scholarlyAssistant:deleteBookmark",async(_,d)=>{const f=ensure(d.projectPath);writeJson(f.bookmarks,readJson(f.bookmarks,[]).filter(x=>x.id!==d.id));return{success:true}});
 ipcMain.handle("scholarlyAssistant:citation",async(_,d)=>({success:true,citation:citation(d.evidence,d.style)}));
 ipcMain.handle("scholarlyAssistant:export",async(_,d)=>{const f=ensure(d.projectPath);fs.mkdirSync(f.exports,{recursive:true});const conversations=readJson(f.conversations,[]),conv=conversations.find(x=>x.id===d.conversationId);if(!conv)return{success:false,message:"Conversation not found."};const out=path.join(f.exports,`research-${Date.now()}.${d.format==="json"?"json":"html"}`);if(d.format==="json")writeJson(out,conv);else{const body=conv.messages.map(m=>`<section><h3>${esc(m.role)}</h3><p>${esc(m.content).replace(/\n/g,"<br>")}</p>${(m.evidence||[]).map(e=>`<blockquote><b>${esc(e.sourceType)}</b><br>${esc(e.text)}<br><small>${esc(e.relativePath)}</small></blockquote>`).join("")}</section>`).join("");fs.writeFileSync(out,`<!doctype html><meta charset="utf-8"><title>${esc(conv.title)}</title><h1>${esc(conv.title)}</h1>${body}`,"utf8")}return{success:true,filePath:out,message:"Research conversation exported."}});
 ipcMain.handle("scholarlyAssistant:open",async(_,d)=>{await shell.openPath(d.filePath);return{success:true}});
}
