import fs from "fs";
import path from "path";
import crypto from "crypto";

const now=()=>new Date().toISOString();
const uid=(p)=>`${p}-${Date.now()}-${crypto.randomBytes(3).toString("hex")}`;
const dir=(projectPath)=>path.join(projectPath,".ocr-studio","knowledge-graph");
const file=(projectPath)=>path.join(dir(projectPath),"timeline-narrative.json");
const graphFile=(projectPath)=>path.join(dir(projectPath),"graph.json");
const readJson=(f,x)=>{try{return JSON.parse(fs.readFileSync(f,"utf8"))}catch{return x}};
const blank=()=>({version:1,events:[],places:[],threads:[],reviewQueue:[],extractionJobs:[],updatedAt:null});
const readStore=(p)=>{const v=readJson(file(p),blank());return {...blank(),...v,events:v.events||[],places:v.places||[],threads:v.threads||[],reviewQueue:v.reviewQueue||[],extractionJobs:v.extractionJobs||[]}};
const save=(p,s)=>{fs.mkdirSync(dir(p),{recursive:true});s.updatedAt=now();fs.writeFileSync(file(p),JSON.stringify(s,null,2));return s};
const norm=(v)=>String(v||"").normalize("NFKC").replace(/\s+/g," ").trim();
const clamp=(n)=>Math.max(0,Math.min(1,Number(n)||0));
function pages(projectPath){const root=path.join(projectPath,"ocr-word-index"),out=[];if(!fs.existsSync(root))return out;for(const d of fs.readdirSync(root,{withFileTypes:true})){if(!d.isDirectory())continue;for(const n of fs.readdirSync(path.join(root,d.name)).filter(x=>/^page-\d+\.json$/i.test(x))){const x=readJson(path.join(root,d.name,n),null);if(!x)continue;const words=(x.words||[]).map(w=>norm(w.correctedText||w.corrected||w.text||w.word)).filter(Boolean);out.push({documentId:Number(d.name),documentName:x.sourceFile||x.fileName||`Document ${d.name}`,pageNumber:Number(x.pageNumber)||Number((n.match(/\d+/)||[1])[0]),text:words.join(" ")})}}return out.sort((a,b)=>a.documentId-b.documentId||a.pageNumber-b.pageNumber)}
function parseJson(text){const s=String(text||"").replace(/^```(?:json)?/i,"").replace(/```$/i,"").trim();try{return JSON.parse(s)}catch{}const a=s.indexOf("{"),b=s.lastIndexOf("}");if(a>=0&&b>a){try{return JSON.parse(s.slice(a,b+1))}catch{}}return null}
async function askOllama({endpoint,model,text}){const c=new AbortController(),t=setTimeout(()=>c.abort(),120000);const prompt=`Extract explicit narrative events and places from this reviewed OCR passage. Return JSON only: {"events":[{"title":"","description":"","participants":[],"place":"","relativeOrder":"","confidence":0.0,"evidenceQuote":""}],"places":[{"name":"","aliases":[],"description":"","confidence":0.0}]}. Do not invent. Maximum 8 events and 8 places. PASSAGE:\n${text.slice(0,5500)}`;try{const r=await fetch(`${String(endpoint||"http://127.0.0.1:11434").replace(/\/$/,"")}/api/chat`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({model:model||"llama3.2:3b",stream:false,keep_alive:"10m",options:{temperature:.1,num_ctx:4096,num_predict:900},messages:[{role:"user",content:prompt}]}),signal:c.signal});if(!r.ok)throw new Error(`Ollama returned HTTP ${r.status}`);const j=await r.json(),p=parseJson(j?.message?.content);if(!p)throw new Error("Ollama did not return valid event JSON.");return p}finally{clearTimeout(t)}}
function upsertPlace(s,name,evidence,source="Manual",confidence=1){const clean=norm(name);if(!clean)return null;let p=s.places.find(x=>norm(x.name).toLowerCase()===clean.toLowerCase()||(x.aliases||[]).some(a=>norm(a).toLowerCase()===clean.toLowerCase()));if(!p){p={id:uid("place"),name:clean,aliases:[],description:"",latitude:null,longitude:null,status:source==="Manual"?"Verified":"Suggested",confidence:clamp(confidence),source,evidence:[],createdAt:now(),updatedAt:now()};s.places.push(p);if(p.status==="Suggested")s.reviewQueue.push({id:uid("review"),kind:"Place",targetId:p.id,status:"Pending",createdAt:now()})}if(evidence&&!p.evidence.some(x=>x.documentId===evidence.documentId&&x.pageNumber===evidence.pageNumber))p.evidence.push(evidence);return p}
function addEvent(s,data,source="Manual"){const e={id:uid("event"),title:norm(data.title)||"Untitled event",description:norm(data.description),participants:Array.isArray(data.participants)?data.participants.map(norm).filter(Boolean):[],placeId:data.placeId||null,placeName:norm(data.placeName),relativeOrder:norm(data.relativeOrder),chronology:Number.isFinite(Number(data.chronology))?Number(data.chronology):s.events.length+1,status:source==="Manual"?"Verified":"Suggested",confidence:clamp(data.confidence??(source==="Manual"?1:.72)),source,evidence:data.evidence||null,createdAt:now(),updatedAt:now()};s.events.push(e);if(e.status==="Suggested")s.reviewQueue.push({id:uid("review"),kind:"Event",targetId:e.id,status:"Pending",createdAt:now()});return e}
function analytics(s){return {events:s.events.length,verifiedEvents:s.events.filter(x=>x.status==="Verified").length,pending:s.reviewQueue.filter(x=>x.status==="Pending").length,places:s.places.length,threads:s.threads.length,locatedEvents:s.events.filter(x=>x.placeId||x.placeName).length}}
export function registerTimelineNarrativeIpc({ipcMain,dialog,shell,getProjects}){
 ipcMain.handle("timeline:getWorkspace",async()=>{const projects=(await getProjects()).map(p=>{const s=readStore(p.projectPath);return {projectPath:p.projectPath,projectName:p.name,...analytics(s)}});return {projects,totals:projects.reduce((a,p)=>({events:a.events+p.events,places:a.places+p.places,threads:a.threads+p.threads,pending:a.pending+p.pending}),{events:0,places:0,threads:0,pending:0})}});
 ipcMain.handle("timeline:getProject",async(_,{projectPath})=>{const store=readStore(projectPath);return {success:true,store,analytics:analytics(store)}});
 ipcMain.handle("timeline:addEvent",async(_,data)=>{const s=readStore(data.projectPath);addEvent(s,data,"Manual");save(data.projectPath,s);return {success:true,message:"Event saved.",store:s,analytics:analytics(s)}});
 ipcMain.handle("timeline:addPlace",async(_,data)=>{const s=readStore(data.projectPath);const p=upsertPlace(s,data.name,null,"Manual",1);if(p){p.description=norm(data.description);p.aliases=Array.isArray(data.aliases)?data.aliases.map(norm).filter(Boolean):[];p.latitude=data.latitude===""||data.latitude==null?null:Number(data.latitude);p.longitude=data.longitude===""||data.longitude==null?null:Number(data.longitude);p.updatedAt=now()}save(data.projectPath,s);return {success:true,message:"Place saved.",store:s,analytics:analytics(s)}});
 ipcMain.handle("timeline:updatePlace",async(_,data)=>{const s=readStore(data.projectPath),p=s.places.find(x=>x.id===data.placeId);if(!p)return {success:false,message:"Place not found."};Object.assign(p,{name:norm(data.name)||p.name,description:norm(data.description),aliases:Array.isArray(data.aliases)?data.aliases.map(norm).filter(Boolean):p.aliases,latitude:data.latitude===""||data.latitude==null?null:Number(data.latitude),longitude:data.longitude===""||data.longitude==null?null:Number(data.longitude),updatedAt:now()});save(data.projectPath,s);return {success:true,message:"Place updated.",store:s,analytics:analytics(s)}});
 ipcMain.handle("timeline:createThread",async(_,data)=>{const s=readStore(data.projectPath);s.threads.push({id:uid("thread"),title:norm(data.title)||"Untitled narrative",description:norm(data.description),eventIds:[],notes:"",createdAt:now(),updatedAt:now()});save(data.projectPath,s);return {success:true,message:"Narrative thread created.",store:s,analytics:analytics(s)}});
 ipcMain.handle("timeline:updateThread",async(_,data)=>{const s=readStore(data.projectPath),t=s.threads.find(x=>x.id===data.threadId);if(!t)return {success:false,message:"Thread not found."};if(data.title!==undefined)t.title=norm(data.title)||t.title;if(data.description!==undefined)t.description=norm(data.description);if(data.notes!==undefined)t.notes=norm(data.notes);if(Array.isArray(data.eventIds))t.eventIds=data.eventIds.filter(id=>s.events.some(e=>e.id===id));t.updatedAt=now();save(data.projectPath,s);return {success:true,message:"Narrative thread updated.",store:s,analytics:analytics(s)}});
 ipcMain.handle("timeline:review",async(_,data)=>{const s=readStore(data.projectPath),q=s.reviewQueue.find(x=>x.id===data.reviewId);if(!q)return {success:false,message:"Review item not found."};q.status=data.decision;q.reviewedAt=now();q.note=norm(data.note);const list=q.kind==="Event"?s.events:s.places,target=list.find(x=>x.id===q.targetId);if(target){target.status=data.decision==="Approved"?"Verified":"Rejected";target.reviewedAt=now();target.reviewerNote=q.note}save(data.projectPath,s);return {success:true,message:`${q.kind} ${data.decision.toLowerCase()}.`,store:s,analytics:analytics(s)}});
 ipcMain.handle("timeline:extractRules",async(_,data)=>{const s=readStore(data.projectPath),all=pages(data.projectPath).slice(0,Number(data.pageLimit)||100);let count=0;const patterns=[/([\p{L}][\p{L}\s]{2,50})\s+(?:went|came|arrived|visited|met|fought|defeated|married|performed|entered|left)\s+([\p{L}][\p{L}\s]{2,60})/giu,/([\p{L}][\p{L}\s]{2,60})\s+(?:युद्ध|विवाह|सभा|यज्ञ|यात्रा)/giu];for(const p of all){for(const pattern of patterns){for(const m of p.text.matchAll(pattern)){const evidence={documentId:p.documentId,documentName:p.documentName,pageNumber:p.pageNumber,excerpt:p.text.slice(0,500),quote:norm(m[0])};addEvent(s,{title:norm(m[0]).slice(0,100),description:"Rule-detected narrative event",participants:[],relativeOrder:`Document ${p.documentId}, page ${p.pageNumber}`,confidence:.76,evidence},"Rule");count++}}}save(data.projectPath,s);return {success:true,message:`Created ${count} event suggestion(s) from textual patterns.`,store:s,analytics:analytics(s)}});
 ipcMain.handle("timeline:discoverAi",async(_,data)=>{const s=readStore(data.projectPath),all=pages(data.projectPath).filter(p=>!data.documentId||p.documentId===Number(data.documentId)).slice(0,Number(data.pageLimit)||10);const job={id:uid("job"),model:data.model||"llama3.2:3b",status:"Running",createdAt:now(),errors:[],pages:all.length,addedEvents:0,addedPlaces:0};s.extractionJobs.unshift(job);for(const p of all){try{const result=await askOllama({endpoint:data.endpoint,model:data.model,text:p.text});const evidenceBase={documentId:p.documentId,documentName:p.documentName,pageNumber:p.pageNumber,excerpt:p.text.slice(0,500)};for(const place of result.places||[]){const before=s.places.length,rec=upsertPlace(s,place.name,evidenceBase,"Local AI",place.confidence);if(rec){rec.aliases=[...new Set([...(rec.aliases||[]),...(place.aliases||[]).map(norm).filter(Boolean)])];rec.description=rec.description||norm(place.description)}if(s.places.length>before)job.addedPlaces++}for(const event of result.events||[]){let placeId=null;if(event.place){const place=upsertPlace(s,event.place,evidenceBase,"Local AI",event.confidence);placeId=place?.id||null}addEvent(s,{...event,placeId,placeName:event.place,evidence:{...evidenceBase,quote:norm(event.evidenceQuote)}},"Local AI");job.addedEvents++}}catch(error){job.errors.push({documentId:p.documentId,pageNumber:p.pageNumber,message:error instanceof Error?error.message:String(error)})}}job.status=job.errors.length===all.length&&all.length?"Failed":"Completed";job.completedAt=now();save(data.projectPath,s);return {success:job.status!=="Failed",message:`AI suggested ${job.addedEvents} event(s) and ${job.addedPlaces} place(s) from ${all.length} page(s).${job.errors.length?` ${job.errors.length} page(s) failed.`:""}`,store:s,analytics:analytics(s),errors:job.errors}});
 ipcMain.handle("timeline:export",async(_,{projectPath})=>{const r=await dialog.showSaveDialog({title:"Export Timeline & Narratives",defaultPath:"timeline-narratives.json",filters:[{name:"JSON",extensions:["json"]}]});if(r.canceled||!r.filePath)return {success:false,message:"Export cancelled."};fs.writeFileSync(r.filePath,JSON.stringify(readStore(projectPath),null,2));return {success:true,message:"Timeline and narratives exported.",filePath:r.filePath}});
 ipcMain.handle("timeline:openFile",async(_,p)=>shell.openPath(p));
}
