import {useEffect,useMemo,useState} from "react";
import {useLocation,useNavigate} from "react-router-dom";
import "./PublicationValidatorPage.css";
type Any=any;
export default function PublicationValidatorPage(){
 const location=useLocation(),navigate=useNavigate(),params=new URLSearchParams(location.search),workspacePath=params.get("workspace")||"",editionId=params.get("edition")||"";
 const [report,setReport]=useState<Any|null>(null),[message,setMessage]=useState("Loading validation report…"),[busy,setBusy]=useState(false),[severity,setSeverity]=useState("All"),[category,setCategory]=useState("All");
 const load=async()=>{if(!workspacePath||!editionId)return setMessage("Missing workspace or edition.");const r=await window.ocrStudio.getEditionValidation({workspacePath,editionId});setMessage(r.message);if(r.success)setReport(r.report)};
 useEffect(()=>{void load()},[workspacePath,editionId]);
 const run=async()=>{setBusy(true);setMessage("Running publication checks…");const r=await window.ocrStudio.runEditionValidation({workspacePath,editionId});setBusy(false);setMessage(r.message);if(r.success)setReport(r.report)};
 const exportReport=async(format:string)=>{const r=await window.ocrStudio.exportEditionValidation({workspacePath,editionId,format});setMessage(r.message);if(r.success&&r.filePath)await window.ocrStudio.openEditionValidation(r.filePath)};
 const categories=useMemo(()=>["All",...new Set((report?.issues||[]).map((x:Any)=>x.category))],[report]);
 const issues=(report?.issues||[]).filter((x:Any)=>(severity==="All"||x.severity===severity)&&(category==="All"||x.category===category));
 const scoreClass=report?.readiness>=90?"good":report?.readiness>=75?"warn":"bad";
 return <div className="pv-page"><header className="pv-hero"><div><button onClick={()=>navigate("/editions")}>← Editions</button><span>Phase 10.0A · Milestone 5</span><h2>Publication Validator</h2><p>Compile scholarly quality, completeness and publication readiness before export.</p></div><div className="pv-actions"><button className="primary" onClick={run} disabled={busy}>{busy?"Validating…":"Run validation"}</button><button onClick={()=>exportReport("html")} disabled={!report}>Export HTML</button><button onClick={()=>exportReport("json")} disabled={!report}>Export JSON</button></div></header>
 <section className="pv-message">{message}</section>
 {!report?<section className="pv-empty"><div>✓</div><h3>No validation report yet</h3><p>Run the validator to inspect the critical text, structure, apparatus, editorial decisions, evidence, translations, AI review and metadata.</p><button onClick={run} disabled={busy}>Run first validation</button></section>:<>
 <section className="pv-overview"><article className={`pv-score ${scoreClass}`}><div className="ring" style={{"--score":`${report.readiness*3.6}deg`} as any}><span>{report.readiness}%</span></div><div><small>Publication readiness</small><h3>{report.status}</h3><p>Generated {new Date(report.generatedAt).toLocaleString()}</p></div></article><div className="pv-counts">{[["Passed",report.counts.passed,"pass"],["Blockers",report.counts.blockers,"blocker"],["Warnings",report.counts.warnings,"warning"],["Info",report.counts.info,"info"]].map(([l,v,c])=><article className={String(c)} key={String(l)}><strong>{v}</strong><span>{l}</span></article>)}</div></section>
 <section className="pv-grid"><div className="pv-panel"><header><h3>Quality dimensions</h3><span>Weighted readiness score</span></header><div className="pv-bars">{Object.entries(report.scores||{}).map(([name,value]:any)=><article key={name}><div><span>{name}</span><b>{value}%</b></div><i><em style={{width:`${value}%`}}/></i><small>Weight {report.weights?.[name]||0}%</small></article>)}</div></div><div className="pv-panel"><header><h3>Publication checklist</h3><span>{(report.checklist||[]).filter((x:Any)=>x.complete).length}/{(report.checklist||[]).length} complete</span></header><div className="pv-checklist">{(report.checklist||[]).map((x:Any)=><article className={x.complete?"done":"pending"} key={x.label}><b>{x.complete?"✓":"○"}</b><span>{x.label}</span></article>)}</div></div></section>
 {Object.keys(report.translationCoverage||{}).length>0&&<section className="pv-panel pv-translations"><header><h3>Parallel-language coverage</h3><span>Across {report.summary.verses} verses</span></header><div>{Object.entries(report.translationCoverage).map(([lang,value]:any)=><article key={lang}><strong>{value}%</strong><span>{lang}</span><i><em style={{width:`${value}%`}}/></i></article>)}</div></section>}
 <section className="pv-panel pv-issues"><header><div><h3>Validation issues</h3><span>{issues.length} shown · {(report.issues||[]).length} total</span></div><div className="pv-filters"><select value={severity} onChange={e=>setSeverity(e.target.value)}><option>All</option><option>Blocker</option><option>Warning</option><option>Info</option></select><select value={category} onChange={e=>setCategory(e.target.value)}>{categories.map(x=><option key={String(x)}>{String(x)}</option>)}</select></div></header>{!issues.length?<div className="pv-clear">No issues match these filters.</div>:<div className="pv-issue-list">{issues.map((x:Any)=><article key={x.id}><span className={`badge ${x.severity.toLowerCase()}`}>{x.severity}</span><div><header><b>{x.title}</b><small>{x.category}</small></header><p>{x.detail}</p><footer><span>📍 {x.location}</span>{x.suggestedFix&&<span>→ {x.suggestedFix}</span>}</footer></div></article>)}</div>}</section>
 </>}</div>
}
