import {useEffect,useMemo,useState} from 'react';
import {getProjects} from '../../services/projectStorage';
import './CriticalApparatusPage.css';
export default function CriticalApparatusPage(){
 const [workspaces,setWorkspaces]=useState<string[]>([]),[workspacePath,setWorkspacePath]=useState(''),[data,setData]=useState<any>({entries:[],settings:{},summary:{}}),[message,setMessage]=useState('Select a workspace.'),[status,setStatus]=useState('All'),[query,setQuery]=useState(''),[selected,setSelected]=useState<any>(null),[includeDrafts,setIncludeDrafts]=useState(false);
 useEffect(()=>{void getProjects().then(ps=>{const w=[...new Set(ps.map(p=>p.workspacePath).filter(Boolean))] as string[];setWorkspaces(w);if(w[0])setWorkspacePath(w[0])})},[]);
 const load=async()=>{if(!workspacePath)return;const r=await window.ocrStudio.getCriticalApparatus({workspacePath});setData(r);setMessage(r.message)};
 useEffect(()=>{void load()},[workspacePath]);
 const rows=useMemo(()=>(data.entries||[]).filter((e:any)=>(status==='All'||(status==='Included'?!e.include===false:e.status===status))&&(!query||`${e.book} ${e.chapter} ${e.verse} ${e.lemma} ${e.note}`.toLowerCase().includes(query.toLowerCase()))),[data,status,query]);
 const save=async(entry:any)=>{const r=await window.ocrStudio.saveCriticalApparatusEntry({workspacePath,entry});setMessage(r.message);setSelected(null);await load()};
 const exportIt=async(format:string)=>{const r=await window.ocrStudio.exportCriticalApparatus({workspacePath,format,options:{includeDrafts}});setMessage(r.message);if(r.success)await window.ocrStudio.openCriticalApparatusExport(r.filePath)};
 const saveSettings=async()=>{const r=await window.ocrStudio.saveCriticalApparatusSettings({workspacePath,settings:data.settings});setMessage(r.message);await load()};
 return <div className="ap-page"><header className="ap-hero"><div><span>Phase 10B · Milestone 5</span><h2>Critical Apparatus Generator</h2><p>Transform saved witness collations into a reviewable, publication-ready critical apparatus.</p></div><button onClick={()=>void load()}>Regenerate</button></header>
 <section className="ap-toolbar"><label>Workspace<select value={workspacePath} onChange={e=>setWorkspacePath(e.target.value)}>{workspaces.map(w=><option key={w}>{w}</option>)}</select></label><span>{message}</span></section>
 <section className="ap-stats"><article><b>{data.summary?.total||0}</b><span>Variant locations</span></article><article><b>{data.summary?.approved||0}</b><span>Approved</span></article><article><b>{data.summary?.draft||0}</b><span>Draft</span></article><article><b>{data.summary?.excluded||0}</b><span>Excluded</span></article></section>
 <div className="ap-grid"><section className="ap-panel"><div className="ap-head"><h3>Apparatus entries</h3><div><input placeholder="Search location or lemma" value={query} onChange={e=>setQuery(e.target.value)}/><select value={status} onChange={e=>setStatus(e.target.value)}><option>All</option><option>Draft</option><option>Approved</option><option>Needs Review</option></select></div></div>{rows.length===0?<p>No variant locations found. Create and save witness collations first.</p>:rows.map((e:any)=><article className="ap-entry" key={e.key}><div><div className="ap-loc">{[e.book,e.chapter,e.verse].filter(Boolean).join('.')} <em>{e.variantType}</em></div><b>{e.lemma||'No adopted lemma'}</b><p>{(e.readings||[]).map((r:any)=>`${r.text||'om.'} ${r.witnesses.join(' ')}`).join(' · ')}</p>{e.note&&<small>{e.note}</small>}</div><div><span className={`ap-status ${String(e.status).toLowerCase().replace(' ','-')}`}>{e.status}</span><button onClick={()=>setSelected({...e})}>Review</button></div></article>)}</section>
 <aside className="ap-panel ap-settings"><h3>Publication settings</h3><label>Title<input value={data.settings?.title||''} onChange={e=>setData({...data,settings:{...data.settings,title:e.target.value}})}/></label><label>Display style<select value={data.settings?.style||'compact'} onChange={e=>setData({...data,settings:{...data.settings,style:e.target.value}})}><option value="compact">Compact</option><option value="expanded">Expanded</option></select></label><button onClick={saveSettings}>Save settings</button><hr/><label className="check"><input type="checkbox" checked={includeDrafts} onChange={e=>setIncludeDrafts(e.target.checked)}/> Include drafts in exports</label><div className="ap-exports"><button onClick={()=>exportIt('html')}>HTML</button><button onClick={()=>exportIt('tei')}>TEI XML</button><button onClick={()=>exportIt('csv')}>CSV</button><button onClick={()=>exportIt('json')}>JSON</button></div></aside></div>
 {selected&&<div className="ap-modal"><div><h3>Review apparatus entry</h3><label>Lemma<textarea value={selected.lemma||''} onChange={e=>setSelected({...selected,lemma:e.target.value})}/></label><label>Status<select value={selected.status} onChange={e=>setSelected({...selected,status:e.target.value})}><option>Draft</option><option>Needs Review</option><option>Approved</option></select></label><label>Editorial note<textarea value={selected.note||''} onChange={e=>setSelected({...selected,note:e.target.value})}/></label><label className="check"><input type="checkbox" checked={selected.include!==false} onChange={e=>setSelected({...selected,include:e.target.checked})}/> Include in publication</label><div><button onClick={()=>setSelected(null)}>Cancel</button><button onClick={()=>void save(selected)}>Save entry</button></div></div></div>}
 </div>
}
