import { useEffect,useMemo,useState } from "react";
import "./TimelineNarrativePage.css";

type Evidence={documentName?:string;documentId?:number;pageNumber?:number;excerpt?:string;quote?:string};
type Event={id:string;title:string;description:string;participants:string[];placeId?:string|null;placeName?:string;relativeOrder?:string;chronology:number;status:string;confidence:number;source:string;evidence?:Evidence|null};
type Place={id:string;name:string;aliases:string[];description:string;latitude:number|null;longitude:number|null;status:string;confidence:number;evidence:Evidence[]};
type Thread={id:string;title:string;description:string;eventIds:string[];notes:string};
const blank={events:[],places:[],threads:[],reviewQueue:[],extractionJobs:[]};
export default function TimelineNarrativePage(){
 const [workspace,setWorkspace]=useState<any>({projects:[],totals:{}}),[projectPath,setProjectPath]=useState("");
 const [store,setStore]=useState<any>(blank),[analytics,setAnalytics]=useState<any>({});
 const [tab,setTab]=useState<"timeline"|"map"|"threads"|"review">("timeline"),[message,setMessage]=useState(""),[busy,setBusy]=useState(false);
 const [selectedEvent,setSelectedEvent]=useState<Event|null>(null),[selectedPlace,setSelectedPlace]=useState<Place|null>(null),[selectedThread,setSelectedThread]=useState<Thread|null>(null);
 const loadProject=async(p:string)=>{const r=await window.ocrStudio.getProjectTimeline({projectPath:p});setStore(r.store||blank);setAnalytics(r.analytics||{});setSelectedEvent(null);setSelectedPlace(null);setSelectedThread(null)};
 const loadWorkspace=async()=>{const r=await window.ocrStudio.getTimelineWorkspace();setWorkspace(r);if(!projectPath&&r.projects?.[0]){setProjectPath(r.projects[0].projectPath);await loadProject(r.projects[0].projectPath)}};
 useEffect(()=>{void loadWorkspace()},[]);
 const refresh=(r:any)=>{if(r.store)setStore(r.store);if(r.analytics)setAnalytics(r.analytics);setMessage(r.message||"")};
 const events=useMemo(()=>[...store.events].sort((a:any,b:any)=>a.chronology-b.chronology||String(a.createdAt).localeCompare(String(b.createdAt))),[store.events]);
 const placeName=(e:Event)=>store.places.find((p:Place)=>p.id===e.placeId)?.name||e.placeName||"Unlocated";
 const addEvent=async()=>{const title=prompt("Event title");if(!title)return;const description=prompt("Description","")||"";const participants=(prompt("Participants, comma separated","")||"").split(",").map(x=>x.trim()).filter(Boolean);const placeText=prompt("Place name (optional)","")||"";let placeId=null;if(placeText){let p=store.places.find((x:Place)=>x.name.toLowerCase()===placeText.toLowerCase());if(!p){const r=await window.ocrStudio.addTimelinePlace({projectPath,name:placeText,description:"",aliases:[]});refresh(r);p=r.store.places.find((x:Place)=>x.name.toLowerCase()===placeText.toLowerCase())}placeId=p?.id||null}refresh(await window.ocrStudio.addTimelineEvent({projectPath,title,description,participants,placeId,placeName:placeText,relativeOrder:prompt("Relative chronology note","")||"",chronology:events.length+1}))};
 const addPlace=async()=>{const name=prompt("Place name");if(!name)return;refresh(await window.ocrStudio.addTimelinePlace({projectPath,name,description:prompt("Description","")||"",aliases:(prompt("Aliases, comma separated","")||"").split(",").map(x=>x.trim()).filter(Boolean),latitude:prompt("Latitude (optional)","")||null,longitude:prompt("Longitude (optional)","")||null}))};
 const editPlace=async(p:Place)=>{refresh(await window.ocrStudio.updateTimelinePlace({projectPath,placeId:p.id,name:prompt("Place name",p.name)||p.name,description:prompt("Description",p.description)||"",aliases:(prompt("Aliases, comma separated",p.aliases.join(", "))||"").split(",").map(x=>x.trim()).filter(Boolean),latitude:prompt("Latitude",p.latitude?.toString()||"")||null,longitude:prompt("Longitude",p.longitude?.toString()||"")||null}))};
 const createThread=async()=>{const title=prompt("Narrative thread title");if(!title)return;refresh(await window.ocrStudio.createNarrativeThread({projectPath,title,description:prompt("Description","")||""}))};
 const toggleThreadEvent=async(t:Thread,eventId:string)=>{const ids=t.eventIds.includes(eventId)?t.eventIds.filter(x=>x!==eventId):[...t.eventIds,eventId];const r=await window.ocrStudio.updateNarrativeThread({projectPath,threadId:t.id,eventIds:ids});refresh(r);setSelectedThread(r.store.threads.find((x:Thread)=>x.id===t.id)||null)};
 const moveThreadEvent=async(t:Thread,index:number,delta:number)=>{const ids=[...t.eventIds],next=index+delta;if(next<0||next>=ids.length)return;[ids[index],ids[next]]=[ids[next],ids[index]];const r=await window.ocrStudio.updateNarrativeThread({projectPath,threadId:t.id,eventIds:ids});refresh(r);setSelectedThread(r.store.threads.find((x:Thread)=>x.id===t.id)||null)};
 const extractRules=async()=>{setBusy(true);try{refresh(await window.ocrStudio.extractTimelineRules({projectPath,pageLimit:200}));await loadWorkspace()}finally{setBusy(false)}};
 const discover=async()=>{const model=prompt("Ollama model","llama3.2:3b")||"llama3.2:3b",pageLimit=Number(prompt("Pages to analyze","10")||10);setBusy(true);setMessage("Local AI is discovering events and places…");try{refresh(await window.ocrStudio.discoverTimelineWithAi({projectPath,model,pageLimit,endpoint:"http://127.0.0.1:11434"}));await loadWorkspace()}catch(e){setMessage(e instanceof Error?e.message:"AI extraction failed.")}finally{setBusy(false)}};
 const review=async(id:string,decision:string)=>refresh(await window.ocrStudio.reviewTimelineItem({projectPath,reviewId:id,decision,note:decision==="Rejected"?(prompt("Reason","")||""):""}));
 const exportData=async()=>{const r=await window.ocrStudio.exportTimelineNarratives({projectPath});setMessage(r.message);if(r.filePath)await window.ocrStudio.openTimelineFile(r.filePath)};
 const pending=store.reviewQueue.filter((x:any)=>x.status==="Pending");
 return <div className="tn-page">
  <header className="tn-head"><div><p className="eyebrow">PHASE 7.0C</p><h2>Timeline, Geographic & Narrative Explorer</h2><p>Trace events through time and place, assemble scholarly narrative threads, and keep every claim linked to its OCR evidence.</p></div><div className="tn-actions"><button onClick={addEvent}>＋ Event</button><button onClick={addPlace}>＋ Place</button><button onClick={extractRules} disabled={busy}>Extract patterns</button><button className="ai" onClick={discover} disabled={busy}>{busy?"Analyzing…":"✦ Discover with Ollama"}</button><button onClick={exportData}>Export JSON</button></div></header>
  <div className="tn-metrics"><article><b>{workspace.totals?.events||0}</b><span>Events</span></article><article><b>{workspace.totals?.places||0}</b><span>Places</span></article><article><b>{workspace.totals?.threads||0}</b><span>Narrative threads</span></article><article><b>{workspace.totals?.pending||0}</b><span>Needs review</span></article></div>
  <div className="tn-toolbar"><select value={projectPath} onChange={e=>{setProjectPath(e.target.value);void loadProject(e.target.value)}}>{workspace.projects?.map((p:any)=><option key={p.projectPath} value={p.projectPath}>{p.projectName}</option>)}</select><nav>{(["timeline","map","threads","review"] as const).map(x=><button key={x} className={tab===x?"active":""} onClick={()=>setTab(x)}>{x==="timeline"?"Chronology":x==="map"?"Places":x==="threads"?"Narratives":`Review (${pending.length})`}</button>)}</nav></div>
  {message&&<div className="tn-message">{message}</div>}
  {tab==="timeline"&&<div className="timeline-layout"><section className="timeline-list panel"><h3>Chronological Event Timeline <small>{events.length}</small></h3>{events.length===0?<div className="empty">Add events or run extraction to begin the chronology.</div>:events.map((e:Event,i:number)=><button key={e.id} className={`timeline-event ${selectedEvent?.id===e.id?"active":""}`} onClick={()=>setSelectedEvent(e)}><span className="sequence">{i+1}</span><span><b>{e.title}</b><small>{placeName(e)} · {e.status} · {Math.round(e.confidence*100)}%</small><p>{e.description||e.relativeOrder||"No description"}</p></span></button>)}</section><aside className="event-detail panel"><h3>Event Evidence</h3>{selectedEvent?<><h2>{selectedEvent.title}</h2><div className="chips"><span>{selectedEvent.status}</span><span>{selectedEvent.source}</span><span>{placeName(selectedEvent)}</span></div><p>{selectedEvent.description||"No description."}</p><h4>Participants</h4><p>{selectedEvent.participants?.join(", ")||"Not identified"}</p><h4>Chronology</h4><p>{selectedEvent.relativeOrder||`Sequence ${selectedEvent.chronology}`}</p>{selectedEvent.evidence&&<div className="evidence"><b>{selectedEvent.evidence.documentName}</b><span>Page {selectedEvent.evidence.pageNumber}</span>{selectedEvent.evidence.quote&&<blockquote>“{selectedEvent.evidence.quote}”</blockquote>}<p>{selectedEvent.evidence.excerpt}</p></div>}</>:<div className="empty">Select an event to inspect its source evidence.</div>}</aside></div>}
  {tab==="map"&&<div className="map-layout"><section className="map-stage panel"><h3>Local Geographic Canvas</h3><div className="map-canvas">{store.places.map((p:Place,i:number)=>{const left=p.longitude!=null?((p.longitude+180)/360)*88+6:10+(i*17)%78,top=p.latitude!=null?((90-p.latitude)/180)*76+12:18+(i*23)%65;return <button key={p.id} className={`map-pin ${p.status.toLowerCase()}`} style={{left:`${left}%`,top:`${top}%`}} onClick={()=>setSelectedPlace(p)}><i>●</i><span>{p.name}</span></button>})}{store.places.length===0&&<div className="empty map-empty">No places yet. Add one or run AI discovery.</div>}</div></section><aside className="panel place-detail"><h3>Place Record</h3>{selectedPlace?<><h2>{selectedPlace.name}</h2><p>{selectedPlace.description||"No description."}</p><p><b>Aliases:</b> {selectedPlace.aliases.join(", ")||"None"}</p><p><b>Coordinates:</b> {selectedPlace.latitude??"—"}, {selectedPlace.longitude??"—"}</p><p><b>Status:</b> {selectedPlace.status}</p><h4>Related events</h4>{events.filter((e:Event)=>e.placeId===selectedPlace.id||e.placeName===selectedPlace.name).map((e:Event)=><button className="related-event" key={e.id} onClick={()=>{setSelectedEvent(e);setTab("timeline")}}>{e.title}</button>)}<button onClick={()=>editPlace(selectedPlace)}>Edit place</button></>:<div className="empty">Select a place marker to inspect it.</div>}</aside></div>}
  {tab==="threads"&&<div className="threads-layout"><section className="panel thread-list"><div className="section-head"><h3>Narrative Threads</h3><button onClick={createThread}>＋ New thread</button></div>{store.threads.map((t:Thread)=><button key={t.id} className={selectedThread?.id===t.id?"thread active":"thread"} onClick={()=>setSelectedThread(t)}><b>{t.title}</b><small>{t.eventIds.length} events</small><p>{t.description}</p></button>)}{store.threads.length===0&&<div className="empty">Create a narrative such as “The Life of Karna”.</div>}</section><section className="panel thread-builder"><h3>Narrative Builder</h3>{selectedThread?<><h2>{selectedThread.title}</h2><p>{selectedThread.description}</p><div className="thread-sequence">{selectedThread.eventIds.map((id:string,i:number)=>{const e=events.find((x:Event)=>x.id===id);return e?<div className="thread-event" key={id}><b>{i+1}. {e.title}</b><span><button onClick={()=>moveThreadEvent(selectedThread,i,-1)}>↑</button><button onClick={()=>moveThreadEvent(selectedThread,i,1)}>↓</button><button onClick={()=>toggleThreadEvent(selectedThread,id)}>Remove</button></span></div>:null})}</div><h4>Add evidence-backed events</h4><div className="event-picker">{events.filter((e:Event)=>!selectedThread.eventIds.includes(e.id)).map((e:Event)=><button key={e.id} onClick={()=>toggleThreadEvent(selectedThread,e.id)}>＋ {e.title}</button>)}</div></>:<div className="empty">Select a narrative thread to order its events.</div>}</section></div>}
  {tab==="review"&&<section className="panel review-panel"><h3>Event & Place Review Queue</h3>{pending.length===0?<div className="empty">No AI or rule suggestions need review.</div>:pending.map((q:any)=>{const target=q.kind==="Event"?store.events.find((x:Event)=>x.id===q.targetId):store.places.find((x:Place)=>x.id===q.targetId);return <div className="review-row" key={q.id}><span><b>{q.kind}: {target?.title||target?.name||"Unknown"}</b><small>{target?.source} · {Math.round((target?.confidence||0)*100)}% confidence</small></span><div><button onClick={()=>review(q.id,"Approved")}>Approve</button><button onClick={()=>review(q.id,"Rejected")}>Reject</button></div></div>})}</section>}
 </div>
}
