import { useEffect, useMemo, useState } from "react";
import "./EntityIntelligencePage.css";

type Entity={id:string;canonicalName:string;name?:string;type:string;description?:string;alternateNames?:string[];sanskritForm?:string;transliteration?:string;period?:string;editorialStatus?:string;latitude?:number|null;longitude?:number|null;editorialNotes?:string};
type Relationship={id:string;sourceId:string;targetId:string;type:string;confidence:number;approvalStatus:string;evidence?:string;notes?:string};
type Project={projectPath:string;projectName:string};
const entityTypes=["Person","Place","Dynasty","Tribe","River","Mountain","Kingdom","Weapon","Astra","Animal","Deity","Sage","Ritual","Concept","Event","Text"];
const blankEntity={canonicalName:"",type:"Person",description:"",alternateNames:"",sanskritForm:"",transliteration:"",period:"",editorialStatus:"Verified",latitude:"",longitude:"",editorialNotes:""};
export default function EntityIntelligencePage(){
 const [projects,setProjects]=useState<Project[]>([]);const[projectPath,setProjectPath]=useState("");const[entities,setEntities]=useState<Entity[]>([]);const[relationships,setRelationships]=useState<Relationship[]>([]);const[timelines,setTimelines]=useState<any[]>([]);const[maps,setMaps]=useState<any[]>([]);const[metrics,setMetrics]=useState<any>({});const[tab,setTab]=useState("entities");const[query,setQuery]=useState("");const[typeFilter,setTypeFilter]=useState("All");const[form,setForm]=useState<any>(blankEntity);const[message,setMessage]=useState("");const[compareIds,setCompareIds]=useState<string[]>([]);const[comparison,setComparison]=useState<any>(null);
 const api=window.ocrStudio;
 const load=async(p=projectPath)=>{if(!p)return;const r=await api.getEntityIntelligenceProject({projectPath:p});if(r.success){setEntities(r.entities||[]);setRelationships(r.relationships||[]);setTimelines(r.timelines||[]);setMaps(r.maps||[]);setMetrics(r.metrics||{});}};
 useEffect(()=>{(async()=>{const r=await api.getEntityIntelligenceWorkspace();const ps=r.projects||[];setProjects(ps);if(ps[0]){setProjectPath(ps[0].projectPath);await load(ps[0].projectPath)}})()},[]);
 const filtered=useMemo(()=>entities.filter(e=>(typeFilter==="All"||e.type===typeFilter)&&`${e.canonicalName||e.name} ${e.description||""} ${(e.alternateNames||[]).join(" ")}`.toLowerCase().includes(query.toLowerCase())),[entities,typeFilter,query]);
 const name=(id:string)=>entities.find(e=>e.id===id)?.canonicalName||entities.find(e=>e.id===id)?.name||"Unknown";
 const saveEntity=async()=>{if(!form.canonicalName.trim())return setMessage("Canonical name is required.");await api.saveEntityIntelligenceEntity({...form,projectPath,alternateNames:String(form.alternateNames||"").split(",").map((x:string)=>x.trim()).filter(Boolean)});setForm(blankEntity);setMessage("Entity saved.");await load()};
 const editEntity=(e:Entity)=>setForm({...e,alternateNames:(e.alternateNames||[]).join(", "),latitude:e.latitude??"",longitude:e.longitude??""});
 const addRelationship=async()=>{if(entities.length<2)return setMessage("Create at least two entities first.");const sourceId=prompt("Source entity ID",entities[0].id)||"";const targetId=prompt("Target entity ID",entities[1].id)||"";const type=prompt("Relationship type","Related to")||"Related to";const evidence=prompt("Evidence or source passage","")||"";if(!sourceId||!targetId||sourceId===targetId)return;await api.saveEntityIntelligenceRelationship({projectPath,sourceId,targetId,type,evidence,confidence:1,approvalStatus:"Verified"});await load()};
 const addTimeline=async()=>{const title=prompt("Event title");if(!title)return;const dateLabel=prompt("Date or chronological label","Unknown period")||"Unknown period";const ids=prompt("Related entity IDs, comma separated",compareIds.join(","))||"";const description=prompt("Description","")||"";await api.saveEntityTimelineEvent({projectPath,title,dateLabel,entityIds:ids.split(",").map(x=>x.trim()).filter(Boolean),description});await load()};
 const addMap=async()=>{const entityId=prompt("Place entity ID",entities.find(e=>e.type==="Place")?.id||"")||"";const latitude=prompt("Latitude","0");const longitude=prompt("Longitude","0");if(!entityId||latitude===null||longitude===null)return;await api.saveEntityMapPoint({projectPath,entityId,label:name(entityId),latitude:Number(latitude),longitude:Number(longitude)});await load()};
 const compare=async()=>{if(compareIds.length<2)return setMessage("Select at least two entities.");const r=await api.compareKnowledgeEntities({projectPath,entityIds:compareIds});setComparison(r);setTab("compare")};
 const exportGraph=async(format:string)=>{const r=await api.exportEntityIntelligence({projectPath,format});setMessage(r.message);if(r.filePath)await api.openEntityIntelligenceFile(r.filePath)};
 return <div className="ei-page"><header className="ei-head"><div><span>PHASE 10C · MILESTONE 1</span><h2>Knowledge Graph & Entity Intelligence</h2><p>Curate entities, evidence-grounded relationships, timelines, geography, comparison and research metrics.</p></div><div className="ei-actions"><select value={projectPath} onChange={async e=>{setProjectPath(e.target.value);await load(e.target.value)}}>{projects.map(p=><option key={p.projectPath} value={p.projectPath}>{p.projectName}</option>)}</select>{["html","json","csv","graphml","rdf"].map(f=><button key={f} onClick={()=>exportGraph(f)}>Export {f.toUpperCase()}</button>)}</div></header>
 <section className="ei-metrics">{[[metrics.entities,"Entities"],[metrics.relationships,"Relationships"],[metrics.timelineEvents,"Timeline events"],[metrics.mappedPlaces,"Mapped places"],[metrics.unlinked,"Unlinked"],[metrics.components,"Components"]].map(([v,l])=><article key={l}><b>{v||0}</b><span>{l}</span></article>)}</section>
 <nav className="ei-tabs">{["entities","relationships","timeline","geography","compare","analytics"].map(t=><button className={tab===t?"active":""} onClick={()=>setTab(t)} key={t}>{t[0].toUpperCase()+t.slice(1)}</button>)}</nav>{message&&<div className="ei-message">{message}</div>}
 {tab==="entities"&&<div className="ei-entity-grid"><section className="ei-panel"><div className="ei-toolbar"><input placeholder="Search entities…" value={query} onChange={e=>setQuery(e.target.value)}/><select value={typeFilter} onChange={e=>setTypeFilter(e.target.value)}><option>All</option>{entityTypes.map(x=><option key={x}>{x}</option>)}</select></div><div className="ei-list">{filtered.map(e=><button key={e.id} onClick={()=>editEntity(e)}><i>{(e.canonicalName||e.name||"?")[0]}</i><span><b>{e.canonicalName||e.name}</b><small>{e.type} · {e.editorialStatus||"Suggested"}</small></span><code>{e.id}</code></button>)}</div></section><section className="ei-panel ei-form"><h3>{form.id?"Edit entity":"New scholarly entity"}</h3><label>Canonical name<input value={form.canonicalName} onChange={e=>setForm({...form,canonicalName:e.target.value})}/></label><div className="two"><label>Entity type<select value={form.type} onChange={e=>setForm({...form,type:e.target.value})}>{entityTypes.map(x=><option key={x}>{x}</option>)}</select></label><label>Status<select value={form.editorialStatus} onChange={e=>setForm({...form,editorialStatus:e.target.value})}><option>Suggested</option><option>Verified</option><option>Rejected</option></select></label></div><div className="two"><label>Sanskrit form<input value={form.sanskritForm} onChange={e=>setForm({...form,sanskritForm:e.target.value})}/></label><label>Transliteration<input value={form.transliteration} onChange={e=>setForm({...form,transliteration:e.target.value})}/></label></div><label>Alternate spellings<input value={form.alternateNames} onChange={e=>setForm({...form,alternateNames:e.target.value})} placeholder="Comma separated"/></label><label>Description<textarea value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></label><div className="two"><label>Period<input value={form.period} onChange={e=>setForm({...form,period:e.target.value})}/></label><label>Coordinates<input value={`${form.latitude||""}${form.latitude!==""&&form.longitude!==""?", ":""}${form.longitude||""}`} onChange={e=>{const[a,b]=e.target.value.split(",");setForm({...form,latitude:a?.trim()||"",longitude:b?.trim()||""})}} placeholder="lat, lng"/></label></div><label>Editorial notes<textarea value={form.editorialNotes} onChange={e=>setForm({...form,editorialNotes:e.target.value})}/></label><div className="form-actions"><button onClick={saveEntity}>Save entity</button><button onClick={()=>setForm(blankEntity)}>Clear</button>{form.id&&<button className="danger" onClick={async()=>{await api.deleteEntityIntelligenceEntity({projectPath,id:form.id});setForm(blankEntity);await load()}}>Delete</button>}</div></section></div>}
 {tab==="relationships"&&<section className="ei-panel"><div className="section-head"><h3>Scholarly Relationships</h3><button onClick={addRelationship}>＋ Relationship</button></div><table><thead><tr><th>Source</th><th>Relationship</th><th>Target</th><th>Confidence</th><th>Status</th><th>Evidence</th></tr></thead><tbody>{relationships.map(r=><tr key={r.id}><td>{name(r.sourceId)}</td><td>{r.type}</td><td>{name(r.targetId)}</td><td>{Math.round((r.confidence||0)*100)}%</td><td>{r.approvalStatus}</td><td>{r.evidence||"—"}</td></tr>)}</tbody></table></section>}
 {tab==="timeline"&&<section className="ei-panel"><div className="section-head"><h3>Entity Timeline</h3><button onClick={addTimeline}>＋ Event</button></div><div className="timeline">{[...timelines].sort((a,b)=>(a.sortOrder||0)-(b.sortOrder||0)).map(e=><article key={e.id}><time>{e.dateLabel}</time><div><h4>{e.title}</h4><p>{e.description}</p><small>{(e.entityIds||[]).map(name).join(" · ")}</small></div></article>)}</div></section>}
 {tab==="geography"&&<section className="ei-panel"><div className="section-head"><h3>Geographic Explorer</h3><button onClick={addMap}>＋ Map location</button></div><div className="map-stage"><div className="map-grid"/>{maps.map((m,i)=><button key={m.id} className="map-pin" style={{left:`${10+(i*17)%80}%`,top:`${18+(i*23)%68}%`}} title={`${m.latitude}, ${m.longitude}`}><span>●</span>{m.label||name(m.entityId)}</button>)}{!maps.length&&<p>No locations mapped yet.</p>}</div></section>}
 {tab==="compare"&&<section className="ei-panel"><div className="section-head"><h3>Entity Comparison</h3><button onClick={compare}>Compare selected</button></div><div className="compare-picker">{entities.map(e=><label key={e.id}><input type="checkbox" checked={compareIds.includes(e.id)} onChange={x=>setCompareIds(x.target.checked?[...compareIds,e.id]:compareIds.filter(id=>id!==e.id))}/>{e.canonicalName||e.name}<small>{e.type}</small></label>)}</div>{comparison&&<div className="comparison"><h4>{comparison.entities.map((e:Entity)=>e.canonicalName).join(" ↔ ")}</h4><p><b>{comparison.sharedRelationships.length}</b> direct shared relationships</p><p><b>{comparison.sharedEvents.length}</b> shared timeline events</p><div>{comparison.entities.map((e:Entity)=><article key={e.id}><h4>{e.canonicalName}</h4><span>{e.type}</span><p>{e.description||"No description"}</p><small>{e.period||"Period not recorded"}</small></article>)}</div></div>}</section>}
 {tab==="analytics"&&<div className="analytics"><section className="ei-panel"><h3>Most Referenced Entities</h3>{(metrics.mostReferenced||[]).map((x:any,i:number)=><div className="rank" key={x.entity?.id}><b>{i+1}</b><span>{x.entity?.canonicalName||x.entity?.name}<small>{x.entity?.type}</small></span><strong>{x.count}</strong></div>)}</section><section className="ei-panel health"><h3>Knowledge Graph Health</h3><b>{Math.round((metrics.density||0)*10000)/100}%</b><span>graph density</span><b>{metrics.reviewed||0}</b><span>verified entities</span><b>{metrics.pending||0}</b><span>awaiting review</span><b>{metrics.unlinked||0}</b><span>unlinked entities</span><button onClick={async()=>{const n=prompt("Saved view name","Research view")||"Research view";await api.saveEntityGraphView({projectPath,name:n,filters:{query,typeFilter,tab}});setMessage("Graph view saved.")}}>Save current graph view</button></section></div>}
 </div>
}
