import {useEffect,useMemo,useState} from 'react';
import {getProjects} from '../../services/projectStorage';
import './ManuscriptCollationPage.css';
const blankWitness={siglum:'',title:'',repository:'',shelfmark:'',script:'',language:'',material:'',date:'',region:'',provenance:'',condition:'',notes:''};
export default function ManuscriptCollationPage(){
 const [workspaces,setWorkspaces]=useState<string[]>([]),[workspacePath,setWorkspacePath]=useState(''),[data,setData]=useState<any>({witnesses:[],groups:[],collations:[],variants:[],editions:[]}),[tab,setTab]=useState('witnesses'),[message,setMessage]=useState('Select a workspace.'),[witness,setWitness]=useState<any>(blankWitness),[group,setGroup]=useState<any>({name:'',description:'',witnessIds:[]}),[editionId,setEditionId]=useState(''),[selected,setSelected]=useState<string[]>([]),[name,setName]=useState('New witness collation'),[collation,setCollation]=useState<any>(null),[variantType,setVariantType]=useState('All');
 useEffect(()=>{void getProjects().then(ps=>{const w=[...new Set(ps.map(p=>p.workspacePath).filter(Boolean))] as string[];setWorkspaces(w);if(w[0])setWorkspacePath(w[0])})},[]);
 const load=async()=>{if(!workspacePath)return;const r=await window.ocrStudio.getManuscriptWorkspace({workspacePath});setData(r);setMessage(r.message);if(!editionId&&r.editions?.[0])setEditionId(r.editions[0].id)};
 useEffect(()=>{void load()},[workspacePath]);
 const saveWitness=async()=>{const r=await window.ocrStudio.saveManuscriptWitness({workspacePath,witness});setMessage(r.message);if(r.success){setWitness(blankWitness);await load()}};
 const saveGroup=async()=>{const r=await window.ocrStudio.saveWitnessGroup({workspacePath,group});setMessage(r.message);if(r.success){setGroup({name:'',description:'',witnessIds:[]});await load()}};
 const build=async()=>{const r=await window.ocrStudio.buildWitnessCollation({workspacePath,editionId,witnessIds:selected,name});setMessage(r.message);if(r.success){setCollation(r.collation);setTab('collation')}};
 const saveCollation=async()=>{const r=await window.ocrStudio.saveWitnessCollation({workspacePath,collation:{...collation,name}});setMessage(r.message);if(r.success){setCollation(r.collation);await load()}};
 const exportIt=async(format:string)=>{const r=await window.ocrStudio.exportWitnessCollation({workspacePath,collation:{...collation,name},format});setMessage(r.message);if(r.success)await window.ocrStudio.openWitnessExport(r.filePath)};
 const variants=useMemo(()=>data.variants?.filter((v:any)=>variantType==='All'||v.type===variantType)||[],[data.variants,variantType]);
 return <div className="mw-page"><header className="mw-hero"><div><span>Phase 10B · Milestone 3</span><h2>Manuscript Witness & Collation Workbench</h2><p>Catalog witnesses, organize manuscript families, align readings, and create evidence-rich collations.</p></div><button disabled={selected.length<2||!editionId} onClick={build}>Build collation</button></header>
 <section className="mw-toolbar"><label>Workspace<select value={workspacePath} onChange={e=>setWorkspacePath(e.target.value)}>{workspaces.map(w=><option key={w}>{w}</option>)}</select></label><span>{message}</span></section>
 <nav className="mw-tabs">{[['witnesses','Witness catalog'],['groups','Witness groups'],['collation','Collation workspace'],['variants','Variant browser']].map(([id,label])=><button className={tab===id?'active':''} onClick={()=>setTab(id)} key={id}>{label}</button>)}</nav>
 {tab==='witnesses'&&<div className="mw-grid"><section className="mw-card form"><h3>{witness.id?'Edit witness':'Add manuscript witness'}</h3>{['siglum','title','repository','shelfmark','script','language','material','date','region','provenance','condition'].map(k=><label key={k}>{k.replace(/([A-Z])/g,' $1')}<input value={witness[k]||''} onChange={e=>setWitness({...witness,[k]:e.target.value})}/></label>)}<label>Notes<textarea value={witness.notes||''} onChange={e=>setWitness({...witness,notes:e.target.value})}/></label><button onClick={saveWitness}>Save witness</button></section><section className="mw-list"><h3>Witnesses ({data.witnesses?.length||0})</h3>{data.witnesses?.map((w:any)=><article key={w.id}><div><b>{w.siglum} · {w.title||'Untitled witness'}</b><small>{[w.repository,w.shelfmark,w.script,w.date,w.region].filter(Boolean).join(' · ')||'Metadata not supplied'}</small><p>{w.notes}</p></div><div><button onClick={()=>setWitness(w)}>Edit</button><button className="danger" onClick={async()=>{await window.ocrStudio.deleteManuscriptWitness({workspacePath,id:w.id});await load()}}>Delete</button></div></article>)}</section></div>}
 {tab==='groups'&&<div className="mw-grid"><section className="mw-card form"><h3>Create witness group</h3><label>Name<input value={group.name} onChange={e=>setGroup({...group,name:e.target.value})}/></label><label>Description<textarea value={group.description} onChange={e=>setGroup({...group,description:e.target.value})}/></label><div className="checks">{data.witnesses?.map((w:any)=><label key={w.id}><input type="checkbox" checked={group.witnessIds.includes(w.id)} onChange={()=>setGroup({...group,witnessIds:group.witnessIds.includes(w.id)?group.witnessIds.filter((x:string)=>x!==w.id):[...group.witnessIds,w.id]})}/>{w.siglum}</label>)}</div><button onClick={saveGroup}>Save group</button></section><section className="mw-list"><h3>Witness families</h3>{data.groups?.map((g:any)=><article key={g.id}><div><b>{g.name}</b><p>{g.description}</p><small>{g.witnessIds.map((id:string)=>data.witnesses.find((w:any)=>w.id===id)?.siglum).filter(Boolean).join(', ')||'No witnesses assigned'}</small></div><button className="danger" onClick={async()=>{await window.ocrStudio.deleteWitnessGroup({workspacePath,id:g.id});await load()}}>Delete</button></article>)}</section></div>}
 {tab==='collation'&&<div className="mw-collation"><section className="mw-setup"><label>Edition<select value={editionId} onChange={e=>setEditionId(e.target.value)}>{data.editions?.map((e:any)=><option value={e.id} key={e.id}>{e.title} · v{e.version}</option>)}</select></label><label>Collation name<input value={name} onChange={e=>setName(e.target.value)}/></label><div className="checks">{data.witnesses?.map((w:any)=><label key={w.id}><input type="checkbox" checked={selected.includes(w.id)} onChange={()=>setSelected(s=>s.includes(w.id)?s.filter(x=>x!==w.id):[...s,w.id])}/>{w.siglum}</label>)}</div><button onClick={build} disabled={selected.length<2}>Align witnesses</button>{data.collations?.map((c:any)=><button className="saved" key={c.id} onClick={()=>{setCollation(c);setName(c.name);setEditionId(c.editionId);setSelected(c.witnessIds)}}>{c.name} · {c.summary?.variantCount||0} variants</button>)}</section>{!collation?<section className="mw-empty"><b>≋</b><h3>No collation loaded</h3><p>Select an edition and at least two witnesses, then align the readings.</p></section>:<section className="mw-results"><div className="mw-stats"><article><b>{collation.summary.verseCount}</b><span>Verse locations</span></article><article><b>{collation.summary.witnessCount}</b><span>Witnesses</span></article><article><b>{collation.summary.variantCount}</b><span>Variants</span></article><article><b>{collation.summary.agreementCount}</b><span>Agreements</span></article></div><div className="mw-actions"><button onClick={saveCollation}>Save</button><button onClick={()=>exportIt('html')}>HTML</button><button onClick={()=>exportIt('csv')}>CSV</button><button onClick={()=>exportIt('json')}>JSON</button></div><div className="mw-table"><table><thead><tr><th>Location / adopted</th>{collation.witnesses.map((w:any)=><th key={w.id}>{w.siglum}<small>{w.title}</small></th>)}</tr></thead><tbody>{collation.rows.map((r:any)=><tr key={r.key}><td><b>{r.key}</b><textarea value={r.adopted} onChange={e=>setCollation({...collation,rows:collation.rows.map((x:any)=>x.key===r.key?{...x,adopted:e.target.value}:x)})}/></td>{r.readings.map((rd:any)=><td key={rd.witnessId}><textarea value={rd.text} onChange={e=>setCollation({...collation,rows:collation.rows.map((x:any)=>x.key===r.key?{...x,readings:x.readings.map((q:any)=>q.witnessId===rd.witnessId?{...q,text:e.target.value}:q)}:x)})}/><small>{r.variants.find((v:any)=>v.witnessId===rd.witnessId)?.type||'Agreement'}</small></td>)}</tr>)}</tbody></table></div></section>}</div>}
 {tab==='variants'&&<section className="mw-variants"><div><h3>Workspace variant index</h3><select value={variantType} onChange={e=>setVariantType(e.target.value)}>{['All','Orthographic','Substitution','Lexical','Addition','Omission','Transposition'].map(x=><option key={x}>{x}</option>)}</select></div>{variants.length===0?<p>No indexed variants yet. Save a collation to build the index.</p>:variants.map((v:any)=><article key={v.id}><b>{v.location} · {v.type}</b><span>{v.siglum}: {v.reading||'∅'}</span><small>Adopted: {v.adopted||'—'} · {v.collationName}</small></article>)}</section>}
 </div>
}
