import { useEffect, useState } from "react";
import { getProjects } from "../../services/projectStorage";
import type { Collection } from "../../types/Collection";
import "./ManuscriptAssistantPage.css";

type Settings={endpoint:string;model:string;temperature:number;evidenceLimit:number};
type Evidence={id:string;projectId:number;projectName:string;documentName:string;pageNumber:number;language:string;averageConfidence:number;snippet:string};
type Msg={id:string;role:"user"|"assistant";content:string;model?:string;evidence?:Evidence[]};
type Conversation={id:string;title:string;messages:Msg[]};
type Summary={id:string;title:string;updatedAt:string;messageCount:number};

export default function ManuscriptAssistantPage(){
 const [workspacePath,setWorkspacePath]=useState(""); const [workspaces,setWorkspaces]=useState<string[]>([]); const [collections,setCollections]=useState<Collection[]>([]); const [collectionId,setCollectionId]=useState("");
 const [metadata,setMetadata]=useState<any>(null); const [diagnostics,setDiagnostics]=useState<any>(null); const [indexPath,setIndexPath]=useState(""); const [settings,setSettings]=useState<Settings>({endpoint:"http://127.0.0.1:11434",model:"llama3.2:3b",temperature:.2,evidenceLimit:8});
 const [models,setModels]=useState<any[]>([]); const [ready,setReady]=useState(false); const [question,setQuestion]=useState(""); const [conversation,setConversation]=useState<Conversation|null>(null); const [history,setHistory]=useState<Summary[]>([]); const [message,setMessage]=useState("Build the index and connect Ollama."); const [busy,setBusy]=useState(false); const [showSettings,setShowSettings]=useState(false);
 useEffect(()=>{void getProjects().then(ps=>{const ws=[...new Set(ps.map(p=>p.workspacePath).filter(Boolean))] as string[];setWorkspaces(ws);if(ws[0])setWorkspacePath(ws[0]);});},[]);
 useEffect(()=>{if(!workspacePath)return;setConversation(null);void Promise.all([window.ocrStudio.getManuscriptIndexStatus({workspacePath}),window.ocrStudio.listCollections({workspacePath}),window.ocrStudio.getAssistantSettings({workspacePath}),window.ocrStudio.listAssistantConversations({workspacePath})]).then(([i,c,s,h])=>{setMetadata(i.metadata);setIndexPath((i as any).indexPath||"");setDiagnostics(null);setCollections(c.collections||[]);setSettings(s.settings||settings);setHistory(h.conversations||[]);setMessage(i.message);setReady(false);});},[workspacePath]);
 const refresh=async()=>setHistory((await window.ocrStudio.listAssistantConversations({workspacePath})).conversations||[]);
 const build=async()=>{setBusy(true);try{const r:any=await window.ocrStudio.buildManuscriptIndex({workspacePath,chunkWords:120,overlap:25});setMetadata(r.metadata);setDiagnostics(r.diagnostics||null);setIndexPath(r.indexPath||"");setMessage(r.message);}catch(error){setMessage(error instanceof Error?error.message:"Index build failed.");}finally{setBusy(false)}};
 const test=async()=>{setBusy(true);const r=await window.ocrStudio.checkOllama({endpoint:settings.endpoint});setReady(r.success);setModels(r.models||[]);if(r.models?.length&&!r.models.some((m:any)=>m.name===settings.model))setSettings({...settings,model:r.models[0].name});setMessage(r.message);setBusy(false)};
 const save=async()=>{const r=await window.ocrStudio.saveAssistantSettings({workspacePath,settings});setSettings(r.settings||settings);setMessage(r.message);setShowSettings(false)};
 const ask=async()=>{if(!question.trim())return;setBusy(true);const r=await window.ocrStudio.askManuscriptAssistant({workspacePath,collectionId:collectionId||null,conversationId:conversation?.id||null,question,settings});setMessage(r.message);if(r.conversation){setConversation(r.conversation);setQuestion("");await refresh()}setBusy(false)};
 const open=async(id:string)=>{const r=await window.ocrStudio.getAssistantConversation({workspacePath,conversationId:id});if(r.conversation)setConversation(r.conversation)};
 const remove=async(id:string)=>{await window.ocrStudio.deleteAssistantConversation({workspacePath,conversationId:id});if(conversation?.id===id)setConversation(null);await refresh()};
 return <div className="manuscript-assistant-page">
  <header className="assistant-hero"><div><span className="assistant-eyebrow">Phase 6E.2.5B · Ollama RAG</span><h2>AI Manuscript Assistant</h2><p>Private, locally composed answers with page-level manuscript citations.</p></div><div className={`assistant-shield ${ready?"ready":"offline"}`}>◈ {ready?"Ollama connected":"Local model offline"}</div></header>
  <div className="assistant-workspace-bar"><label>Workspace<select value={workspacePath} onChange={e=>setWorkspacePath(e.target.value)}>{workspaces.map(w=><option key={w}>{w}</option>)}</select></label><label>Scope<select value={collectionId} onChange={e=>setCollectionId(e.target.value)}><option value="">Entire workspace</option>{collections.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><button className="assistant-secondary" onClick={test}>Test Ollama</button><button className="assistant-secondary" onClick={()=>setShowSettings(!showSettings)}>Settings</button><button className="assistant-primary" onClick={build}>{metadata?"Rebuild Index":"Build Index"}</button></div>
  {showSettings&&<section className="assistant-panel"><div className="assistant-controls"><label>Endpoint<input value={settings.endpoint} onChange={e=>setSettings({...settings,endpoint:e.target.value})}/></label><label>Model{models.length?<select value={settings.model} onChange={e=>setSettings({...settings,model:e.target.value})}>{models.map(m=><option key={m.name}>{m.name}</option>)}</select>:<input value={settings.model} onChange={e=>setSettings({...settings,model:e.target.value})}/>}</label><label>Temperature<input type="number" step=".1" min="0" max="2" value={settings.temperature} onChange={e=>setSettings({...settings,temperature:Number(e.target.value)})}/></label><label>Sources<input type="number" min="3" max="20" value={settings.evidenceLimit} onChange={e=>setSettings({...settings,evidenceLimit:Number(e.target.value)})}/></label><button className="assistant-primary" onClick={save}>Save</button></div></section>}
  {metadata&&<div className="assistant-stats"><div><strong>{metadata.projects}</strong><span>Projects</span></div><div><strong>{metadata.documents}</strong><span>Documents</span></div><div><strong>{metadata.pages}</strong><span>Pages</span></div><div><strong>{metadata.chunks}</strong><span>Passages</span></div></div>}
  <div className="assistant-message">{message}{indexPath&&<button className="assistant-secondary" style={{marginLeft:12}} onClick={()=>void window.ocrStudio.openManuscriptIndexPath(indexPath)}>Open Index File</button>}</div>{diagnostics&&<section className="assistant-panel"><h3>Index diagnostics</h3><p>Scanned {diagnostics.projects} projects, {diagnostics.documents} documents and {diagnostics.pages} OCR pages. Created {diagnostics.chunks} passages. Warnings: {diagnostics.warnings?.length||0}.</p>{diagnostics.projectReports?.length>0&&<div style={{overflowX:"auto"}}><table style={{width:"100%",borderCollapse:"collapse"}}><thead><tr><th>Project</th><th>Source</th><th>Documents</th><th>Pages</th><th>Words</th><th>Passages</th></tr></thead><tbody>{diagnostics.projectReports.map((r:any)=><tr key={r.projectPath}><td>{r.projectName}</td><td>{r.source}</td><td>{r.documents}</td><td>{r.pages}</td><td>{r.words}</td><td>{r.passages}</td></tr>)}</tbody></table></div>}</section>}
  <div className="assistant-chat-layout"><aside className="conversation-sidebar"><div className="conversation-header"><h3>Conversations</h3><button onClick={()=>setConversation(null)}>＋</button></div>{history.map(h=><div className={`conversation-item ${conversation?.id===h.id?"active":""}`} key={h.id}><button className="conversation-open" onClick={()=>void open(h.id)}><strong>{h.title}</strong><span>{h.messageCount} messages</span></button><button className="conversation-delete" onClick={()=>void remove(h.id)}>×</button></div>)}</aside>
  <main className="chat-main"><div className="chat-thread">{!conversation?.messages.length&&<div className="assistant-empty"><div>✦</div><h3>Ask your manuscript library</h3><p>Answers use only retrieved OCR evidence and include citations.</p></div>}{conversation?.messages.map(m=><article className={`chat-message ${m.role}`} key={m.id}><div className="chat-role">{m.role==="user"?"You":`Local Assistant${m.model?` · ${m.model}`:""}`}</div><div className="chat-content">{m.content}</div>{m.evidence?.length&&<details><summary>{m.evidence.length} cited passages</summary>{m.evidence.map((e,i)=><div className="evidence-row" key={e.id}><b>[{i+1}] {e.projectName} › {e.documentName} › Page {e.pageNumber}</b><p>{e.snippet}</p></div>)}</details>}</article>)}{busy&&<div className="assistant-thinking">Reading manuscript evidence…</div>}</div><div className="chat-composer"><textarea value={question} onChange={e=>setQuestion(e.target.value)} onKeyDown={e=>{if(e.key==="Enter"&&!e.shiftKey){e.preventDefault();void ask()}}} placeholder="Ask a question about the manuscripts…"/><button className="assistant-primary" disabled={!ready||!metadata||busy||!question.trim()} onClick={ask}>Ask Local AI</button><small>Enter to send · Shift+Enter for a new line</small></div></main></div>
 </div>
}
