import { useEffect, useMemo, useState } from "react";
import "./ResearchWorkbenchPage.css";

type Evidence = { id:string; type:string; title:string; excerpt:string; projectName:string; projectPath:string; documentName:string; pageNumber:number|null; notes:string };
type Notebook = { id:string; title:string; description:string; tags:string[]; author:string; status:"Draft"|"Review"|"Published"; content:string; evidence:Evidence[]; createdAt:string; updatedAt:string };
type Project = { id:number; name:string; projectPath:string; workspacePath:string };
type Citation = { id:string; notebookId:string; evidenceId:string; type:string; title:string; author:string; editor:string; publisher:string; publicationPlace:string; year:string; volume:string; chapter:string; page:string; manuscript:string; projectName:string; projectPath:string; documentName:string; reviewer:string; verified:boolean; accessDate:string; notes:string };
type BibliographyEntry = Citation & { formatted:string; issues:string[] };

const blank = { title:"", description:"", tags:"", author:"Local Researcher" };
const blankCitation = { type:"Manuscript", title:"", author:"", editor:"", publisher:"", publicationPlace:"", year:"", volume:"", chapter:"", page:"", manuscript:"", reviewer:"", verified:false, notes:"" };

export default function ResearchWorkbenchPage() {
  const [projects,setProjects]=useState<Project[]>([]); const [workspacePath,setWorkspacePath]=useState("");
  const [notebooks,setNotebooks]=useState<Notebook[]>([]); const [selectedId,setSelectedId]=useState("");
  const [query,setQuery]=useState(""); const [form,setForm]=useState(blank); const [message,setMessage]=useState("");
  const [evidence,setEvidence]=useState({type:"Passage",title:"",excerpt:"",projectPath:"",documentName:"",pageNumber:"",notes:""});
  const [citations,setCitations]=useState<Citation[]>([]); const [citation,setCitation]=useState(blankCitation);
  const [citationStyle,setCitationStyle]=useState("APA"); const [bibliography,setBibliography]=useState<BibliographyEntry[]>([]);
  const [validation,setValidation]=useState<{issueCount:number;results:{citationId:string;title:string;issues:string[]}[]} | null>(null);
  const selected=notebooks.find(n=>n.id===selectedId)||null;
  const filtered=useMemo(()=>notebooks.filter(n=>`${n.title} ${n.description} ${n.tags.join(" ")}`.toLowerCase().includes(query.toLowerCase())),[notebooks,query]);

  async function load(path=workspacePath){ if(!path)return; const data=await window.ocrStudio.listResearchNotebooks({workspacePath:path}); setNotebooks(data.notebooks||[]); setSelectedId(id=>(data.notebooks||[]).some((n:Notebook)=>n.id===id)?id:(data.notebooks?.[0]?.id||"")); }
  async function loadCitations(notebookId=selectedId){ if(!workspacePath||!notebookId){setCitations([]);setBibliography([]);return;} const data=await window.ocrStudio.listCitations({workspacePath,notebookId}); setCitations(data.citations||[]); const bib=await window.ocrStudio.buildBibliography({workspacePath,notebookId,style:citationStyle}); setBibliography(bib.entries||[]); }
  useEffect(()=>{ (async()=>{ const list=await window.ocrStudio.listRecentProjects(); setProjects(list); const path=list.find((p:Project)=>p.workspacePath)?.workspacePath||""; setWorkspacePath(path); if(path) await load(path); })().catch(e=>setMessage(e.message)); },[]);
  useEffect(()=>{ loadCitations().catch(e=>setMessage(e.message)); },[selectedId,workspacePath,citationStyle]);
  async function createNotebook(){ if(!workspacePath||!form.title.trim())return; const created=await window.ocrStudio.createResearchNotebook({workspacePath,notebook:{...form,tags:form.tags.split(",").map(x=>x.trim()).filter(Boolean)}}); setForm(blank); await load(); setSelectedId(created.id); }
  async function saveNotebook(patch:Partial<Notebook>={}){ if(!selected)return; const updated=await window.ocrStudio.updateResearchNotebook({workspacePath,notebook:{...selected,...patch}}); setNotebooks(items=>items.map(n=>n.id===updated.id?updated:n)); setMessage("Notebook saved."); }
  async function removeNotebook(){ if(!selected||!confirm(`Delete “${selected.title}”?`))return; await window.ocrStudio.deleteResearchNotebook({workspacePath,notebookId:selected.id}); await load(); }
  async function addEvidence(){ if(!selected||!evidence.title.trim())return; const project=projects.find(p=>p.projectPath===evidence.projectPath); await window.ocrStudio.addResearchEvidence({workspacePath,notebookId:selected.id,evidence:{...evidence,projectId:project?.id,projectName:project?.name,pageNumber:evidence.pageNumber?Number(evidence.pageNumber):null}}); setEvidence({type:"Passage",title:"",excerpt:"",projectPath:"",documentName:"",pageNumber:"",notes:""}); await load(); }
  async function removeEvidence(id:string){ if(!selected)return; await window.ocrStudio.removeResearchEvidence({workspacePath,notebookId:selected.id,evidenceId:id}); await load(); }
  async function exportNotebook(format:string){ if(!selected)return; const result=await window.ocrStudio.exportResearchNotebook({workspacePath,notebookId:selected.id,format}); if(result?.filePath)setMessage(`Exported to ${result.filePath}`); }
  async function addCitation(){ if(!selected||!citation.title.trim())return; await window.ocrStudio.createCitation({workspacePath,citation:{...citation,notebookId:selected.id,style:citationStyle}}); setCitation(blankCitation); await loadCitations(); setMessage("Citation added."); }
  async function citeEvidence(item:Evidence){ if(!selected)return; await window.ocrStudio.createCitationFromEvidence({workspacePath,notebookId:selected.id,evidence:item,defaults:{author:selected.author}}); await loadCitations(); setMessage("Evidence citation created."); }
  async function removeCitation(id:string){ await window.ocrStudio.deleteCitation({workspacePath,citationId:id}); await loadCitations(); }
  async function validate(){ if(!selected)return; const result=await window.ocrStudio.validateCitations({workspacePath,notebookId:selected.id}); setValidation(result); setMessage(result.valid?"All citations passed validation.":`${result.issueCount} citation issue(s) found.`); }
  async function exportBibliography(format:string){ if(!selected)return; const result=await window.ocrStudio.exportCitations({workspacePath,notebookId:selected.id,format,style:citationStyle}); if(result?.filePath)setMessage(`Bibliography exported to ${result.filePath}`); }

  return <div className="workbench-page">
    <header className="wb-hero"><div><span className="eyebrow">PHASE 8.0B</span><h2>Research Workbench & Citation Engine</h2><p>Write research notes, preserve evidence provenance, and produce publication-ready bibliographies.</p></div><div className="wb-stats"><b>{notebooks.length}</b><span>Notebooks</span><b>{notebooks.reduce((s,n)=>s+n.evidence.length,0)}</b><span>Evidence</span><b>{citations.length}</b><span>Citations</span></div></header>
    {!workspacePath && <div className="wb-warning">Create or open a project with a workspace before using Research Workbench.</div>}
    {message && <div className="wb-message">{message}</div>}
    <div className="wb-grid">
      <aside className="wb-list">
        <input placeholder="Search notebooks…" value={query} onChange={e=>setQuery(e.target.value)}/>
        <div className="new-card"><input placeholder="Notebook title" value={form.title} onChange={e=>setForm({...form,title:e.target.value})}/><textarea placeholder="Description" value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/><input placeholder="Tags, comma separated" value={form.tags} onChange={e=>setForm({...form,tags:e.target.value})}/><button onClick={createNotebook}>＋ Create notebook</button></div>
        <div className="notebook-list">{filtered.map(n=><button key={n.id} className={n.id===selectedId?"active":""} onClick={()=>setSelectedId(n.id)}><strong>{n.title}</strong><span>{n.status} · {n.evidence.length} evidence</span><small>{new Date(n.updatedAt).toLocaleString()}</small></button>)}</div>
      </aside>
      <main className="wb-editor">{selected ? <>
        <div className="editor-head"><input className="title-input" value={selected.title} onChange={e=>setNotebooks(ns=>ns.map(n=>n.id===selected.id?{...n,title:e.target.value}:n))}/><select value={selected.status} onChange={e=>saveNotebook({status:e.target.value as Notebook["status"]})}><option>Draft</option><option>Review</option><option>Published</option></select><button onClick={()=>saveNotebook()}>Save</button><button onClick={()=>exportNotebook("markdown")}>Export MD</button><button onClick={()=>exportNotebook("json")}>Export JSON</button><button className="danger" onClick={removeNotebook}>Delete</button></div>
        <textarea className="description-input" value={selected.description} placeholder="Research purpose and scope" onChange={e=>setNotebooks(ns=>ns.map(n=>n.id===selected.id?{...n,description:e.target.value}:n))}/>
        <textarea className="markdown-editor" value={selected.content} onChange={e=>setNotebooks(ns=>ns.map(n=>n.id===selected.id?{...n,content:e.target.value}:n))} onBlur={()=>saveNotebook()} spellCheck/>
        <section className="evidence-section"><h3>Evidence Library</h3><div className="evidence-form"><select value={evidence.type} onChange={e=>setEvidence({...evidence,type:e.target.value})}><option>Passage</option><option>Page</option><option>Entity</option><option>Relationship</option><option>Timeline Event</option><option>Comparison</option><option>AI Conversation</option></select><input placeholder="Evidence title" value={evidence.title} onChange={e=>setEvidence({...evidence,title:e.target.value})}/><select value={evidence.projectPath} onChange={e=>setEvidence({...evidence,projectPath:e.target.value})}><option value="">Select project</option>{projects.map(p=><option key={p.id} value={p.projectPath}>{p.name}</option>)}</select><input placeholder="Document" value={evidence.documentName} onChange={e=>setEvidence({...evidence,documentName:e.target.value})}/><input placeholder="Page" value={evidence.pageNumber} onChange={e=>setEvidence({...evidence,pageNumber:e.target.value})}/><textarea placeholder="Quoted passage or evidence summary" value={evidence.excerpt} onChange={e=>setEvidence({...evidence,excerpt:e.target.value})}/><button onClick={addEvidence}>Add evidence</button></div>
          <div className="evidence-list">{selected.evidence.map(item=><article key={item.id}><div><span>{item.type}</span><h4>{item.title}</h4><p>{item.excerpt||item.notes}</p><small>{[item.projectName,item.documentName,item.pageNumber?`Page ${item.pageNumber}`:""].filter(Boolean).join(" · ")}</small></div><div className="evidence-actions"><button onClick={()=>citeEvidence(item)}>Create citation</button>{item.projectPath&&<button onClick={()=>window.ocrStudio.openResearchSource(item.projectPath)}>Open source</button>}<button onClick={()=>removeEvidence(item.id)}>Remove</button></div></article>)}</div>
        </section>
        <section className="citation-section"><div className="citation-heading"><div><h3>Smart Citation Engine</h3><p>Generate citations from evidence, validate metadata, and export bibliographies.</p></div><div className="citation-toolbar"><select value={citationStyle} onChange={e=>setCitationStyle(e.target.value)}><option>APA</option><option>MLA</option><option>Chicago</option><option>Indic</option></select><button onClick={validate}>Validate</button><button onClick={()=>exportBibliography("markdown")}>Markdown</button><button onClick={()=>exportBibliography("bibtex")}>BibTeX</button><button onClick={()=>exportBibliography("ris")}>RIS</button><button onClick={()=>exportBibliography("csl")}>CSL JSON</button></div></div>
          <div className="citation-form"><select value={citation.type} onChange={e=>setCitation({...citation,type:e.target.value})}><option>Manuscript</option><option>Book</option><option>Chapter</option><option>Verse</option><option>Commentary</option><option>Journal</option><option>OCR Page</option><option>Web reference</option></select><input placeholder="Title *" value={citation.title} onChange={e=>setCitation({...citation,title:e.target.value})}/><input placeholder="Author" value={citation.author} onChange={e=>setCitation({...citation,author:e.target.value})}/><input placeholder="Year" value={citation.year} onChange={e=>setCitation({...citation,year:e.target.value})}/><input placeholder="Manuscript / document" value={citation.manuscript} onChange={e=>setCitation({...citation,manuscript:e.target.value})}/><input placeholder="Volume" value={citation.volume} onChange={e=>setCitation({...citation,volume:e.target.value})}/><input placeholder="Chapter" value={citation.chapter} onChange={e=>setCitation({...citation,chapter:e.target.value})}/><input placeholder="Page" value={citation.page} onChange={e=>setCitation({...citation,page:e.target.value})}/><input placeholder="Publisher" value={citation.publisher} onChange={e=>setCitation({...citation,publisher:e.target.value})}/><button onClick={addCitation}>Add citation</button></div>
          {validation && validation.issueCount>0 && <div className="citation-validation"><strong>{validation.issueCount} issue(s)</strong>{validation.results.filter(r=>r.issues.length).map(r=><div key={r.citationId}><b>{r.title}:</b> {r.issues.join("; ")}</div>)}</div>}
          <div className="citation-layout"><div><h4>Citation Records</h4><div className="citation-list">{citations.map(c=><article key={c.id}><div><b>{c.title}</b><small>{[c.author,c.year,c.page?`p. ${c.page}`:""].filter(Boolean).join(" · ")}</small></div><div>{c.projectPath&&<button onClick={()=>window.ocrStudio.openCitationSource(c.projectPath)}>Source</button>}<button onClick={()=>removeCitation(c.id)}>Delete</button></div></article>)}{!citations.length&&<p className="muted">No citations yet. Create one manually or from an evidence item.</p>}</div></div><div><h4>{citationStyle} Bibliography</h4><ol className="bibliography-list">{bibliography.map(entry=><li key={entry.id}><p>{entry.formatted}</p>{entry.issues.length>0&&<small>⚠ {entry.issues.join("; ")}</small>}</li>)}</ol></div></div>
        </section>
      </> : <div className="empty-workbench"><h3>Create your first research notebook</h3><p>Use notebooks to write analysis and collect traceable manuscript evidence.</p></div>}</main>
    </div>
  </div>;
}
