import {useEffect,useMemo,useState} from "react";
import "./InstitutionalRepositoryPage.css";
type Project={projectPath:string;projectName:string};
const api=window.ocrStudio as any;
const blank={id:"",title:"",creator:"",publisher:"",description:"",version:"1.0",status:"Draft",access:"Private",license:"CC BY 4.0",doi:"",localIdentifier:"",publicationDate:""};
export default function InstitutionalRepositoryPage(){
 const[projects,setProjects]=useState<Project[]>([]),[projectPath,setProjectPath]=useState(""),[publications,setPublications]=useState<any[]>([]),[deposits,setDeposits]=useState<any[]>([]),[events,setEvents]=useState<any[]>([]),[metrics,setMetrics]=useState<any>({}),[form,setForm]=useState<any>(blank),[tab,setTab]=useState("publications"),[message,setMessage]=useState("");
 const load=async(p:string)=>{if(!p)return;const r=await api.getRepositoryProject({projectPath:p});if(r.success){setPublications(r.publications);setDeposits(r.deposits);setEvents(r.events);setMetrics(r.metrics)}};
 useEffect(()=>{api.getRepositoryWorkspace().then((r:any)=>{const ps=r.projects||[];setProjects(ps);const p=ps[0]?.projectPath||"";setProjectPath(p);load(p)})},[]);
 const validation=useMemo(()=>{const issues=["title","creator","publisher","license","access"].filter(k=>!String(form[k]||"").trim());return{valid:issues.length===0,issues}},[form]);
 const save=async()=>{const r=await api.saveRepositoryPublication({projectPath,...form});setForm(r.publication);setMessage("Publication record saved.");await load(projectPath)};
 const exportMeta=async(format:string)=>{if(!form.id)return setMessage("Save the publication first.");const r=await api.exportRepositoryMetadata({projectPath,publication:form,format});if(r.filePath){setMessage(`Exported ${format}.`);await api.openRepositoryFile(r.filePath)}};
 const bag=async()=>{if(!form.id)return setMessage("Save the publication first.");const r=await api.createRepositoryBag({projectPath,publication:form});setMessage(`BagIt package created with ${r.fileCount} files.`);await load(projectPath);if(r.root)await api.openRepositoryFile(r.root)};
 return <div className="repo-page"><header><div><h2>Institutional Repository</h2><p>Publish, preserve, identify, and distribute scholarly editions and research datasets.</p></div><select value={projectPath} onChange={e=>{setProjectPath(e.target.value);load(e.target.value)}}>{projects.map(p=><option value={p.projectPath} key={p.projectPath}>{p.projectName}</option>)}</select></header>
 <section className="repo-metrics">{[["Publications",metrics.publications],["Published",metrics.published],["Deposits",metrics.deposits],["Validated",metrics.validated],["Preservation events",metrics.preservationEvents],["Public access",metrics.publicAccess]].map(([a,b])=><article key={String(a)}><b>{b||0}</b><span>{a}</span></article>)}</section>
 <nav>{["publications","deposits","preservation"].map(x=><button key={x} className={tab===x?"active":""} onClick={()=>setTab(x)}>{x}</button>)}</nav>{message&&<p className="notice">{message}</p>}
 {tab==="publications"&&<div className="repo-grid"><aside><h3>Publication records</h3><button className="new" onClick={()=>setForm(blank)}>+ New publication</button>{publications.map(p=><button className="record" key={p.id} onClick={()=>setForm(p)}><b>{p.title||"Untitled"}</b><span>{p.status} · v{p.version}</span></button>)}</aside><section className="editor"><h3>{form.id?"Edit publication":"New publication"}</h3><label>Title<input value={form.title} onChange={e=>setForm({...form,title:e.target.value})}/></label><div className="two"><label>Creator<input value={form.creator} onChange={e=>setForm({...form,creator:e.target.value})}/></label><label>Publisher<input value={form.publisher} onChange={e=>setForm({...form,publisher:e.target.value})}/></label></div><label>Description<textarea value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></label><div className="three"><label>Version<input value={form.version} onChange={e=>setForm({...form,version:e.target.value})}/></label><label>Status<select value={form.status} onChange={e=>setForm({...form,status:e.target.value})}>{["Draft","Under Review","Published","Withdrawn","Archived"].map(x=><option key={x}>{x}</option>)}</select></label><label>Access<select value={form.access} onChange={e=>setForm({...form,access:e.target.value})}>{["Public","Embargoed","Institution-only","Restricted","Private"].map(x=><option key={x}>{x}</option>)}</select></label></div><div className="two"><label>Licence<input value={form.license} onChange={e=>setForm({...form,license:e.target.value})}/></label><label>Publication date<input type="date" value={form.publicationDate} onChange={e=>setForm({...form,publicationDate:e.target.value})}/></label></div><div className="two"><label>DOI<input placeholder="10.xxxx/..." value={form.doi} onChange={e=>setForm({...form,doi:e.target.value})}/></label><label>Local identifier<input value={form.localIdentifier} onChange={e=>setForm({...form,localIdentifier:e.target.value})}/></label></div><div className={validation.valid?"validation ok":"validation"}><b>{validation.valid?"Ready for repository validation":"Metadata incomplete"}</b>{!validation.valid&&<span>Missing: {validation.issues.join(", ")}</span>}</div><div className="actions"><button onClick={save}>Save record</button>{form.id&&<button className="danger" onClick={async()=>{await api.deleteRepositoryPublication({projectPath,id:form.id});setForm(blank);await load(projectPath)}}>Delete</button>}</div><h4>Repository exports</h4><div className="exports"><button onClick={()=>exportMeta("dublin-core")}>Dublin Core XML</button><button onClick={()=>exportMeta("datacite")}>DataCite JSON</button><button onClick={()=>exportMeta("oai-dc")}>OAI-PMH record</button><button onClick={bag}>Create BagIt package</button></div></section></div>}
 {tab==="deposits"&&<section className="table"><h3>Repository deposits</h3><button onClick={async()=>{if(!form.id)return setMessage("Select and save a publication first.");await api.saveRepositoryDeposit({projectPath,publicationId:form.id,title:form.title,depositType:"Research publication",validationStatus:validation.valid?"Valid":"Needs attention",access:form.access,status:"Prepared"});await load(projectPath)}}>Create deposit from selected publication</button>{deposits.map(d=><article key={d.id}><b>{d.title}</b><span>{d.depositType} · {d.validationStatus} · {d.status}</span></article>)}</section>}
 {tab==="preservation"&&<section className="table"><h3>Preservation history</h3>{events.map(e=><article key={e.id}><b>{e.type}</b><span>{e.details} · {new Date(e.createdAt).toLocaleString()}</span></article>)}</section>}
 </div>;
}
