import {useEffect,useMemo,useState} from 'react';
import {getProjects} from '../../services/projectStorage';
import './ParallelCorpusPage.css';

const blankCorpus={name:'',description:'',sourceLanguage:'sa',targetLanguages:['te'],status:'Active'};
const blankAlignment={corpusId:'',location:'',sourceLanguage:'sa',sourceText:'',targetLanguage:'te',targetText:'',level:'Verse',relation:'Exact equivalent',confidence:100,status:'Draft',provenance:'Human',notes:''};
const blankTerm={sourceLanguage:'sa',sourceTerm:'',targetLanguage:'te',preferredTranslation:'',alternates:'',notes:''};

export default function ParallelCorpusPage(){
 const [workspaces,setWorkspaces]=useState<string[]>([]),[workspacePath,setWorkspacePath]=useState(''),[data,setData]=useState<any>({corpora:[],alignments:[],terminology:[],memory:[],summary:{}}),[message,setMessage]=useState('Select a workspace.'),[tab,setTab]=useState('alignments'),[corpus,setCorpus]=useState<any>(blankCorpus),[alignment,setAlignment]=useState<any>(blankAlignment),[term,setTerm]=useState<any>(blankTerm),[quality,setQuality]=useState<any>(null),[query,setQuery]=useState('');
 useEffect(()=>{void getProjects().then(ps=>{const w=[...new Set(ps.map(p=>p.workspacePath).filter(Boolean))] as string[];setWorkspaces(w);if(w[0])setWorkspacePath(w[0])})},[]);
 const load=async()=>{if(!workspacePath)return;const r=await window.ocrStudio.getParallelCorpusWorkspace({workspacePath});setData(r);setMessage(r.message);if(!alignment.corpusId&&r.corpora?.[0])setAlignment((a:any)=>({...a,corpusId:r.corpora[0].id}))};
 useEffect(()=>{void load()},[workspacePath]);
 const alignments=useMemo(()=>(data.alignments||[]).filter((a:any)=>!query||`${a.location} ${a.sourceText} ${a.targetText} ${a.targetLanguage}`.toLowerCase().includes(query.toLowerCase())),[data,query]);
 const saveCorpus=async()=>{const r=await window.ocrStudio.saveParallelCorpus({workspacePath,corpus});setMessage(r.message);setCorpus(blankCorpus);await load()};
 const saveAlignment=async()=>{const r=await window.ocrStudio.saveParallelAlignment({workspacePath,alignment});setMessage(r.message);setAlignment({...blankAlignment,corpusId:alignment.corpusId});await load()};
 const saveTerm=async()=>{const r=await window.ocrStudio.saveCorpusTerm({workspacePath,entry:term});setMessage(r.message);setTerm(blankTerm);await load()};
 const runQuality=async()=>{const r=await window.ocrStudio.getParallelCorpusQuality({workspacePath,corpusId:alignment.corpusId});setQuality(r.quality);setMessage(r.message)};
 const exportIt=async(format:string)=>{const r=await window.ocrStudio.exportParallelCorpus({workspacePath,format,corpusId:alignment.corpusId});setMessage(r.message);if(r.success)await window.ocrStudio.openParallelCorpusExport(r.filePath)};
 return <div className="pc-page"><header className="pc-hero"><div><span>Phase 10B · Milestone 6</span><h2>Parallel Corpus & Translation Alignment Studio</h2><p>Align multilingual texts, curate terminology, reuse translation memory, and measure translation quality.</p></div><button onClick={()=>void load()}>Refresh</button></header>
 <section className="pc-toolbar"><label>Workspace<select value={workspacePath} onChange={e=>setWorkspacePath(e.target.value)}>{workspaces.map(w=><option key={w}>{w}</option>)}</select></label><span>{message}</span></section>
 <section className="pc-stats"><article><b>{data.summary?.corpora||0}</b><span>Corpora</span></article><article><b>{data.summary?.alignments||0}</b><span>Alignments</span></article><article><b>{data.summary?.coverage||0}%</b><span>Approved coverage</span></article><article><b>{data.summary?.terms||0}</b><span>Terms</span></article><article><b>{data.summary?.memory||0}</b><span>Memory entries</span></article></section>
 <div className="pc-tabs"><button className={tab==='alignments'?'active':''} onClick={()=>setTab('alignments')}>Alignment Studio</button><button className={tab==='corpora'?'active':''} onClick={()=>setTab('corpora')}>Corpus Manager</button><button className={tab==='terms'?'active':''} onClick={()=>setTab('terms')}>Terminology</button><button className={tab==='quality'?'active':''} onClick={()=>{setTab('quality');void runQuality()}}>Quality Dashboard</button></div>
 {tab==='alignments'&&<div className="pc-grid"><section className="pc-panel"><div className="pc-head"><h3>Aligned segments</h3><input placeholder="Search aligned text" value={query} onChange={e=>setQuery(e.target.value)}/></div>{alignments.length===0?<p>No alignments yet.</p>:alignments.map((a:any)=><article className="pc-row" key={a.id} onClick={()=>setAlignment({...a})}><small>{a.location||'Unlocated'} · {a.level} · {a.relation}</small><div><p lang={a.sourceLanguage}>{a.sourceText||'—'}</p><span>⇄</span><p lang={a.targetLanguage}>{a.targetText||'—'}</p></div><footer><span>{a.sourceLanguage} → {a.targetLanguage}</span><b>{a.confidence}% · {a.status}</b></footer></article>)}</section><aside className="pc-panel pc-form"><h3>{alignment.id?'Edit':'New'} alignment</h3><label>Corpus<select value={alignment.corpusId} onChange={e=>setAlignment({...alignment,corpusId:e.target.value})}><option value="">Select corpus</option>{data.corpora?.map((c:any)=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label>Location<input value={alignment.location} onChange={e=>setAlignment({...alignment,location:e.target.value})} placeholder="1.2.3"/></label><div className="pc-pair"><label>Source language<input value={alignment.sourceLanguage} onChange={e=>setAlignment({...alignment,sourceLanguage:e.target.value})}/></label><label>Target language<input value={alignment.targetLanguage} onChange={e=>setAlignment({...alignment,targetLanguage:e.target.value})}/></label></div><label>Source text<textarea value={alignment.sourceText} onChange={e=>setAlignment({...alignment,sourceText:e.target.value})}/></label><label>Target text<textarea value={alignment.targetText} onChange={e=>setAlignment({...alignment,targetText:e.target.value})}/></label><div className="pc-pair"><label>Level<select value={alignment.level} onChange={e=>setAlignment({...alignment,level:e.target.value})}><option>Book</option><option>Chapter</option><option>Verse</option><option>Sentence</option><option>Phrase</option><option>Word</option></select></label><label>Relation<select value={alignment.relation} onChange={e=>setAlignment({...alignment,relation:e.target.value})}><option>Exact equivalent</option><option>Near equivalent</option><option>Interpretation</option><option>Gloss</option><option>Commentary</option><option>Cultural explanation</option><option>Idiomatic rendering</option></select></label></div><div className="pc-pair"><label>Confidence<input type="number" min="0" max="100" value={alignment.confidence} onChange={e=>setAlignment({...alignment,confidence:Number(e.target.value)})}/></label><label>Status<select value={alignment.status} onChange={e=>setAlignment({...alignment,status:e.target.value})}><option>Draft</option><option>Needs Review</option><option>Approved</option></select></label></div><button onClick={()=>void saveAlignment()} disabled={!alignment.corpusId||!alignment.sourceText||!alignment.targetText}>Save alignment</button></aside></div>}
 {tab==='corpora'&&<div className="pc-grid"><section className="pc-panel"><h3>Parallel corpora</h3>{data.corpora?.map((c:any)=><article className="pc-card" key={c.id} onClick={()=>setCorpus({...c})}><h4>{c.name}</h4><p>{c.description||'No description'}</p><small>{c.sourceLanguage} → {(c.targetLanguages||[]).join(', ')} · {c.status}</small></article>)}</section><aside className="pc-panel pc-form"><h3>{corpus.id?'Edit':'Create'} corpus</h3><label>Name<input value={corpus.name} onChange={e=>setCorpus({...corpus,name:e.target.value})}/></label><label>Description<textarea value={corpus.description} onChange={e=>setCorpus({...corpus,description:e.target.value})}/></label><label>Source language<input value={corpus.sourceLanguage} onChange={e=>setCorpus({...corpus,sourceLanguage:e.target.value})}/></label><label>Target languages<input value={(corpus.targetLanguages||[]).join(', ')} onChange={e=>setCorpus({...corpus,targetLanguages:e.target.value.split(',').map(x=>x.trim()).filter(Boolean)})}/></label><button onClick={()=>void saveCorpus()} disabled={!corpus.name}>Save corpus</button></aside></div>}
 {tab==='terms'&&<div className="pc-grid"><section className="pc-panel"><h3>Terminology bank</h3>{data.terminology?.map((t:any)=><article className="pc-card" key={t.id} onClick={()=>setTerm({...t})}><h4>{t.sourceTerm} → {t.preferredTranslation}</h4><small>{t.sourceLanguage} → {t.targetLanguage}</small><p>{t.notes}</p></article>)}</section><aside className="pc-panel pc-form"><h3>{term.id?'Edit':'Add'} terminology</h3><div className="pc-pair"><label>Source language<input value={term.sourceLanguage} onChange={e=>setTerm({...term,sourceLanguage:e.target.value})}/></label><label>Target language<input value={term.targetLanguage} onChange={e=>setTerm({...term,targetLanguage:e.target.value})}/></label></div><label>Source term<input value={term.sourceTerm} onChange={e=>setTerm({...term,sourceTerm:e.target.value})}/></label><label>Preferred translation<input value={term.preferredTranslation} onChange={e=>setTerm({...term,preferredTranslation:e.target.value})}/></label><label>Alternates<input value={term.alternates} onChange={e=>setTerm({...term,alternates:e.target.value})}/></label><label>Notes<textarea value={term.notes} onChange={e=>setTerm({...term,notes:e.target.value})}/></label><button onClick={()=>void saveTerm()} disabled={!term.sourceTerm||!term.preferredTranslation}>Save term</button></aside></div>}
 {tab==='quality'&&<div className="pc-panel"><div className="pc-head"><h3>Alignment quality</h3><select value={alignment.corpusId} onChange={e=>{setAlignment({...alignment,corpusId:e.target.value});setTimeout(()=>void runQuality(),0)}}><option value="">All corpora</option>{data.corpora?.map((c:any)=><option value={c.id} key={c.id}>{c.name}</option>)}</select></div><section className="pc-quality"><article><b>{quality?.coverage||0}%</b><span>Text coverage</span></article><article><b>{quality?.approvalRate||0}%</b><span>Approval rate</span></article><article><b>{quality?.averageConfidence||0}%</b><span>Average confidence</span></article><article><b>{quality?.missing||0}</b><span>Missing segments</span></article><article><b>{quality?.human||0}</b><span>Human alignments</span></article><article><b>{quality?.ai||0}</b><span>AI alignments</span></article></section><h3>Export corpus</h3><div className="pc-exports"><button onClick={()=>exportIt('html')}>HTML</button><button onClick={()=>exportIt('json')}>JSON</button><button onClick={()=>exportIt('csv')}>CSV</button><button onClick={()=>exportIt('tei')}>TEI XML</button><button onClick={()=>exportIt('tmx')}>TMX</button><button onClick={()=>exportIt('xliff')}>XLIFF</button></div></div>}
 </div>
}
