import {useEffect,useState} from "react";
import {getProjects} from "../../services/projectStorage";
import "./ResearchDiscoveryPage.css";
type A=any;
export default function ResearchDiscoveryPage(){
 const [workspaces,setWorkspaces]=useState<string[]>([]),[workspacePath,setWorkspacePath]=useState(""),[report,setReport]=useState<A>(null),[busy,setBusy]=useState(false),[message,setMessage]=useState("Select a workspace.");
 useEffect(()=>{void getProjects().then(ps=>{const w=[...new Set(ps.map(p=>p.workspacePath).filter(Boolean))] as string[];setWorkspaces(w);if(w[0])setWorkspacePath(w[0]);})},[]);
 const load=async(rebuild=false)=>{if(!workspacePath)return;setBusy(true);const r=rebuild?await window.ocrStudio.analyzeResearchDiscovery({workspacePath}):await window.ocrStudio.getResearchDiscovery({workspacePath});setReport(r.report||null);setMessage(r.message);setBusy(false)};
 useEffect(()=>{void load(false)},[workspacePath]);
 const s=report?.summary||{},m=report?.metrics||{};
 return <div className="rd-page"><header className="rd-hero"><div><span>Phase 9.0B · Scholarly discovery</span><h2>Research Discovery Engine</h2><p>Surface unanswered questions, manuscript variants, evidence gaps and publication risks.</p></div><button onClick={()=>load(true)} disabled={busy||!workspacePath}>{busy?"Discovering…":"Run discovery"}</button></header>
 <section className="rd-toolbar"><label>Workspace<select value={workspacePath} onChange={e=>setWorkspacePath(e.target.value)}>{workspaces.map(w=><option key={w}>{w}</option>)}</select></label><span>{message}</span></section>
 {!report?<div className="rd-empty">Build the manuscript index, then run discovery.</div>:<>
 <section className="rd-overview"><article className="rd-score"><div className="rd-ring" style={{"--score":`${s.readiness||0}%`} as any}><strong>{s.readiness||0}</strong><span>Readiness</span></div><p>Publication readiness is a research aid based on OCR quality, citations, graph density, review coverage and unresolved variants.</p></article>{[["Opportunities",s.opportunities],["Hypotheses",s.hypotheses],["Variants",s.variants],["Passages",s.passages]].map(([l,v])=><article className="rd-stat" key={String(l)}><strong>{Number(v||0).toLocaleString()}</strong><span>{l}</span></article>)}</section>
 <section className="rd-metrics">{[["OCR quality",m.ocrQuality],["Evidence coverage",m.evidenceCoverage],["Graph density",m.graphDensity],["Review score",m.reviewScore],["Consistency",m.conflictScore]].map(([l,v])=><article key={String(l)}><header><span>{l}</span><b>{v}%</b></header><i><em style={{width:`${v}%`}}/></i></article>)}</section>
 <div className="rd-grid"><section className="rd-card"><h3>Research opportunities</h3>{report.opportunities.map((o:A)=><article className={`rd-op ${o.severity}`} key={o.id}><strong>{o.count}</strong><div><h4>{o.title}</h4><p>{o.description}</p></div></article>)}</section><section className="rd-card"><h3>Dynamic research roadmap</h3>{report.roadmap.map((r:A)=><article className={`rd-road ${r.status}`} key={r.step}><b>{r.step}</b><div><h4>{r.title}</h4><p>{r.status==="complete"?"Completed":r.status==="ready"?"Ready to proceed":`${r.count} items require attention`}</p></div></article>)}</section></div>
 <section className="rd-card"><h3>AI-assisted hypotheses</h3><p className="rd-note">Hypotheses are suggestions for scholarly review, not factual conclusions.</p><div className="rd-hypotheses">{report.hypotheses.map((h:A)=><article key={h.id}><header><span>{h.title}</span><b>{h.confidence}% confidence</b></header><h4>{h.statement}</h4><p>{h.reasoning}</p>{h.evidence?.length>0&&<footer>{h.evidence.map((e:A)=><button key={e.id} onClick={()=>e.projectPath&&window.ocrStudio.openResearchDiscoverySource(e.projectPath)}>{e.projectName} · {e.documentName} · p.{e.pageNumber}</button>)}</footer>}</article>)}</div></section>
 <section className="rd-card"><h3>Evidence strength heatmap</h3><div className="rd-heatmap">{report.heatmap.map((x:A)=><button key={x.id} title={`${x.projectName} · ${x.documentName} · page ${x.pageNumber}\nStrength ${x.overall}%`} style={{opacity:.25+x.overall/135}} onClick={()=>x.projectPath&&window.ocrStudio.openResearchDiscoverySource(x.projectPath)}><span>{x.pageNumber}</span><small>{x.overall}</small></button>)}</div></section>
 <section className="rd-card"><h3>Variant clusters</h3><div className="rd-variants">{report.variants.map((v:A)=><article key={v.id}><header><b>{v.similarity}% similarity</b><span>{v.category}</span></header><div><p><strong>{v.left.projectName}</strong> · {v.left.documentName} · p.{v.left.pageNumber}</p><blockquote>{String(v.left.text||"").slice(0,220)}</blockquote></div><div><p><strong>{v.right.projectName}</strong> · {v.right.documentName} · p.{v.right.pageNumber}</p><blockquote>{String(v.right.text||"").slice(0,220)}</blockquote></div></article>)}</div></section>
 </>}</div>;
}
