import {useEffect,useMemo,useState} from 'react';
import {getProjects} from '../../services/projectStorage';
import './EditionComparisonPage.css';

export default function EditionComparisonPage(){
 const [workspaces,setWorkspaces]=useState<string[]>([]),[workspacePath,setWorkspacePath]=useState(''),[catalog,setCatalog]=useState<any[]>([]),[selected,setSelected]=useState<string[]>([]),[report,setReport]=useState<any>(null),[history,setHistory]=useState<any[]>([]),[message,setMessage]=useState('Select a workspace.'),[filter,setFilter]=useState('All'),[name,setName]=useState('New edition comparison');
 useEffect(()=>{void getProjects().then(ps=>{const w=[...new Set(ps.map(p=>p.workspacePath).filter(Boolean))] as string[];setWorkspaces(w);if(w[0])setWorkspacePath(w[0])})},[]);
 const load=async()=>{if(!workspacePath)return;const [c,h]=await Promise.all([window.ocrStudio.getEditionComparisonCatalog({workspacePath}),window.ocrStudio.listEditionComparisons({workspacePath})]);setCatalog(c.editions||[]);setHistory(h.items||[]);setMessage(c.message)};
 useEffect(()=>{setSelected([]);setReport(null);void load()},[workspacePath]);
 const toggle=(id:string)=>setSelected(s=>s.includes(id)?s.filter(x=>x!==id):[...s,id]);
 const compare=async()=>{const r=await window.ocrStudio.compareScholarlyEditions({workspacePath,editionIds:selected});setMessage(r.message);if(r.success){setReport(r.report);setName(`${r.report.editions.map((x:any)=>x.title).join(' vs ')}`)}};
 const save=async()=>{const r=await window.ocrStudio.saveEditionComparison({workspacePath,name,report});setMessage(r.message);if(r.success){setReport(r.comparison);await load()}};
 const exportReport=async()=>{const r=await window.ocrStudio.exportEditionComparison({workspacePath,report:{...report,name}});setMessage(r.message);if(r.success)await window.ocrStudio.openEditionComparison(r.filePath)};
 const visible=useMemo(()=>report?.rows?.filter((r:any)=>filter==='All'||r.classification===filter)||[],[report,filter]);
 return <div className="ec-page"><header className="ec-hero"><div><span>Phase 10B · Milestone 2</span><h2>Cross-Edition Comparison Lab</h2><p>Align parallel verse locations, identify textual variation, and preserve reusable scholarly comparison reports.</p></div><button onClick={compare} disabled={selected.length<2}>Compare {selected.length} editions</button></header>
 <section className="ec-toolbar"><label>Workspace<select value={workspacePath} onChange={e=>setWorkspacePath(e.target.value)}>{workspaces.map(w=><option key={w}>{w}</option>)}</select></label><span>{message}</span></section>
 <div className="ec-layout"><aside><h3>Select editions</h3><p>Choose two or more editions from the same workspace.</p>{catalog.map(e=><label className={selected.includes(e.id)?'checked':''} key={e.id}><input type="checkbox" checked={selected.includes(e.id)} onChange={()=>toggle(e.id)}/><div><b>{e.title}</b><small>v{e.version} · {e.status}</small><small>{(e.languages||[]).join(', ')||'No languages declared'}</small></div></label>)}<h3>Saved comparisons</h3>{history.length===0?<p className="empty">No saved comparisons.</p>:history.map(h=><article className="history" key={h.id}><button onClick={async()=>{const r=await window.ocrStudio.getSavedEditionComparison({workspacePath,id:h.id});if(r.success){setReport(r.report);setName(r.report.name);setSelected(r.report.editionIds||[])}}}><b>{h.name}</b><small>{h.summary?.totalAlignedRows||0} aligned verses</small></button><button className="delete" onClick={async()=>{await window.ocrStudio.deleteEditionComparison({workspacePath,id:h.id});await load()}}>×</button></article>)}</aside>
 <main>{!report?<section className="ec-empty"><b>⇄</b><h3>Build a synoptic comparison</h3><p>Select at least two editions to align their books, chapters, and verses by canonical numbering.</p></section>:<><section className="ec-summary"><article><b>{report.summary.totalAlignedRows}</b><span>Aligned locations</span></article><article><b>{report.summary.averageAgreement}%</b><span>Average agreement</span></article><article><b>{report.summary.substantive}</b><span>Substantive variants</span></article><article><b>{report.summary.missing}</b><span>Missing witnesses</span></article></section>
 <section className="ec-actions"><input value={name} onChange={e=>setName(e.target.value)}/><select value={filter} onChange={e=>setFilter(e.target.value)}>{['All','Agreement','Minor variation','Substantive variation','Missing witness'].map(x=><option key={x}>{x}</option>)}</select><button onClick={save}>Save comparison</button><button onClick={exportReport}>Export HTML</button></section>
 <section className="ec-coverage"><h3>Edition coverage</h3>{report.coverage.map((c:any)=><article key={c.editionId}><div><b>{c.title}</b><small>{c.verses} verses · {c.apparatus} apparatus · {c.decisions} decisions</small></div><div>{Object.entries(c.languages||{}).map(([l,n])=><span key={l}>{l}: {String(n)}</span>)}</div></article>)}</section>
 <section className="ec-table"><table><thead><tr><th>Location</th>{report.editions.map((e:any)=><th key={e.id}>{e.title}<small>v{e.version}</small></th>)}</tr></thead><tbody>{visible.map((r:any)=><tr key={r.key}><td><b>{r.key}</b><span className={`tag ${r.classification.toLowerCase().replace(/ /g,'-')}`}>{r.classification}</span><small>{r.agreement}% agreement</small></td>{r.cells.map((c:any)=><td className={!c.present?'missing':''} key={c.editionId}>{c.present?<><p>{c.criticalText||<em>No critical text</em>}</p>{Object.entries(c.languages||{}).map(([l,t])=>t?<details key={l}><summary>{l}</summary><p>{String(t)}</p></details>:null)}</>:<b>Missing</b>}</td>)}</tr>)}</tbody></table></section></>}</main></div></div>
}
